- test/image/README.md
@etpinard  
touch a little on the doc
> add info about docker document

- tasks/util/constants.js
npm3 will flatten node_modules, so the nested node_modules that is used
for copying the JSON over from Topojson will not be available in the
package's relative node_modules. This commit uses a synchronous check to
see if the path is valid and on failure with try to use the path
expected from npm3 installations.
Tested this fix on my repo using a git url: `"plotly.js": git://github.com/justinwoo/plotly.js.git#90e1c36ec12e431"`
> fix installation from npm3

- package.json
- tasks/header.js
- tasks/util/constants.js
@bpostlethwaite 
This PR adds a build task that prepends all dist file with the a license header that includes the most up-to-date package version.
> Add 'header' build task

- CONTRIBUTING.md
- README.md
> Some docs updates

- src/lib/search.js
- test/jasmine/tests/search_test.js
@etpinard @chriddyp gotta love 1-character fixes! The test `it('should treat a length-1 array as ascending'` failed before the fix. fixes #38
> length-1 bins count as ascending in Plotly.Lib.findBin

- package.json
- tasks/util/shortcut_paths.js
Two issues were preventing `npm run test-jasmine` on windows:
1) karma-browserify had a bug (See nikku/karma-browserify#154, fixed by bumping to karma-browserify 4.4.1).
2) On windows (or cygwin) paths generated by the requireTransform browserify transform contain platform-specific file separators (fixed by converting file separators).
> Fix test-jasmine on windows

- circle.yml
- docker-compose.yml
- test/image/README.md
@etpinard  Using docker-compose to ease the creation/stopping/deletion of testing docker container. Please refer the `test/image/README.md` for detail information.
> Using docker compose

- src/components/modebar/manage.js
- test/jasmine/tests/modebar_test.js
@bpostlethwaite 
Fixes some incomplete logic.
> Fix logic for display modebar plot config [fixes #56]

- CONTRIBUTING.md
- README.md
> Better contributing instructions 

- src/plot_api/plot_api.js
- src/plots/geo/geo.js
@alexcjohnson @bpostlethwaite @cldougl @mdtusz
This PR fixes:
- `Plotly.plot().then()` for the geo plot type
- `Plotly.newPlot().then()` for all trace types
> Plot promises fixups

- src/plot_api/plot_api.js
Fixes a minor spelling typo (`exits` vs `exists`) in the gdElement existence check. Current error reads:
`No DOM element with id 'myDiv' exits on the page.`
New error reads:
`No DOM element with id 'myDiv' exists on the page.`
> s/exits/exists/ in gdElement existence check error message

- src/traces/pie/index.js
Plotly.js pie charts accept `rgba()` marker colors, but drop any opacity value present. This codepen and image demonstrate: http://codepen.io/tlrdstd/pen/adoKgp
Running the same demo again with the attached change yields a chart with one transparent `rgba()` slice, one `rgba()` slice at 100% opacity, and an `rgb()` slice:
> Pie chart slices support transparent rgba() colors

- package.json
This won't break anything for people who have been using `require('plotly.js/dist/plotly.min.js')` because of how webpack resolves things.
> Added webpack field for entry point to dist

- test/image/README.md
@perigee @alexcjohnson @cldougl @mdtusz 
Better dockers docs, including info about `docker-machine` for Mac users.
> Better image testing docs

- src/plots/cartesian/graph_interact.js
- test/jasmine/tests/hover_label_test.js
- test/jasmine/tests/plot_interact_test.js
- fix for hover label bug: https://github.com/plotly/plotly.js/issues/43
- add hover tests
> Hover text bug

- src/plot_api/plot_api.js
Although called on a single element, getComputedStyle forces layout thrashing/reflow: https://gist.github.com/paulirish/5d52fb081b3570c81e3a
> Optimize by calling window.getComputedStyle once

- tasks/util/constants.js
- tasks/util/shortcut_paths.js
@justinwoo @mdtusz @bpostlethwaite 
I found a possibly cleaner way (you tell me :smile:) to find the path to the topojson files using node's [`require.resolve`](https://nodejs.org/api/globals.html#globals_require_resolve).
Supports both npm@2 and npm@3 .
> Use require.resolve to get path to topojson files

- circle.yml
- docker-compose.yml
- test/image/README.md
@etpinard  using new docker image instead
> using new docker image to test

- src/lib/svg_text_utils.js
- test/jasmine/tests/svg_text_utils_test.js
@scjody @alexcjohnson @bpostlethwaite @mdtusz @cldougl 
plotly.js is currently vulnerable to
```js
{
title: '<a href="javascript:alert(\'attack\')">XSS</a>'
}
```
now only certain protocols can be set in plotly `href` tags.
> Improve XSS check for <a href>

- src/plots/cartesian/graph_interact.js
At work, I develop on Firefox 31. I found that this browser does not support setting `z-index` via `style['z-index']`. However, it works correctly with `style.zIndex`.
[W3Schools](http://www.w3schools.com/jsref/prop_style_zindex.asp) (I know, I know...but I couldn't find a better reference for this) confirms that this is the expected, idiomatic behavior.
Firefox 38 seems to handle either approach correctly.
> idiomatically set zIndex when creating the Cartesian plot dragCover/coverSlip

- src/plots/layout_attributes.js
- src/plots/plots.js
- src/snapshot/tosvg.js
@alexcjohnson @bpostlethwaite @mdtusz @cldougl 
One nasty bug.
> Fix Firefox toImage failures

- src/traces/mesh3d/attributes.js
- src/traces/mesh3d/index.js
@cldougl @jackparmer @chriddyp 
Looking through some old Mikola PRs, I found some info about the mesh3d attribute from man himself.
> Add attribute descriptions for mesh3d

- src/plots/cartesian/graph_interact.js
- src/traces/pie/index.js
From issue https://github.com/plotly/plotly.js/issues/105.
It seems like a bit of an ugly hack, but there doesn't appear to be a standardized method for the click event. 
The ugly part of adding `slices[0][0].__data__.trace` is because for some reason, only the first slice in the `each` loop - the largest slice - contains the trace data.
I'd prefer to make some changes before merging this in, but I'm open to suggestions.
> Added click event on pie charts.

- src/plots/plots.js
- test/jasmine/tests/plots_test.js
10 seconds of adding code,
30 minutes of hoping the jasmine test would finish without disconnecting...
From issue https://github.com/plotly/plotly.js/issues/120
> Destroy modebar in purge step

- src/plot_api/plot_api.js
- src/plots/plots.js
> Remove all event listeners from gd

- src/plot_api/plot_api.js
- test/jasmine/tests/plot_api_test.js
The traces being added were missing `uid`, and as such, wouldn't get drawn. Adding `cleanData` will add the correct uid to the traces now.
> Clean data when addTraces is called

- src/traces/choropleth/index.js
- src/traces/choropleth/plot.js
- src/traces/scatter/attributes.js
Just removed a few references to `Plotly.___` where they cause circular dependency issues.
> Remove dependencies on Plotly for Choropleth

- src/plots/cartesian/graph_interact.js
@alexcjohnson @mdtusz @cldougl 
The lasso PR (https://github.com/plotly/plotly.js/pull/154) added a `fx.unhover` call which clear the hover data when drag box motions are initiated, which had the side effect of clearing the hover data for the click event emitter.
This PR moves the `fx.unhover` call to the `onMove` dragBox handler, bringing back click event.
That said, this has the side effect of making all drag boxes (e.g. select box, zoom box, colorbar, annotations and legend) clear hover upon drag.
> Bring back click events [fixes #173]

- test/jasmine/assets/mouse_event.js
- test/jasmine/tests/click_test.js
@mdtusz @alexcjohnson @cldougl 
so that https://github.com/plotly/plotly.js/issues/173 never happens again.
Useful resource: https://developer.mozilla.org/en/docs/Web/API/MouseEvent
The test below would have failed before the patch in https://github.com/plotly/plotly.js/pull/174
> Test click event handlers

- src/components/colorscale/attributes.js
- src/traces/scatter/attributes.js
- tasks/util/compress_attributes.js
I'm not 100% sure if this is in the right place, and you may have a better way to word the description. Quick pr though. 
Also changed: the `compress_attributes` regex for string arrays that are `join`ed. This will allow for any content in the string (before, `[` and `]` would break it.
> Update Descriptions for Colorscale

- src/components/modebar/buttons.js
Fixes https://github.com/plotly/plotly.js/issues/177. The drag mode `moveFn` isn't changed when the mode is changed, but after the drag event itself, so the pan drag action wasn't visible until mouseup. There doesn't seem to be a good *clean* way to do this without repeating code, so I have just made a call to `Fx.init`. Because this is only on mode change, it shouldn't be an issue to run `init` again.
> Add init step when changing dragmode

- src/plot_api/plot_api.js
- src/plots/plots.js
@mdtusz 
I found a simple way to remove the explicit dependency on `Pie` in plot_api.js meaning that `Pie` won't have to be part of core module.
> Remove explict dependency on Pie module from plot routine

- src/lib/index.js
- src/lib/search.js
- src/plot_api/plot_api.js
- test/jasmine/tests/plot_api_test.js
> Make deleteTrace handle big-indices-array properly [fixes #201]

- test/jasmine/tests/geo_interact_test.js
@mdtusz @cldougl 
part of https://github.com/plotly/plotly.js/issues/209
I found a nice way to determine the mouse (x,y) position. Open the Karma debugger, paste
```js
document.onmousemove = function(evt) { console.log(evt.clientX, evt.clientY); };
```
and hover over the position where you're trying to simulate a mouse over.
> add geo hover tests

- src/components/modebar/buttons.js
Quick typo that fixes https://github.com/plotly/plotly.js/issues/218.
> Fix typo on modebar geo zoom out

- src/plots/geo/geo.js
- src/plots/geo/index.js
- src/traces/choropleth/plot.js
- src/traces/scattergeo/plot.js
- test/jasmine/tests/geo_interact_test.js
@mdtusz @cpsievert 
About time I do this.
> Scattergeo and choropleth click and hover events

- src/plots/plots.js
- test/jasmine/tests/config_test.js
Resolves https://github.com/plotly/plotly.js/issues/222. It seems that the text.offsetParent call is unnecessary (except maybe in old versions of IE?).
In any case - chrome is deprecating it so we should remove it before then.
> Remove offsetparent call

- build/ploticon.js
- tasks/util/compress_attributes.js
@mdtusz 
The compress attributes transform has been failing for some attribute descriptions since https://github.com/plotly/plotly.js/commit/ee66bb347d65eab65745b954b61a8dcea8d976fe e.g.
- taken from `dist/plotly.js`
The new regular expression is on display here: http://www.regexr.com/3cmac
> Fix compress attributes

- src/plot_api/plot_api.js
- test/jasmine/tests/plot_promise_test.js
Added promise rejections missed in https://github.com/plotly/plotly.js/pull/77 meant to resolve part of https://github.com/plotly/plotly.js/issues/76
All tests pass.
> Added promise returns to Plotly.plot

- README.md
Something is up with the https://img.shields.io/ , where most our badges come from.
This PR grabs the dependency and dev-dependency badges directly from  https://david-dm.org/ and removes the npm-download badge to remedy the problem.
> Readme badges updates

- src/components/colorbar/draw.js
- src/components/titles/index.js
- src/plotly.js
- src/plots/cartesian/axes.js
@mdtusz 
another circular dependency pattern bites the dust :dash:
> De-circularize Titles and Axes

- README.md
Once we have a "getting started" page in the docs, we can add that as well.
> Add link to plotly-notebook-js

- src/plots/geo/geo.js
- src/traces/choropleth/plot.js
- src/traces/scattergeo/plot.js
- test/jasmine/tests/geo_interact_test.js
@mdtusz 
Visibility toggling for geo traces has been broken since e8ebcb2e302850b68fb6a2653be4c870e399887a
This PR fixes it and adds tests.
> Bring back geo trace toggle [fixes #244]

- src/components/modebar/buttons.js
- src/components/modebar/index.js
- src/components/modebar/manage.js
- src/plot_api/plot_api.js
- src/plots/cartesian/graph_interact.js
- src/plots/geo/geo.js
- src/plots/gl3d/layout/defaults.js
- src/plots/gl3d/layout/layout_attributes.js
- src/plots/gl3d/scene.js
- test/jasmine/assets/modebar_button.js
- test/jasmine/tests/fx_test.js
- test/jasmine/tests/gl3dlayout_test.js
- test/jasmine/tests/gl_plot_interact_test.js
- test/jasmine/tests/modebar_test.js
@mdtusz 
A follow-up of https://github.com/plotly/plotly.js/pull/246
This PR ended up being pretty big as I kept discovering bugs in some very uncharted waters of the plotly.js subplot sea :ocean: 
- Mode bar of multi-subplot-type graphs don't look hideous any more. This PR adds multi-plot-type mode bar buttons that can reset the view and toggle hover label visibility of all subplots at once.
- `layout.hovermode` and `layout.dragmode` are now also attributes of each gl3d scene. This was needed so that cartesian and gl3d hovermodes and dragmodes don't conflict with one another. In gl3d-only graphs `scene.hovermode` and `scene.dragmode` *inherit* from `layout.hovermode` and `layout.dragmode` respectively, keeping backward compatibility. 
- Mode bar button click handlers are now tested.
- …
> Subplot mode bars

- src/plots/plots.js
As the resize operation will modify the size of the plot only after a
timeout, if you call resize and then immediately do something based on
the current plot size, you'll get the "old" size. This fixes it.
> Plots.resize returns a Promise

- src/plots/plots.js
- test/jasmine/tests/plot_promise_test.js
Working off of https://github.com/plotly/plotly.js/pull/253
Added tests, and added a reject as well as passing in the `gd` to the resolved promise.
> Promise from resize

- devtools/test_dashboard/buttons.js
- devtools/test_dashboard/index.html
@mdtusz 
Couple things that should make our lives easier.
> Dashboard improvements

- test/jasmine/assets/custom_matchers.js
- test/jasmine/tests/gl_plot_interact_test.js
Changed to use `toBeCloseTo` and added a custom matcher for arrays of values. :tiger2:
> Make gl plot interaction test more robust

- src/plots/cartesian/tick_defaults.js
- test/jasmine/tests/axes_test.js
- test/jasmine/tests/gl_plot_interact_test.js
- test/jasmine/tests/hover_label_test.js
Fixes #261.
Pulled some of the coersions out from the block that checks for `showTickLabels` so things act as expected, and added a quick testeroonie in there for good measure in the future.
> Hoverformat bug with showTickLabels

- src/plots/cartesian/axes.js
- src/plots/cartesian/axis_ids.js
- src/plots/cartesian/graph_interact.js
- test/jasmine/tests/click_test.js
@mdtusz 
- A three-line bug fix
- Some linting
- 200+ of tests
> Handle autorange axes with 'reset' doubleClick config option [fixes #278]

- src/plot_api/plot_api.js
- src/plots/cartesian/index.js
- src/plots/cartesian/layout_defaults.js
- src/plots/geo/geo.js
- src/plots/geo/index.js
- src/plots/geo/layout/defaults.js
- src/plots/gl3d/index.js
- src/plots/gl3d/layout/defaults.js
- src/plots/plots.js
- src/traces/mesh3d/convert.js
- src/traces/surface/convert.js
- test/jasmine/tests/axes_test.js
- test/jasmine/tests/geo_interact_test.js
- test/jasmine/tests/geolayout_test.js
- test/jasmine/tests/gl3dlayout_test.js
- test/jasmine/tests/gl_plot_interact_test.js
- test/jasmine/tests/plot_interact_test.js
- test/jasmine/tests/plots_test.js
@alexcjohnson @mdtusz 
An alternative to https://github.com/plotly/plotly.js/pull/268 .
Comment https://github.com/plotly/plotly.js/pull/268#discussion_r53905458 made me realize that #268 was taking things a little too far.
This PR shares most commits with #268 but does **not** allow for orphan scenes and geos to be drawn. In other words, gl3d and geo subplots must be associated with a gl3d / geo trace respectively in order to be visible.
- `Plotly.deleteTraces` when applied to the last trace of a subplot now properly deletes that last trace 
+ deleting the last cartesian trace does **not** delete its axes (i.e orphan cartesian axes are allowed)
+ deleting the last gl3d/geo trace does delete its associated scene/geo
- `Plotly.deleteTraces` now works on heatmap and contour traces (yep, …
> A slightly less ambitious take on orphan subplots and 'delete last trace'

- test/syntax_test.js
@mdtusz 
So that post-merge commits like https://github.com/plotly/plotly.js/commit/6a79a62e2e941fe367b135b3739c304297ebe552 don't happen again.
> add check-header test

- src/css/_base.scss
**Repro**
(comment out style tag on IE11 to view broken behavior):
http://codepen.io/john-soklaski/pen/ZWYPbL
**Broken**
**Fixed**
> Fix clipping of charts on IE11

- src/components/legend/index.js
@mdtusz 
Fixes a bug introduced in https://github.com/plotly/plotly.js/pull/243 and discovered on plot.ly pdf and eps image exports. 
To be a valid <svg> all <rect> must have set width and height attributes. From https://validator.w3.org:
> Make legend scrollbar valid svg elements

- CHANGELOG.md
- build/plotcss.js
- package.json
@mdtusz so that https://github.com/plotly/plotly.js/pull/305#issuecomment-190907049 doesn't happen again.
> Commit build directory on version step

- circle.yml
- package.json
- tasks/test_export.sh
- test/image/export_test.js
@mdtusz so that we don't need to make hot fixes like https://github.com/plotly/plotly.js/pull/304 again.
> Test non-png exports

- src/plots/cartesian/graph_interact.js
- test/jasmine/tests/hover_label_test.js
Fixes https://github.com/plotly/plotly.js/issues/302.
> Bug hover text labels

- src/traces/choropleth/plot.js
- src/traces/scattergeo/plot.js
- test/jasmine/tests/geo_interact_test.js
@mdtusz 
This PR fixes a few issues that occur while streaming `scattergeo` and (to a lesser degree) `choropleth` traces. See the added tests. All of those cases were broken before these patches.
Most of the issues were a result of our implementation of the `d3` [update pattern](https://bl.ocks.org/mbostock/3808218). Whereas cartesian traces are [*purged*](https://github.com/plotly/plotly.js/blob/c735931f131e8c77c614e275dfdfa44229b1d5be/src/plots/cartesian/index.js#L80) on every `Plotly.plot` call, geo traces used the classic `d3` update pattern **but** did not account for a few details. Namely, that scatter traces have multiple modes.
> Better geo streaming

- src/lib/events.js
Fixes #325.
This shouldn't cause any issues at all as `$ === jQuery`.
> Replace $ check for jQuery check

- src/lib/events.js
- test/jasmine/tests/events_test.js
> Make events work in jQuery no-conflict scopes [fixes #350]

- src/plot_api/plot_api.js
- test/jasmine/.eslintrc
- test/jasmine/tests/click_test.js
@mdtusz 
A cheeky edge case discovered by @Jodana in https://github.com/plotly/plotly.js/issues/346 .
> Don't override saved initial ranges on data-updating restyle calls [fixes #346]

- src/plots/cartesian/constants.js
- src/plots/cartesian/graph_interact.js
- test/jasmine/assets/get_rect_center.js
- test/jasmine/tests/click_test.js
Fixes #333 
---
* shorten `DBLCLICKDELAY` from `600` to `300`
* remove `pauseForDrag` method and calls - this prevented the next mouse actions from completing until after a `DBLCLICKDELAY` delay
* removed unused artifact code from pre-open-source days
I can't see any areas that rely on the behaviour of the  `pauseForDrag` call, and nothing *appears* to be broken by the changes, but it is possible there is some user-interaction that may not behave properly if this delay is removed. 
@alexcjohnson @etpinard
> Doubleclick - Drag bug [Fixes #333]

- src/traces/scatter/attributes.js
Resolves #331 
It's tricky to be *crystal* clear in these, but I think this gets the point across.
@cldougl @etpinard
> Clarify color attribute descriptions

- src/components/rangeslider/create_slider.js
- test/jasmine/tests/range_slider_test.js
Very quick PR - just adding the call to `requestAnimationFrame`. This doesn't make things buttery smooth, but it's a big zero-effort-improvement. The next step will be to either make a call to something other than `relayout` or improve `relayout` performance.
> Rangeslider speedup

- src/.eslintrc
* Fixes the reported eslint errors in `src/traces/surface/convert.js`
and `src/traces/surface/convert.js`.
> Add Float32Array eslint global

- src/plots/plots.js
Otherwise IE/Edge can throw exceptions.
This fixes issue #375.
> Call getComputedTextLength() only on child elements of document.body

- src/components/rangeslider/create_slider.js
- src/components/rangeslider/index.js
- test/jasmine/tests/gl_plot_interact_test.js
- test/jasmine/tests/range_slider_test.js
Quick PR to ensure that the rangeslider isn't drawn (yet!) with gl plots.
> Rangeslider gl safety check

- test/jasmine/tests/shapes_test.js
From https://github.com/plotly/plotly.js/pull/378#issuecomment-204387178
> Add shapes tests

- src/components/drawing/index.js
@mdtusz cleaning up some pre-open-source ugliness I noticed this week.
> remove dependence on internal Plotly in drawing module

- src/components/shapes/index.js
- test/jasmine/tests/shapes_test.js
Here's an outline of the plan I'm following to fix issues #359 and #148:
I've checked refactoring `shapes.draw`hasn't introduced new bugs by running both the image and the jasmine tests.
> Shape clean up

- src/traces/scatter3d/convert.js
- test/jasmine/tests/gl_plot_interact_test.js
@mdtusz probably the easiest bug fix of all time.
> dispose delaunayMeadh on scatter3d toggle [fixes #399]

- src/traces/scatter/attributes.js
-- Update word order to make documentation more clear.
> Fix grammar errors in documentation.

- devtools/test_dashboard/devtools.js
Fixes #404 and improves perceived search performance.
* Set interval check to run `onReload` function only after the new `plotly.js` bundle has loaded.
* Debounce the fuzzy search for mocks by 250ms.
> Devtools patch

- src/plots/gl2d/scene2d.js
- src/plots/gl3d/scene.js
- test/jasmine/tests/gl_plot_interact_test.js
resolve #122.
using @mikolalysenko 's suggestion in https://github.com/plotly/plotly.js/issues/122#issuecomment-188501264
Moreover, this makes gl2d be drawn faster (to my :eyes:).
> Return promise after gl rendering 

- lib/heatmapgl.js
- lib/index.js
- package.json
- src/plots/gl2d/index.js
- src/plots/gl2d/scene2d.js
- src/traces/heatmap/calc.js
- src/traces/heatmapgl/attributes.js
- src/traces/heatmapgl/convert.js
- src/traces/heatmapgl/index.js
@mdtusz @bpostlethwaite @mikolalysenko 
as discussed, `heatmapgl` won't be part of the `dist` plotly.js bundle - until gl2d plots can have reliable image test support.
To register `heatmapgl` :
```js
var Plotly = require('plotly.js/lib/core');
Plotly.register(
require('plotly.js/lib/heatmapgl')
);
Plotly.plot(/* as normally */)
```
> Add heatmapgl trace module

- src/traces/choropleth/plot.js
- src/traces/scattergeo/plot.js
- test/jasmine/tests/geo_interact_test.js
@mdtusz easy
... but, really we have to bring geo hover on-par with cartesian at some point. This `mouseover` / `mouseout` business is minor league level at best.
> trigger plotly_unhover on geo mouseout [fixes #409]

- CONTRIBUTING.md
Gotta stay fresh 🍃 
I'll add a gif too but I don't want to pollute the repo with it so I'll add it directly so github can host it.
> Update CONTRIBUTING devdocs

- src/components/annotations/index.js
- src/components/shapes/index.js
- src/lib/gl_format_color.js
- src/lib/show_no_webgl_msg.js
- src/plot_api/set_plot_config.js
- src/plots/cartesian/axes.js
- src/plots/cartesian/dragbox.js
- src/plots/cartesian/graph_interact.js
- src/plots/plots.js
- src/plots/ternary/ternary.js
- src/snapshot/tosvg.js
@mdtusz some Friday afternoon :hammer: 
To sum up, don't use the require `src/plotly.js` unless you need to.
> Internal Plotly cleanup

- src/plots/cartesian/graph_interact.js
- test/jasmine/tests/click_test.js
- test/jasmine/tests/gl_plot_interact_test.js
- test/jasmine/tests/hover_label_test.js
Resolution for issue https://github.com/plotly/plotly.js/issues/313
As per issue discussion, the hoverinfo = 'none' case is solved but the hovermode = false isn't attempted in this PR.
> Click, hover callbacks should work despite hoverinfo = none, fixes #313

- src/plots/cartesian/dragbox.js
- test/jasmine/tests/click_test.js
Something went goofy in either #415 or #390 - likely a botched/missed conflict.
This resolves the issue (`graph_interact.js` was refactored and SVG-removal changes were misplaced) and a simple test for panning movement has been added.
> Fixup SVG Removal Panning

- test/image/compare_pixels_test.js
... that output random pixels from run to run.  
Now with a 1e-6 tolerance (added in https://github.com/plotly/plotly.js/pull/243/commits/1df89c53c0491acfcbd438ddd86a88977a7d2a18), these troublesome image test cases behave well from run to run.
Proof: see [CircleCI runs](https://circleci.com/gh/plotly/plotly.js/tree/add-back-random-image-tests). **Note that** the two failed runs were due to some other test failing.
> Un-skip troublesome image tests 

- test/jasmine/karma.conf.js
Fixes https://github.com/plotly/plotly.js/issues/444 by specifying a certain window size for the Chrome launcher. The numbers are simply derived from observing the window size in the properly working case.
CI karma/jasmine testing isn't impacted because, while CI piggybacks on this baseline config file, it specifies a separate browser (currently, Firefox). @etpinard suggested we don't change CI starting options right now.
I haven't experienced any problems with the fact that the `browser` we use is named differently (we can't name it `Chrome` as it's wired to mean plain vanilla Chrome and is being referenced as the `base`.
> Specify window size for the karma chrome launcher (Fixes #444)

- lib/contourgl.js
- lib/index.js
- package.json
- src/traces/contourgl/convert.js
- src/traces/contourgl/index.js
@mdtusz @bpostlethwaite @mikolalysenko 
as for `heatmapgl`, `contourgl` won't be part of the `dist` plotly.js bundle - until gl2d plots can have reliable image test support.
To register `contourgl` :
```js
var Plotly = require('plotly.js/lib/core');
Plotly.register(
require('plotly.js/lib/contour')
);
Plotly.plot(/* as normally */)
```
> Add contourgl trace module

- src/plots/gl3d/scene.js
- test/jasmine/tests/gl_plot_interact_test.js
Fixes issue #FI29. The added test cases aren't part of CircleCI as the test file is excluded, but they pass when run locally with fdescribe.
> Trigger plotly_relayout event when camera is reset to default or saved (Solves #FI29)

- test/jasmine/karma.conf.js
* This change allows the jasmine tests to be run within a VM.
> Run jasmine tests with --ignore-gpu-blacklist

- src/components/shapes/index.js
- src/plot_api/plot_api.js
- test/jasmine/tests/shapes_test.js
- Reverted f67ff4d1dcbd4a0a9e5d460ed10020861a8abcae
- Added comment to the code
- Added test
Fixes #464
> Fixes #464 (shapes not deleted when clearing all shapes)

- src/components/modebar/buttons.js
- src/plots/cartesian/dragbox.js
> Fix rangesldier + mode bar +/- and double click

- CONTRIBUTING.md
> add info about 'making pull requests'

- src/snapshot/tosvg.js
> Fix tosvg in IE11 (and possibly other browsers)

- src/plot_api/plot_api.js
- test/jasmine/tests/plot_api_test.js
- test/jasmine/tests/plots_test.js
Fixes #488. The d3 selection was only being created. This has added an update "join" on
the selection so the clips will be updated whenever relayout is called.
> Plot Area: Plot clip bug

- src/components/legend/draw.js
- src/lib/index.js
- test/jasmine/tests/config_test.js
- test/jasmine/tests/lib_test.js
Legends were changed to use a `<g>`, so the drag function now needs to use `translate` for positioning.
The cursor classes don't seem to work when in the middle of a click-drag, so instead we add the `move` cursor to the entire legend element when `editable`.
> Legend: fix drag movement when `editable: true`

- README.md
Although this typo is beautifully appropriate - we must deal with it.
> "chartset" typo to "charset"

- src/plots/cartesian/graph_interact.js
- test/jasmine/tests/hover_label_test.js
fixes https://github.com/plotly/plotly.js/issues/493
@mdtusz this commit https://github.com/plotly/plotly.js/pull/438/commits/c8b05edc2ed13ac3ec58f0b1ef45bed47554f253  in PR https://github.com/plotly/plotly.js/pull/438 introduced the bug in `v1.10.0`.
`hoverinfo: 'none'`  traces used to be skipped over in the search-closest-data routine before `v1.10.0` which fixed issue https://github.com/plotly/plotly.js/issues/313 . But, as a side-effect, that patch allowed  `Fx.getClosest` to pick `hoverinfo: 'none'` data points which were then passed to the hover label routine resulting in non apparent hover labels.
Note that `hovermode: 'closest'` only shows the hover label for the closest point. Previously, if two points were superimposed, only the data point of the first trace (as ordered in …
> Fix hovermode 'closest'  + hoverinfo 'none' with superimposed data bug

- src/components/shapes/index.js
- src/plot_api/plot_api.js
- test/jasmine/tests/shapes_test.js
For #496.
This restructures the shapelayers to be nested inside a generic `layer-above` or `layer-below` so that future images can be cleanly added to the above or below layers.
(Includes some linting I happened upon too...)
> Shapes: nest shapelayers in .above and .below classed groups

- src/components/shapes/attributes.js
> Copy over information about x-axis data type to shape attributes

- src/components/annotations/index.js
- test/jasmine/tests/config_test.js
Replaces https://github.com/plotly/plotly.js/pull/502.
Fixes the drag interaction on annotation text and the arrow.
> Annotation dragging

- src/plot_api/plot_api.js
- src/plots/cartesian/axis_defaults.js
- src/plots/cartesian/category_order_defaults.js
- test/jasmine/tests/axes_test.js
- test/jasmine/tests/cartesian_test.js
@mdtusz @monfera (cc @chriddyp )
Relayout calls involving axis `categoryorder` and `categoryarray` were not updating the graph properly.
This PR fixes this and cleans up a few things in the axis category defaults code. I hope @monfera won't mind.
> Fix relayout axis category

- src/plots/cartesian/constants.js
100 ms causes a 10 fps performance which feels like it's lagging behind your cursor. 30 ms feels too fast and noisy, 50 ms feels snappy yet stable.
https://github.com/plotly/plotly.js/issues/503
> Make chart mouse hover feel responsive

- devtools/test_dashboard/devtools.js
- devtools/test_dashboard/index.html
@mdtusz This PR adds back a few features that were (accidentally?) dropped during your devtool overhaul in https://github.com/plotly/plotly.js/pull/386. Namely:
- fonts are back
- MathJax is back
- Geo plots grab the required topojson files locally in `dist/`
> Devtool patch

- src/plot_api/plot_api.js
Real quick PR.
**In brief**: ensures that all the promises pushed into `gd._promises` are resolved before the final resolve.
The call to `Lib.syncOrAsync` never completes "fast enough" to cause `donePlotting` to be returned (at least, not in my semi-scientific testing) and all async things _should_ be pushing their promises to gd._promises.
> Promises: Ensure all `gd._promises` resolve before final resolve

- devtools/test_dashboard/devtools.js
_Have you ever been working in the devtools dashboard and wanted to get a mock, only to have to open the mock in an editor, copy the mock, then paste it in the browser console? I know I have. That's why I added `getMock` to the devtools and I'm here to share it with you today!_
> Devtools: Add `getMock` method

- src/plots/cartesian/graph_interact.js
- test/jasmine/tests/hover_label_test.js
Fixes #519.
Trying to find the _true_ source of this issue became a tangled mess of function diving until your head spins, so this is a quick fix that will prevent `NaN` values from getting through as text labels.
> HoverLabels: Check for <= 0 error values for log axes

- .eslintrc
- src/components/modebar/buttons.js
- src/core.js
- src/plot_api/to_image.js
- src/snapshot/download.js
- src/snapshot/filesaver.js
- src/snapshot/index.js
- src/snapshot/svgtoimg.js
- src/snapshot/toimage.js
- test/jasmine/tests/download_test.js
- test/jasmine/tests/toimage_test.js
*ref original pull https://github.com/timelyportfolio/plotly.js/pull/1 for very long discussion and commits*
-----
Addresses
- https://github.com/plotly/plotly.js/issues/83
- https://github.com/plotly/plotly.js/issues/89
- https://github.com/plotly/plotly.js/issues/264
- https://github.com/plotly/plotly.js/issues/345
- https://github.com/ropensci/plotly/issues/311
-----
----- 
**Plotly.toImage**
```
var img = document.createElement('img');
document.body.appendChild(img);
Plotly.plot()
.then(Plotly.toImage)
.then(function(url){
img.src = url;
});
// all the options
Plotly.plot()
.then(function(gd){
return Plotly.toImage({
format: 'png', //also can use 'jpeg', 'webp', 'svg'
height: 500,
width: 700
});
})
.then(function(url){
img.src = url;
});
```
**Plotly.downloadImage**
```
Plotly.plot() …
```
> add new promise-based toImage and downloadImage to Plotly

- src/plot_api/plot_api.js
- test/jasmine/tests/ternary_test.js
Ternary plots were not being restyled when `a, b, c` were updated. This remedies it in the simplest possible way.
I can't think of a much better way to test this - it's not a _great_ test, but it is better than nothing, and will still check that the plotted points have changed.
> Ternary restyle fix

- src/plot_api/to_image.js
- src/plots/geo/index.js
- src/plots/gl2d/index.js
- src/plots/gl3d/index.js
- src/plots/plots.js
- src/snapshot/toimage.js
- src/snapshot/tosvg.js
@mdtusz 
This PR continues on https://github.com/plotly/plotly.js/pull/491 and comes in preparation for our mapbox-gl [integration](https://github.com/plotly/plotly.js/compare/mapbox-wip). 
This PR creates an interface for subplot-specific steps during to-svg and supply-defaults such that `Plotly.plot` and `Plotly.toImage` are agnostic to which subplot types are registered.
- https://github.com/plotly/plotly.js/commit/6344fa41487b4409df74e4b569221e459fac0dd4 where `gl3d`, `gl2d`, `geo` to-svg routines are moved to their corresponding `basePlotModule`.
- https://github.com/plotly/plotly.js/commit/68a6a96f77151b7099246c559522e6241eebd720 where trace subplot attributes (e.g. `trace.scene` for gl3d subplots, `trace.geo` for geo subplots) are coerced by looping over the registered subplot …
> Seamless subplots

- src/lib/index.js
- src/plot_api/plot_api.js
- src/plots/cartesian/constants.js
- src/plots/cartesian/dragbox.js
- test/jasmine/assets/mouse_event.js
- test/jasmine/tests/click_test.js
- test/jasmine/tests/lib_test.js
This pr fixes #528. There was a regression when the last remaining nested `<svg>` tags were removed, so that when zooming with a scroll, the transforms were incorrect.
**In brief:**
* add `Lib.getScale/Lib.setScale` similar to `Lib.getTranslate/Lib.setTranslate`
* scale the plot when zooming with a scroll, based on the mouse position
* add a mouse scroll event helper for tests - usage is `mouseEvent('scroll', 100, 100, { deltaX: 0, deltaY: -500 })`
* reduce the redraw time to 50ms - this makes the scroll zoom feel much snappier in my opinion, but we may need to raise it to something a bit higher if there's issues on other machines/browsers (something closer to 100ms or 200ms)
* added a super simple test for the scrolling - because `relayout` is called 50ms after the scroll is done, we …
> Zoomscroll fix

- src/components/rangeslider/create_slider.js
- src/lib/index.js
- src/plot_api/plot_api.js
- test/jasmine/tests/range_slider_test.js
Fixes #557 
* Refactor the set method for the slider to set the slider, and plot data separately
* Check for both "types" of relayout update
* Remove `Lib.promiseError` which itself threw errors because `err.stack` is undefined - `Error.prototype.stack` is a non-standard feature that we shouldn't rely on, and `Lib.promiseError` is currently not being used anywhere in plotly.js or streambed.
> Rangeslider `Plotly.relayout` bugfix

- src/traces/contourgl/convert.js
- src/traces/scattergl/convert.js
@mdtusz fixes `scattergl` and `contourgl` graphs in [`core-js`](https://github.com/zloirock/core-js) environments, and possibly other environments with a more strict implementation of typed arrays.
> Init Float32Array with explicit length of 0

- src/plots/gl2d/index.js
- src/plots/plots.js
- test/jasmine/tests/gl_plot_interact_test.js
@mdtusz replotting from a blank graph is currently broken for `gl2d` plots.
For example,
```js
Plotly.plot(gd, []);
Plotly.plot(gd, [{ type: 'scattergl', x: [1, 2, 3], y: [2, 1, 2] }];
```
is falling.
This PR fixes :arrow_double_up: , while robustifying the `gl2d` clean-plot step and adding a comprehensive test case.
> fix gl2d replot

- src/traces/contour/attributes.js
reported on http://community.plot.ly/t/typos-in-api-reference-for-contour/1160 
fixed here.
> improve contour attribute descriptions

- src/plots/cartesian/graph_interact.js
- src/plots/ternary/index.js
- src/plots/ternary/ternary.js
- src/traces/scatterternary/plot.js
- test/jasmine/tests/hover_label_test.js
- test/jasmine/tests/scatterternary_test.js
Another PR in preparation for our mapbox-gl [integration](https://github.com/plotly/plotly.js/compare/mapbox-wip).
In brief, this PR generalizes the `Fx.hover` in `graph_interact.js`, so that it can use `xaxis` and `yaxis` from arbitrary _subplot_ instance. 
At the moment, only `cartesian` and `ternary` subplots use `Fx.hover` to handle their hover labels. But with after this PR, making `geo` and `mapbox` subplots use `Fx.hover` will be a piece of :cake: .
> Generalize hover picking routine

- src/traces/scattergl/convert.js
- test/image/mocks/gl2d_line_opacity.json
fixes https://github.com/plotly/plotly.js/issues/585 and https://github.com/plotly/plotly.js/issues/586
I added one test mock but without its corresponding baseline image (I can't wait for https://github.com/plotly/plotly.js/pull/572)
In the meantime, here's the proof:
the graph above is `gl2d` and the graph below is `svg`.
> scattergl lines fixes for opacity and connectgaps

- src/snapshot/svgtoimg.js
- src/snapshot/tosvg.js
- test/jasmine/tests/download_test.js
- test/jasmine/tests/toimage_test.js
Fixes #600.
This PR fixes a nasty little bug with image downloads. The culprit was font-family strings that were quoted and breaking the svg string used for image conversions.
The fix is not exactly _pretty_, but should be more robust now (previously, the quotation marks were escaped _before the svg was converted to a string_ - Chrome seems to not care for that and automatically replaces the double quotation marks.
> Toimage bug

- src/components/colorscale/attributes.js
- src/components/colorscale/color_attributes.js
- src/traces/bar/attributes.js
- src/traces/choropleth/attributes.js
- src/traces/contour/attributes.js
- src/traces/heatmap/attributes.js
- src/traces/histogram/attributes.js
- src/traces/histogram2d/attributes.js
- src/traces/histogram2dcontour/attributes.js
- src/traces/scatter/attributes.js
- src/traces/scatter3d/attributes.js
- src/traces/scattergeo/attributes.js
- src/traces/scattergl/attributes.js
- src/traces/scatterternary/attributes.js
- src/traces/surface/attributes.js
This is a PR that is a prequel to #581 (covered with a PoC already) with the purpose of centralizing shared color attribute specifications. This is a non-functional change that consolidates attribute lines but should leave operations identical, beyond the odd case where the new version sometimes has more descriptive descriptions (the former code sometimes used `marker` even when the reference was included in `marker.line`). The new vertex/line color spec solution for #581 can thus use the new color spec attributes in bulk, without having to add them one by one.
> DRY up color attributes

- circle.yml
- package.json
- tasks/run_in_testbed.sh
@mdtusz @perigee 
This PR DRYs up our `circle.yml`, while making it more readable (I think).
The script `run_in_testbed.sh` also works locally (once you have `lxc` installed), but isn't necessary as `docker exec` essentially does the same.
Note that `docker exec` does not work on CircleCI (see [here](https://circleci.com/docs/docker/#docker-exec)).
> Run in testbed shortcut script

- src/plot_api/plot_api.js
- test/jasmine/tests/layout_images_test.js
@mdtusz 
For example,
```js
Plotly.relayout(gd, { 'images[0].x': 0, 'images[0].y': 1 });
```
is broken currently.
The fix was easy ... once I made sense of all those tiny relayout variable names.
> Fixup relayout images in { astr: val } notation

- src/traces/histogram/attributes.js
Resolves [#614](https://github.com/plotly/plotly.js/issues/614)
> Changing Histogram parameter descriptions

- test/image/compare_pixels_test.js
(cherry picked from commit 8240de2)
This is another place where a non-json file can trip up the process. With this change, `npm run test-image` will only attempt to process `.json` files rather than reporting ILLEGAL token.
> Ignore files in the mock directory that aren't .json (e.g. .DS_Store)

- src/plots/cartesian/graph_interact.js
- test/jasmine/tests/hover_label_test.js
fixes https://github.com/plotly/plotly.js/issues/606
by grabbing refs to x/y axis using `Axes.getFromId` instead of looking into `fullLayout._plots` -
as it was done before commit https://github.com/plotly/plotly.js/pull/575/commits/858a3388a316544ee298ef86d65d70c83a160426 .
But really, the axis refs in `fullLayout._plots` should **always** be up-to-date. A future maintenance PR should address this.
> Fix hover label after resize bug

- src/traces/scatter/select.js
- test/jasmine/tests/select_test.js
fixes https://github.com/plotly/plotly.js/issues/588
easy.
> Handle non-visible trace in dragmode 'select' and 'lasso' 

- src/plots/ternary/ternary.js
- test/jasmine/tests/ternary_test.js
fixes https://github.com/plotly/plotly.js/issues/628
> Properly handle `staticPlot` plot config in ternary subplots

- test/image/README.md
@etpinard  @mdtusz 
Update the `testbed` document
> update doc for new testbed setting

- src/components/legend/draw.js
- test/jasmine/tests/legend_test.js
fixes https://github.com/plotly/plotly.js/issues/649
And also fixes `relayout` for `legend.bgcolor` which was broken.
Easy fix. We were only setting border and bg attributes to the `enter` selection. This PR correctly sets them on the `merge` selection.
> Fix legend border relayout bug

- src/traces/heatmap/calc.js
- test/jasmine/assets/custom_matchers.js
- test/jasmine/tests/contour_test.js
- test/jasmine/tests/heatmap_test.js
fixes https://github.com/plotly/plotly.js/issues/605
and also the case where `x` or `y` is set to `[]` for heatmap and contour traces.
This PR also adds a `toBeClose2DArray` custom jasmine matcher, which is convenient to assert 2D arrays like heatmap and contour `z`.
> Fix heatmap brick generation edge cases

- src/components/images/draw.js
- test/jasmine/tests/layout_images_test.js
fixes https://github.com/plotly/plotly.js/issues/670
@mdtusz on `master` we can have multiple images of the same source on a given graph.
> Fix layout images add / remove

- src/components/dragelement/index.js
- src/components/shapes/index.js
- test/jasmine/tests/shapes_test.js
* Added drag element to shapes
* Added tests
* Addresses https://github.com/plotly/streambed/issues/1525#issuecomment-225043702
---
Resubmitted PR after:
- removing `console.log` from tests,
- and checking tests pass locally with both Chromium and Firefox.
> Implement draggable shapes

- src/plots/mapbox/convert_text_opts.js
- src/plots/mapbox/layers.js
- src/plots/mapbox/layout_attributes.js
- src/plots/mapbox/layout_defaults.js
- src/plots/mapbox/mapbox.js
- src/traces/scattermapbox/attributes.js
- src/traces/scattermapbox/convert.js
- src/traces/scattermapbox/defaults.js
- test/image/assets/get_image_paths.js
- test/image/mocks/mapbox_layers.json
- test/jasmine/assets/has_webgl_support.js
- test/jasmine/karma.ciconf.js
- test/jasmine/tests/mapbox_test.js
- test/jasmine/tests/scattermapbox_test.js
@chriddyp please review.
- Two  _new_ `mapbox.layers` types :arrow_right: `'circle'` and `'symbol'` (along side the current `'fill'` and `'line'`). This allows GeoJSON point geometries to be drawn as mapbox [`circle`](https://www.mapbox.com/mapbox-gl-style-spec/#layers-circle) or symbol layers.
- Some mapbox jasmine tests are now tested on CircleCi. All mapbox jasmine tests that do no required a `gl` context are now tested on CircleCI. So that hot fixes like https://github.com/plotly/plotly.js/commit/9c7254887954c77c8010d4896babd57fd9d703d2 won't be needed again. See https://github.com/plotly/plotly.js/commit/4a8563b5dcf3045b0407e9f7fe6acb4aaa4054ba for more.
- The `mapbox.layers` attribute changed a little. They are now more one-to-one with the mapbox layer …
> Miscellaneous mapbox tweaks

- src/traces/surface/attributes.js
As per Emilia's email: @jackparmer
> project description edit

- src/traces/heatmap/plot.js
- test/jasmine/tests/heatmap_test.js
I forgot to move the `xlink:href` line in https://github.com/plotly/plotly.js/pull/655/commits/2ef4411923eb9a0ed452fa797a209af76e53d78c from the enter to the update selection.
My mistake.
> Fix heatmap colorscale restyles

- src/plots/mapbox/layers.js
- test/jasmine/tests/mapbox_test.js
Previously,
```js
// create an empty layer
relayout(gd, {'mapbox.layers[0]': {}});
// add geojson to that layer
relayout(gd, {'mapbox.layers[0].source': geojson});
```
resulted in errors. This PR fixes it.
> Make invalid mapbox layers work with relayout 

- package.json
This PR
- bumps `karma` to `1.1.0` 
- bumps `eslint` to `3.0.0`
with no patches to our code required, this is, if we trust CircleCI.
> Bump dev dependencies

- src/traces/bar/set_positions.js
- test/jasmine/tests/bar_test.js
fixes #639
This PR cherry picks the commits of #687 and adds a few test cases using the bar `calc` / `setPositions` testing routine introduced in https://github.com/plotly/plotly.js/pull/716/.
In brief, as @keeganmccallum found, we must bucket stacks starting from `0` / stacking in the +ve directions and stacks starting from `0` / stacking in the -ve direction in 2 separate buckets. We do so here by using the `"-0"` identifier to store the stacks starting from `0` / stacking in the -ve direction.
> Fix bar relative first bucket

- src/plot_api/plot_api.js
- src/plots/gl2d/scene2d.js
- src/plots/plots.js
- test/jasmine/tests/gl_plot_interact_test.js
Commit c123ebc helps a lot - not only with a significantly reduced (though not yet fully eliminated) memory leak, but also, causes a `stop` for the point picker requestAnimationFrame loop, so the purportedly idempotent `plotNew` function doesn't leave behind an orphaned, CPU eating rAF loop with potentially large arrays.
It may be that part of the residual leakage is related to the rAF acting as a closure with variable capture: even if the rAF is stopped by causing `stop = true` via the intended destroy sequence, maybe some state is still retained. Check this among other things.
Unrelated to the leakage, we identified the rAF based approach as something we might want to improve upon. 
PR is WIP not only because it's not a full fix and it's as yet untested, but also the code will probably …
> Memory leak fixes

- src/components/modebar/buttons.js
- src/plot_api/plot_api.js
- src/plots/cartesian/dragbox.js
- test/jasmine/tests/fx_test.js
fixes https://github.com/plotly/plotly.js/issues/657
Previously, we made the main dragbox inactive whenever both xaxis and yaxis were `fixedrange: true` regardless of the `dragmode`. This is of course correct for dragmode `'pan'` and `'lasso'` but wrong for `'lasso'` and `'select'`. This PR fixes the latter two cases. In addition, this PR cleans up some modebar -> relayout code paths.
> Make dragmode 'lasso' & 'select' work with fixedrange axes

- test/jasmine/tests/extend_test.js
I made a separate PR out of it b/c it can be merged irrespective of the speedup (https://github.com/plotly/plotly.js/pull/732) or discussed here if it's not desirable to lock in this specific behavior. Once it gets the green light, then the speedup just needs to comply with whatever tests.
> Reifies not yet covered, preexisting behavior of Lib.extendDeep

- src/lib/extend.js
This PR has the same effect on speed as the suggestion in https://github.com/plotly/plotly.js/pull/726#issuecomment-231656623
The referred suggestion isn't obsoleted by this PR, because `deepExtend`, by its nature, is still expensive: with large datasets, `Plotly.restyle` will still allocate and populate very large arrays (though much faster if this PR is merged). 
Similarly, this PR can be useful even outside the original speed problem, as it generally speeds up structure extension when large, simple arrays are present.
> Speed up Lib.extendDeep (_extend) for arrays that have no object, array elements

- src/plots/gl2d/index.js
- src/plots/gl3d/scene.js
Cherry-picking @mikolalysenko 's commit 778560bb85dff1bd3dfebb5416f8d23801ec8ab8 off PR https://github.com/plotly/plotly.js/pull/572 and fixing the merge conflict to make gl2d images non-blurry. Example:
before
after
**Note:** this PR does not fix all our gl2d images trouble namely the lack of image test support. See  https://github.com/plotly/plotly.js/pull/572#issuecomment-222178770 for more info.
> Make gl2d snapshot non-blurry

- src/plots/gl2d/scene2d.js
Solves the symptoms of https://github.com/plotly/plotly.js/issues/730 in that it reduces idle CPU utilization from 100% to around 5% at 500k-1m data points (as measured even for non-fancy 2d WebGL scatterplot)
> Bypassing most of the heavy lifting in the rAF for when there's no interaction

- src/lib/svg_text_utils.js
- test/jasmine/tests/svg_text_utils_test.js
resolves https://github.com/plotly/plotly.js/issues/642
See https://github.com/plotly/plotly.js/commit/d58d3bee92cbed88e2da250753d7dcb374d42e1d and https://github.com/plotly/plotly.js/commit/f6a5c673a07cbe3cc451b10c7af7a21e51ef8cf6
> A few fixes in convertToTspans

- src/lib/queue.js
- src/plot_api/plot_api.js
- src/plot_api/plot_config.js
- test/jasmine/tests/lib_test.js
- test/jasmine/tests/plot_api_test.js
In brief this PR,
- starts off by cherry-picking @monfera's commits from https://github.com/plotly/plotly.js/pull/726 
- lints a few things, 
- makes the queue length configurable via a new `queueLength` config option
- and adds a few tests for `Queue`
> Set undo/redo queue length via setPlotConfig

- src/components/colorscale/is_valid_scale_array.js
- src/core.js
- src/lib/coerce.js
- src/lib/index.js
- src/plot_api/validate.js
- test/jasmine/tests/colorscale_test.js
- test/jasmine/tests/lib_test.js
- test/jasmine/tests/validate_test.js
resolves https://github.com/plotly/plotly.js/issues/598
based off [`plotly-validate`](https://github.com/plotly/plotly.js/compare/plotly-validate) and [`lib-validate`](https://github.com/plotly/plotly.js/compare/lib-validate).
```js
var data = [{
type: 'bar',
y: [2, 1, 2],
orientation: 'horizontal'
}];
var out = Plotly.validate(data);
console.log(out[0].msg));
// "In data trace 0, key orientation is set to an invalid value (horizontal)"
```
This PR expose a top-level method allowing users to validate their input `data` and `layout`. 
`Plotly.validate` calls `Plots.supplyDefaults` and `PlotSchema.get` and a new [`Lib.validate`](https://github.com/plotly/plotly.js/commit/e94eec31ca160e29f221fdcd5d1f048f1b8cb117) method internally to determine if:
- [code `'object'`] a container key isn't …
> Introducing Plotly.validate(data, layout)

- src/components/drawing/index.js
> Add a z-index to js-plotly-tester as a workaround for a chrome bug 

- src/traces/scattermapbox/convert.js
- test/jasmine/tests/scattermapbox_test.js
The `mapbox-gl` API for `arrayOk` attributes (they call it [data-driven](https://www.mapbox.com/blog/data-driven-styling/) :smiley: ) links values in the features geojson `properties` field to a set of `stops`. These stops map the geojson properties values to mapbox-gl paint settings per feature (as opposed to a source-wide setting). Note that the stop values must be unique.
> Fix repeated val case in scattermapbox convert step

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
The previously merged issue & PR template guidelines had ugly linebreaks (obv in hindsight since it's not rendered markdown). Also linked CONTRIBUTING.md to the new templates to keep DRY.
> Clean up issue & PR guidelines

- src/plot_api/plot_api.js
- src/plots/mapbox/index.js
- src/plots/mapbox/layout_attributes.js
- src/plots/mapbox/layout_defaults.js
- src/plots/mapbox/mapbox.js
- test/jasmine/tests/mapbox_test.js
@chriddyp 
Users can now register their mapbox access token via `layout.mapbox.accesstoken`:
```js
var layout = {
mapbox: {
accesstoken: 'pk.124faEdgfsar2wsasdfsdgradgafdgasd'
}
};
```
This is especially important for users wanting to use a custom map style - where setting the access token in `layout` guarantee that the map will look the same regardless of the specified `config` options.
If `mapbox.accesstoken` isn't specify, the config `mapboxAccessToken` is used.
> Make mapbox access token configurable via layout attribute

- devtools/test_dashboard/devtools.js
A tiny PR to set and load the currently selected mock via a hash fragment. `Tabs.reload()` and `Tabs.plotMock(...)` is able to replot the mock, but command-R is my natural instinct and always requires me to re-locate the mock.
An easy nice-to-have, so let me know if there's a better way or any side effects I'm not aware of.
> Persist the current test dashboard mock on page reload

- src/traces/scatter/plot.js
See: #760 
See related point scaling PR: #762
See codepen example (includes point scaling PR, visible on scrollZoom): http://codepen.io/rsreusser/pen/OXvmjR?editors=0010
This is basically a one-line commit that disables scaling on scatter paths. It can be applied in `lineGroupStyle`, but since it has no effect in the other places where it's used (except for contours, where this could also be applied), it seems more targeted to just apply it to scatter lines directly.
This does not solve the point scaling problem. See example at: http://rickyreusser.com/plotly-expression-transform/ (which actually applies it in the drawing component, but for the sake of illustration, the effect is the same while scrollzoooming)
cc: @mdtusz
> Non-scaling SVG scatter lines

- src/lib/index.js
- src/plots/cartesian/dragbox.js
- test/jasmine/tests/lib_test.js
See issue: #760
See related line scaling PR: #761 
See codepen example (visible on scrollZoom): http://codepen.io/rsreusser/pen/OXvmjR?editors=0010
This PR compensates for point scaling by applying an inverse scale transform. It's simple, but kind of an ugly hack since it requires stripping any existing scale from points before applying a new scale. That may make it prohibitive, but it was a bit easier than expected, so maybe it's not unreasonable. cc @mdtusz
> Non-scaling SVG scatter points

- src/components/colorscale/calc.js
- src/traces/scatter/colorscale_calc.js
- src/traces/scatter/line_defaults.js
- src/traces/scatter/marker_defaults.js
- test/jasmine/tests/scatter3d_test.js
fixes https://github.com/plotly/plotly.js/issues/750
The :meat_on_bone: of this PR is in https://github.com/plotly/plotly.js/commit/b9a471ebfec5355f9ceadd46903de2cf8016f28d where we now explicitly skip `line.color` --> `marker.line.color` inheritance when `line.color` is an array. 
The errors described in #750 were due to the colorscale calc step complaining about `gd.data[i].marker.line` not being defined. Errors here are fine as `hasColorscale(marker.line)` should be `false` unless the user make `marker.line.color` support a colorscale. The problem was in the default step.
> Fix scatter3d marker.line.color inheritance

- src/plot_api/plot_api.js
- test/jasmine/tests/mapbox_test.js
Fixes bug introduced in https://github.com/plotly/plotly.js/pull/729 and on display here: http://codepen.io/lpan/pen/kXJzbY?editors=0011 discovered by @lpan .
```js
Plotly.plot(gd, data, layout).catch(function(err) {
console.log('works again');
});
```
> Mapbox access token catches

- src/lib/svg_text_utils.js
- test/jasmine/tests/svg_text_utils_test.js
I don't believe this is necessary for security, but it makes our code more obviously secure.
> HTML-encode attributes in <tspan>s and <a>s

- src/components/colorbar/has_colorbar.js
- src/components/colorscale/has_colorscale.js
- src/components/rangeslider/defaults.js
- src/lib/is_plain_object.js
- src/plots/mapbox/layers.js
- src/traces/scatter/subtypes.js
`Lib.isPlainObject` fails in our `imagetest` docker image test container at the moment.
More specifically, 
```js
Object.getPrototypeOf(obj) === Object.prototype
```
is `false` for _plain_ objects in `imagetest`. This behaviour is due to how the async utility [`lash`](https://github.com/bpostlethwaite/lash) applies functions to objects. Making a fix `lash` and/or the `imagetest` would have been arduous, so I decided to patch `Lib.isPlainObject` instead.
The patch in  https://github.com/plotly/plotly.js/commit/c09cbb3f2d53fe30126e1c233a5a8ea11dd79d35 makes `Lib.isPlainObject` only check for 
```js
Object.prototype.toString.call(obj) === '[object Object]'
```
in `nw.js` environments. This lead to 
```js
function A() {}
Lib.isPlainObject(new A());
```
to return `true`. I'd argue that this is …
> Enforce is-plain-object

- src/components/rangeselector/defaults.js
- test/jasmine/tests/range_selector_test.js
fixes https://github.com/plotly/plotly.js/issues/777
**N.B.** This PR needs to #792 to pass the tests.
Very easily, this PR makes the range selector defaults skip over non-plain-object button items. So that:
```js
Plotly.relayout(gd, 'xaxis.rangeselector.buttons[0]', 'remove');
```
is now functional.
> Range selector buttons deletion

- src/lib/extend.js
- src/lib/index.js
- test/jasmine/tests/extend_test.js
This PR implements the `extendDeepNoArrays` library function that does a regular deep extend except transferring arrays and not recursing instead of also duplicating arrays. It includes tests but not any use so that @monfera can use it in his code right away.
> Add extendDeepNoArrays variant

- test/jasmine/tests/plot_css_test.js
See: #764 
cc: @etpinard @nielsenb-jf 
The [child window test](https://github.com/plotly/plotly.js/blob/master/test/jasmine/tests/plot_css_test.js#L96-L114) in `plot_css_test.js` is asynchronous but was not implemented as such. As a result, things didn't get cleaned up and d3 transitions after this test gave a cryptic `TypeError: d3_window(...) is undefined` error. This PR makes all three tests asynchronous.
For reference, strategies used to debug:
- [karma-verbose-reporter](https://www.npmjs.com/package/karma-verbose-reporter) to output the current test (otherwise it just halts without any indication of where)
- specified `files: [...]` explicitly + alphabetically in `karma.ciconf.js` and removed them via bisection until the tests that interacted problematically were isolated
> Make plot_css_test.js asynchronous

- src/lib/svg_text_utils.js
- src/plots/cartesian/axes.js
- src/plots/cartesian/graph_interact.js
- test/image/mocks/axes_enumerated_ticks.json
- test/jasmine/tests/svg_text_utils_test.js
Remove HTML entity decoding from convertToSVG - this is unnecessary and imposes a performance hit on long strings.
> Remove HTML entity decoding from convertToSVG

- CONTRIBUTING.md
- test/jasmine/karma.ciconf.js
- test/jasmine/karma.conf.js
This PR adds additional notes on `karma-verbose-reporter`, which is definitely what I was actually looking for when I tried `config.LOG_DEBUG`—which I found verbose without adding any useful information. The comments are intended to serve as a signpost toward what, in hindsight, would have helped me locate messy test failures much faster.
> Additional notes on verbose karma reporting

- src/plot_api/plot_api.js
fixup of https://github.com/plotly/plotly.js/pull/776/commits/8f4e11e01e6a2794c5fe97802018ce74a099e0f3 merged via https://github.com/plotly/plotly.js/pull/776
> Do not log in clearPromiseQueue is _promises is empty

- src/traces/heatmap/calc.js
Fixes the isHist/Category problem without complicating the branching any further ("undefined || 0" returns 0).
> Proposed fix to Issue #782

- src/components/color/index.js
- src/components/rangeselector/attributes.js
- src/components/rangeselector/constants.js
- src/components/rangeselector/defaults.js
- src/components/rangeselector/draw.js
- test/image/mocks/range_selector_style.json
- test/jasmine/tests/color_test.js
- test/jasmine/tests/range_selector_test.js
resolves https://github.com/plotly/plotly.js/issues/790
This PR add a `rangeselector` attribute that sets the color of the active / hovered on range selector button. 
This PR also add a new `Color` method called `contrast` that is used to determine the default active color given `bgcolor`. In brief, `Color.contrast` lightens _dark_ colors and darken _light_ colors using some `tinycolor2`'s color manipulation [methods](https://github.com/bgrins/TinyColor#color-modification).
TODO:
> Configurable range selector active color

- src/lib/coerce.js
- src/plots/mapbox/layout_attributes.js
- src/plots/mapbox/mapbox.js
- test/jasmine/tests/mapbox_test.js
@chriddyp 
This PR add support for mapbox style JSON input in `layout.mapbox.style`. For example,
```js
d3.json(urlToMapboxStyleJSON, function(err, style) {
Plotly.plot(Tabs.fresh(), [{
type: 'scattermapbox',
}], {
mapbox: {
style: style
}
});
});
```
> Add support for mapbox style JSON

- src/plots/plots.js
- test/jasmine/tests/plots_test.js
The `relinkPrivateKeys` step was refactor in https://github.com/plotly/plotly.js/pull/499/commits/37e291b0439f5c5baa7df52895bdc22aa2c255d5, to accommodate transform operation they may change the side of array containers.
In doing so, it made the `Plots.supplyDefaults` step dive into all arrays present in `"data"` / `"layout"` - not just array container (e.g. annotations, images, etc as originally intended. My mistake.
> Faster relink private keys

- src/components/rangeselector/defaults.js
- src/components/updatemenus/attributes.js
- src/components/updatemenus/defaults.js
- src/lib/coerce.js
- src/plot_api/validate.js
- test/jasmine/tests/lib_test.js
- test/jasmine/tests/plotschema_test.js
- test/jasmine/tests/range_selector_test.js
- test/jasmine/tests/updatemenus_test.js
- test/jasmine/tests/validate_test.js
I noticed a few problems with `Plotly.validate` and `isLinkedToArray` attributes (which are becoming more and more numerous). Here are a few fixes.
> Fix validation logic for arrays attributes and array containers

- src/plots/mapbox/layout_defaults.js
- test/jasmine/tests/mapbox_test.js
fixes https://github.com/plotly/plotly.js/issues/818
I'm starting to really like putting `isPlainObject` checks early in the default step for `isLinkedToArray` containers. Together with adding a ref to the input index with  `_index`, we should think about generalisign this pattern to the older `isLinkedToArray` container `annoations` and `shapes`.
> Skip over non-object mapbox layer containers

- devtools/test_dashboard/devtools.js
> Plot from hash on test dashboard reload

- src/plots/cartesian/axes.js
- test/jasmine/tests/axes_test.js
Overview: Fixes autorange issues described in https://github.com/plotly/plotly.js/issues/798
Details: As suggested in https://github.com/plotly/plotly.js/issues/798#issuecomment-236605662, in the [first commit](https://github.com/tulip/plotly.js/commit/59b19991f0b9e4327f942265d627045f7a54fee0) here I've added a bunch of unit tests for [`Axes.getAutoRange`](https://github.com/plotly/plotly.js/blob/641b23172689aec28beff4cdf6460449b55ee762/src/plots/cartesian/axes.js#L133-L215) and [`Axes.expand`](https://github.com/plotly/plotly.js/blob/641b23172689aec28beff4cdf6460449b55ee762/src/plots/cartesian/axes.js#L278-L385), with what I think is reasonable behavior.  Three of the new `Axes.getAutoRange` tests fail because of the behavior described in https://github.com/plotly/plotly.js/issues/798 …
> Fix Axes.getAutoRange edge cases

- src/constants/string_mappings.js
- src/lib/html2unicode.js
- src/lib/svg_text_utils.js
- src/plots/gl2d/convert.js
- src/plots/gl2d/scene2d.js
- src/plots/gl3d/layout/convert.js
- src/plots/gl3d/layout/tick_marks.js
- test/image/mocks/axes_enumerated_ticks.json
- test/jasmine/tests/svg_text_utils_test.js
In https://github.com/plotly/plotly.js/pull/804, we dropped html entity decoding for performance reasons, but apparently some folks have been using `&amp;`, `&nbsp;`, etc in their graphs. We need to bring back support for these ASAP. 
So, I propose supporting a few entities by translating them one-by-one to unicode.
This PR also DRYs up some code by making sure that `svg_text_utils.js` (for svg text) and `html2unicode` (for WebGL text) use the same mappings.
> Decode some html entities

- src/plot_api/plot_api.js
Separate PR as it's not directly pertinent to the upcoming WebGL point cloud plot.
> use extendDeepNoArrays in plotly.restyle event emission

- src/plot_api/plot_api.js
- test/jasmine/tests/plot_api_test.js
This PR allows the following syntax:
```javascript
Plotly.restyle(gd, {'marker.color': [null, undefined]}, [0, 1]);
```
which will restore trace 0 to its default and leave trace 1 unaffected. This is necessary for the animation restyle so that property changes can be merged into a single restyle. Otherwise it's not possible to avoid modifying undesired properties.
This PR amounts to a single `continue` in the restyle loop if the `newVal` is undefined. The extra checks in the loop don't appear to be relevant for this since they don't actually use the value.
> Skip undefined props on restyle

- tasks/util/container_commands.js
Intermittent failures at the `pretest` step have more common ever since  https://github.com/plotly/plotly.js/pull/821 get merged.
This PR attempts to solve the problem by bumping the `wget` server response command from 10 to 20.
> Bump server repsonse retry limit to 20

- src/plot_api/plot_config.js
- src/plots/plots.js
- test/jasmine/tests/transforms_test.js
so that users can now set transform globally for all traces going through `Plotly.plot`.
Example: 
```js
Plotly.setPlotConfig({
globalTransforms: [{
type: 'filter',
/* */
}] 
});
// will apply a filter to all traces plotted herein
```
cc @bpostlethwaite
> Add global transforms config option

- circle.yml
- tasks/pretest.js
- tasks/run_docker.js
- tasks/setup_docker.js
We've seen a lot of intermittent test failure on CircleCI during the `npm run pretest` test ever since #821 got merged and https://github.com/plotly/plotly.js/pull/849 does not seem to help much.
So I decided to dumb down the pretest step. Instead of having one node script that does it all, this PR split the docker container tasks in two steps. These tasks are call using the shell `eval`.
cc @rreusser
> Don't use `child_process.exec` to setup docker container on CircleCI

- src/plots/gl2d/scene2d.js
General WebGL speedup (currently done for 2D plots only) that can help low-end platforms such as current MacBook and mobile platforms that have large display buffers (high resolution)
> avoid draw buffer -> display buffer copy

- src/plots/attributes.js
- src/plots/cartesian/graph_interact.js
- src/plots/gl2d/scene2d.js
- src/plots/gl3d/scene.js
- src/traces/choropleth/plot.js
- src/traces/pie/plot.js
- test/jasmine/tests/click_test.js
- test/jasmine/tests/hover_label_test.js
Add a new hoverinfo flag 'skip'. This prevents a trace from being considered for hovering or clicking. Addresses #678.
> Add hoverinfo skip

- src/components/images/draw.js
- test/image/export_test.js
... in more strict environment (then browsers).
The fix was easy. we simply add to skip over the clip-path with no corresponding `<defs>` item. The browsers don't care about that, but other environments do.
> Fix <svg> export of graphs with layout images

- src/plots/gl2d/camera.js
- src/plots/gl2d/scene2d.js
- src/traces/contourgl/convert.js
- src/traces/heatmap/calc.js
- src/traces/heatmapgl/convert.js
- src/traces/scattergl/convert.js
- test/jasmine/tests/gl2d_scatterplot_contour_test.js
- test/jasmine/tests/gl_plot_interact_test.js
fixes https://github.com/plotly/plotly.js/issues/830 and https://github.com/plotly/plotly.js/issues/545
In brief
- `heatmapgl` and `contourgl` traces rescale properly when click on the reset axes and autoscale modebar button via https://github.com/plotly/plotly.js/commit/330c5f3cd1aaccad9fa1c9607006f5891dd78c69
- toggling gl2d trace via the legend preserves the current axis range (post interactions) via https://github.com/plotly/plotly.js/commit/e0d05f6265c6ccf91d34dc2d1fde3e51abce075e
> Improve gl2d interactions

- test/jasmine/.eslintrc
- test/jasmine/tests/extend_test.js
These changes ensure that `extendDeepNoArrays` includes by reference (i.e. does NOT deep-copy) typed arrays. Initially it looked as though the [definition](https://github.com/plotly/plotly.js/blob/master/src/lib/extend.js#L13) of `isArray` needs to be changed to
```
var isArray = function(a) {
return ArrayBuffer.isView(a) || Array.isArray(a);
};
``` 
because `Array.isArray` returns `false` for typed arrays.
But it turned out that even the plain `extendDeep` already didn't deep-copy TYPED arrays. Therefore it was sufficient to add test coverage to ensure that `extendDeepNoArrays` doesn't deep-copy the typed arrays.
An additional commit locks in the current, untested `extendDeep` behavior with typed arrays. However it's contentious because maybe the reason for this `extendDeep` behavior is …
> Ensure that extendDeepNoArrays includes typed arrays by reference

- src/.eslintrc
- src/lib/index.js
- src/lib/is_array.js
- src/lib/nested_property.js
- test/jasmine/tests/is_array_test.js
Use the new Lib.isArray rather than Array.isArray.
Test cases for Lib.isArray and nested_property.
> Nested property with typed arrays

- src/plots/cartesian/ordered_categories.js
- test/jasmine/tests/calcdata_test.js
> Fix off by one error in flattenUniqueSort

- test/jasmine/tests/gl2d_scatterplot_contour_test.js
PR https://github.com/plotly/plotly.js/pull/855 added a few test cases in `gl_plot_interact_test.js` but messed up the `Plotly.register` call. This PR fixes it.
> Fix register call in gl2d test suite

- src/components/rangeselector/defaults.js
- test/jasmine/tests/range_selector_test.js
fixes bug reported on this forum [post](http://community.plot.ly/t/range-selector-on-x-axis-seems-to-break-when-using-multiple-y-axes/1904/3).
To note, overlaying axes don't get coerced domain (logic [here](https://github.com/plotly/plotly.js/blob/c837359532dac161d157eadde7277406757736d5/src/plots/cartesian/position_defaults.js#L52-L60)).
> Fix range selector position logic for overlaying axes

- src/plots/cartesian/dragbox.js
I forget about that module during PRs https://github.com/plotly/plotly.js/pull/833 and https://github.com/plotly/plotly.js/pull/845
cc @rreusser
> Fixup cartesian dragbox module

- dist/extras/request_animation_frame.js
- src/components/rangeslider/create_slider.js
- tasks/stats.js
This PR adds a proper RAF polyfill based on [this discussion](https://gist.github.com/paulirish/1579671) and [the resulting repo](https://github.com/darius/requestAnimationFrame/blob/master/requestAnimationFrame.js). I debated whether to make this `Lib.requestAnimationFrame` and `Lib.cancelAnimationFrame` or not. The only downside of this approach is that it would *fix* libraries using `requestAnimationFrame` without a polyfill.
As part of this, remove the logic from: https://github.com/plotly/plotly.js/blob/f07a274fe7c215c06d3827f2a589f17421f72ce1/src/components/rangeslider/create_slider.js#L225-L233
> Add a requestAnimationFrame polyfill

- src/plot_api/plot_api.js
As discussed, this replaces a warning + early return on invalid gd with throwing an error. Related to but **does not** address the fact that `Lib.isPlotDiv(Plotly.purge(gd)) === true` if `gd` was ever a plot.
> Throw an error when redraw called on invalid gd

- src/plots/mapbox/mapbox.js
- test/jasmine/tests/mapbox_test.js
Passing in `scattermapbox` trace with `visible: false` to `Plotly.plot` resulted in plot code exceptions (updates with `visible: false` worked and work fine).
> Fix mapbox visible false first draw

- lib/index-gl2d.js
- lib/index.js
- lib/pointcloud.js
- package.json
- src/.eslintrc
- src/lib/float32_truncate.js
- src/traces/pointcloud/attributes.js
- src/traces/pointcloud/convert.js
- src/traces/pointcloud/defaults.js
- src/traces/pointcloud/index.js
- src/traces/scattergl/convert.js
- test/image/mocks/gl2d_pointcloud-basic.json
- test/jasmine/karma.ciconf.js
- test/jasmine/tests/gl2d_pointcloud_test.js
This PR contains the plotly.js part of the new `pointcloud2d` trace type.
Work left involves
> Adding pointcloud

- src/components/legend/draw.js
- src/traces/bar/arrays_to_calcdata.js
- test/jasmine/tests/legend_test.js
fixes https://github.com/plotly/plotly.js/issues/893
In some update scenarios, the trace toggle background `<rect>` nodes - which trigger the legend click handlers - did not get their `x` and `y` attributes set. This leads to ambiguously defined `<rec>` and buggy behavior on mouse interactions.
Note also, this PR fixes a newly-discoveed bug in the array-to-calcdata step for bars. This bug was discovered while writing the test case.
> Fix legend trace toggle background on restyles

- src/plot_api/plot_config.js
- src/plots/mapbox/index.js
- test/jasmine/tests/mapbox_test.js
This PR makes sure that plotly.js does not attempt to reach the mapbox public server when users are connected to a Mapbox Atlas server.
> Special mapboxAccessToken case for Atlas users

- src/plots/cartesian/index.js
- src/plots/plots.js
- test/jasmine/tests/cartesian_test.js
Setting **all** scatter traces to `visible: false` on a given graph at once (e.g. by `Plotly.restyle(gd, 'visible', false);` is currently broken in `master` and `v1.17.0` ever since commit https://github.com/plotly/plotly.js/commit/57892edf00c497a447b3e9e32847c6e7d08dd5ac of PR #802. By broken, I meant the `visible: false` traces remain visible on the graph after the update.
As of https://github.com/plotly/plotly.js/commit/57892edf00c497a447b3e9e32847c6e7d08dd5ac, scatter traces aren't purged in the cartesian subplot plot step (see [here](https://github.com/plotly/plotly.js/blob/ab51c36edeb629ab73bdc542cdb89d430491c71e/src/plots/cartesian/index.js#L88)), meaning that the `Scatter` trace module takes the responsibility of cleaning up `visible: false` traces - which works fine **except** …
> Hotfix: clean up visible false scatter trace

- src/plot_api/plot_api.js
- test/jasmine/tests/legend_test.js
- test/jasmine/tests/updatemenus_test.js
Both legend and updatemenus `bgcolor` are defaulted to the `layout.paper_bgcolor` value. Previously, relayout calls that included `paper_bgcolor` bypassed component updates, but in general, we can't do so in order to correctly update the legend and updatemenu `bgcolor`.
> make paper bgcolor relayout update legend and updatemenu accordingly

- src/traces/scatter/calc.js
- src/traces/scatterternary/calc.js
The code was comparing the result of `typeof` with a variable named `undefined`.
As typeof returns a string it should compare to `'undefined'`
> Correct check for undefined variable

- src/lib/events.js
- test/jasmine/tests/events_test.js
- test/jasmine/tests/plots_test.js
**Problem**: Currently it is the responsibility of the item triggering an event to iterate over all controls and update them. This seems like a rather unmaintainable and tightly coupled pattern.
**Solution**: This PR creates a second event handler which receives a copy of all events emitted on the the regular event handler. It does this so that internal parts of plotly can respond to events without adding events onto the user-facing event handler—which would otherwise break plotly if the user ever executed `plotObj.removeAllListeners()`. 
Note that it mirrors the events so that it's not necessary to *emit* two copies of every event.
This could otherwise be achieved with a flag that differentiates internal vs external event handlers (so that `removeAllListeners` would not break things), …
> Mirror events on an internal event handler

- src/plot_api/plot_api.js
- test/jasmine/tests/plot_api_test.js
fixes https://github.com/plotly/plotly.js/issues/942
... which turned out to be an easy fix. All we had to do was to make `Plotly.redraw` go through the `cleanData` to make sure the newly (if any) added traces have a `uid` field - which is now used in the key function in the scatter plot method since @rreusser 's animation PR #802
> Clean data & layout on Plotly.redraw

- src/plots/gl2d/scene2d.js
resolves https://github.com/plotly/plotly.js/issues/744
Off this branch, double-clicking on the canvas now no longer puts the select-box in a weird state.
This solution was discovered by @dfcreative , I made a PR here to potential make this fix part of the `1.17.3` patch release.
> Sanitise gl2d double-click interactions

- src/components/drawing/index.js
- src/traces/scatter/plot.js
- test/jasmine/tests/cartesian_test.js
fixes https://github.com/plotly/plotly.js/issues/952
but also I noticed that `Plotly.restyle(gd, 'mode', '')` is broken on `master` for scatter traces (since PR https://github.com/plotly/plotly.js/pull/802). I think I got all the cases fixed on this branch.
@rreusser
> Multiple scatter plot fixes

- .eslintrc
- .gitignore
- devtools/.eslintrc
- lib/.eslintrc
- lib/bar.js
- lib/box.js
- lib/choropleth.js
- lib/contour.js
- lib/contourgl.js
- lib/core.js
- lib/heatmap.js
- lib/heatmapgl.js
- lib/histogram.js
- lib/histogram2d.js
- lib/histogram2dcontour.js
- lib/mesh3d.js
- lib/pie.js
- lib/pointcloud.js
- lib/scatter.js
- lib/scatter3d.js
- lib/scattergeo.js
- lib/scattergl.js
- lib/scattermapbox.js
- lib/scatterternary.js
- lib/surface.js
- src/.eslintrc
- test/jasmine/.eslintrc
This PR:
- defines one set of globals in the root `.eslintrc` for simplicity
- enforce `src/` linting rules in `lib/` (e.g. if ever we add `console.log` in `lib/<trace>.js`)
> Fixing a few maintenance issues

- package.json
- test/image/assets/get_image_request_options.js
- test/image/export_test.js
I had a few commits on a local branch that added [`image-size`](https://www.npmjs.com/package/image-size) to our `npm run test-export` routine to test the SVG more robustly check the generated image size (instead of simply looking for a minimum file size) after PR https://github.com/plotly/plotly.js/pull/604
Better late than never.
> Test SVG image size in test-export

- src/plot_api/plot_api.js
- test/jasmine/tests/plot_api_test.js
fixes `Plotly.update` issue discovered here http://codepen.io/veraz/pen/wzgjpJ
> Fix Plotly.update for full data + layout replot

- src/components/updatemenus/attributes.js
- test/jasmine/tests/updatemenus_test.js
when `Plotly.update` was added in https://github.com/plotly/plotly.js/pull/875 , I forgot to add `'update'` to the list of available updatemenu button methods.
This PR adds it in.
> Plotly.update in update menus

- lib/filter.js
making `eslint .` pass again on `master`
cherry-picked https://github.com/plotly/plotly.js/pull/978/commits/6309837f46ddca9369d9d5624a9d7e1918899dcf from https://github.com/plotly/plotly.js/pull/978
> Fix linting in lib/filter.js

- src/plots/attributes.js
Add max and default vals for `maxpoint` attribute for streams
so the values shown [here](https://github.com/plotly/streambed/blob/f95f3303b3600451902efa6d86bada58b9f727ee/shelly/streaming/streamingviews.py#L97) make it into the reference pages
> add streaming maxpoints max and dflt

- src/plots/gl2d/scene2d.js
- src/traces/contourgl/convert.js
- src/traces/heatmapgl/convert.js
- src/traces/pointcloud/convert.js
- src/traces/scattergl/convert.js
- test/jasmine/assets/hover.js
- test/jasmine/assets/timed_click.js
- test/jasmine/tests/gl2d_click_test.js
Covers `plotly_hover`, `plotly_unhover`, `plotly_click`.
https://github.com/plotly/plotly.js/issues/743
Also: FI-71
Partial coverage: https://github.com/plotly/plotly.js/issues/130
> Hover / unhover events on the 2d WebGL plots

- src/components/drawing/index.js
- src/traces/scatter/plot.js
cc @etpinard @cpsievert 
This PR refactors text mode scatter just slightly to properly duck-type the node being translated as a transition. The text node itself remains an instantaneous update.
> Adjust d3 update to enable text mode animation

- src/plot_api/plot_api.js
- test/jasmine/tests/frame_api_test.js
This PR makes passing either `null` or `undefined` to `Plotly.addFrames` a no-op. I didn't initially expect this would be a meaningful case, but this allows *all* plots to simply call 
```javascript
Plotly.plot(gd, x.data, x.layout, x.config).then(function () {
return Plotly.addFrames(gd, x.frames))
});
```
without worrying about whether addFrames *needs* to be called. Ideally in v2.0 frames will be part of the initial `plot` call, but until then, at least you can call addFrames and let the method sort out whether it's a no-op or not.
> Make null/undefined a noop for addFrames

- src/components/sliders/attributes.js
This is a trivial PR that fixes poorly chosen defaults for sliders. It should look *nice* by default, not by configuration. This PR sets:
```javascript
{
x: 0,
y: 0,
xanchor: 'left',
yanchor: 'top',
pad: {t: 20}
}
```
In many cases, this will hopefully just make it unnecessary to do much with the appearance. The result for an otherwise unstyled slider now looks like:
> Fix badly chosen default positioning for sliders

- src/lib/svg_text_utils.js
- src/snapshot/tosvg.js
- test/jasmine/tests/snapshot_test.js
See #984 
The goal of this PR is to get circle-ci to see what happens if the visibility default on text is `visibility: inherit` instead of `visibility: visible`. `visible` hard-codes it and is difficult to override. I had an ominous feeling about this change leading to a rabbit hole of related fixes and compensations, but let's see what happens…
> Try out visibility:inherit default for text

- tasks/pretest.js
`master` is currently broken, but rest assured, there's nothing wrong with `v1.18.0` itself (yet).
In brief,
The `npm run pretest` builds a fixture to test `plotly.min.js` in a Require.js environment in this [suite](https://github.com/plotly/plotly.js/blob/master/test/jasmine/bundle_tests/requirejs_test.js).
To do so, in `master`, `pretest.js` uses a string replace to place the bundle code in a Require.js define statement. This string replace currently breaks the fixture and thus making the Require.js test fail.
In this PR, the Require.js test fixture is built using a more robust arrary `join('')`.
> Fix pretest task for require.js test fixture

- package.json
- src/plots/gl2d/scene2d.js
- src/plots/gl3d/scene.js
- test/jasmine/assets/has_webgl_support.js
Replace every entry of `canvas.getContext('webgl')` with more reliable context getter [webgl-context](https://github.com/mattdesl/webgl-context) (it handles errors and returns null if no context available).
May be related to the karma cases where context is unavailable.
> Use package to obtain webgl context

- dist/extras/request_animation_frame.js
After looking at the requestAnimationFrame polyfill I noticed that it would be leaking global vars as it's not wrapped in an IIFE. As the closure will be around for the life of the page, I have also nulled out the temporary vars.
> Fix leak of global vars in polyfill

- test/image/README.md
Added to the first line of the image test instructions:
> Test plotly.js with Plotly's image testing docker container. Before starting, don't forget to [set up your testing environment with `npm run pretest`](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md#development).
I could make this Step 0. Or Step 1. Or Step 1.5. Glad to amend, but I think it's worth mentioning on this page since the tests don't work without it. Wasn't _strictly_ sure where in the sequence it had to go.
> Add note directing to pretest

- package.json
- test/jasmine/assets/custom_matchers.js
- test/jasmine/tests/lib_test.js
This test adds a helper function to the lib test in order to loosen the comparison to what we actually care about, which is array **access**, not array **content**.
Gross.
> Fix expect(new Array(1)).toEqual([undefined]) failures on *some* platforms

- src/traces/ohlc/transform.js
- test/jasmine/tests/finance_test.js
small fix following https://github.com/plotly/plotly.js/pull/1020
> Pass 'name' in hoverinfo for OHLC generated traces

- src/plot_api/plot_api.js
- src/plots/plots.js
- test/jasmine/tests/hover_label_test.js
- test/jasmine/tests/plots_test.js
fixes https://github.com/plotly/plotly.js/issues/1044
and fixes relayout problems discovered in http://community.plot.ly/t/resizing-is-not-working-after-setting-height-in-plotly-relayout/2196/6?u=etienne
These problems were introduced in https://github.com/plotly/plotly.js/pull/946
This PR will need to merge `master` after https://github.com/plotly/plotly.js/pull/1048 to :white_check_mark:
> Cartesian subplot fixes

- src/plot_api/plot_api.js
- test/jasmine/tests/plot_api_test.js
This PR overloads `Plotly.plot` so that loading frames isn't a second, promise-chained step.
```javascript
Plotly.plot(gd, data, layout, config)
```
```javascript
Plotly.plot(gd, {
data: [...]
layout: {...}
config: {...}
frames: [...]
});
```
```javascript
Plotly.plot(gd, data, layout, config).then(function () {
return Plotly.addFrames(gd, frames);
});
```
> Modify Plotly.plot to accept frames #1014

- src/plots/cartesian/axis_autotype.js
- src/plots/cartesian/axis_defaults.js
- src/traces/scattergl/convert.js
- test/jasmine/tests/axes_test.js
- test/jasmine/tests/gl2d_date_axis_render_test.js
Performance improvement - it avoids the slower fancy `scattergl` that used to be triggered by the presence of the `Date` X axis type.
Fixes issue https://github.com/plotly/plotly.js/issues/413
> Non-fancy scattergl to work with dates

- src/plots/plots.js
- test/jasmine/tests/plots_test.js
... so that `gd._fullData[i]._fullInput` and `gd._fullData[i]._expandedTrace` are **always** defined, that is, inside transform traces and non-transforms traces.
This, I believe, will make @VeraZab's live a lot easier for building UI buttons for `ohlc` and `candlestick` traces.
@bpostlethwaite can you think of a potential problem here?
> Add identity _fullInput refs to fullTrace

- src/components/images/draw.js
- src/plots/plots.js
- test/jasmine/tests/transition_test.js
This PR does two things:
1. a couple one-line tweaks were needed to get layouts to use the new `extendLayout` function from #1041 
2. transitions with `redraw: true` weren't getting redrawn between frames due to a race condition between frame duration and transition duration. If you specify `redraw: true`, the whole plot now *definitely* gets redrawn between frames.
Here are animated annotations. Note that they take effect at the *end* of the transition since smooth annotation transitions are not yet implemented. Also, two-way component binding is *not* merged into this branch but will work once #1016 is merged.
> Layout animations for container array'd objects

- src/plots/plots.js
- test/jasmine/tests/finance_test.js
fixes https://github.com/plotly/plotly.js/issues/1068
> Use trace gd.data index to determine dflt trace name

- src/plot_api/helpers.js
- src/plot_api/plot_api.js
- src/plots/plots.js
- test/jasmine/tests/annotations_test.js
- test/jasmine/tests/layout_images_test.js
- test/jasmine/tests/lib_test.js
- test/jasmine/tests/mapbox_test.js
- test/jasmine/tests/shapes_test.js
- test/jasmine/tests/sliders_test.js
- test/jasmine/tests/transform_multi_test.js
- test/jasmine/tests/updatemenus_test.js
fixes https://github.com/plotly/plotly.js/issues/1069
Currently, `relayout` is allowed to be called with :diamond_shape_with_a_dot_inside: special :diamond_shape_with_a_dot_inside: `'add'` and `'remove'` values for annotations and shapes. For example, 
```js
Plotly.relayout(gd, 'annotations', 'add');
// => adds a blank annotations
Plotly.relayout(gd, 'annotations[2]', 'remove');
// => remove the 3rd annotation
```
which gets the job done, but is a little sloppy. We can do better and luckily `'add'` and `'remove'` we're never implemented for the new (e.g. images, updatemenus, sliders, mapbox layers) layout array containers.
This PR enforces,
```js
Plotly.relayout(gd, `${containerName}[${itemIndex}]`, null);
```
as a way to delete items in containers found in layout. Similarly, 
```js …
```
> Consistent container update / removal 

- src/plot_api/plot_api.js
- src/plots/animation_attributes.js
- src/plots/plots.js
- test/jasmine/tests/animate_test.js
This PR adds two animation options:
- `fromcurrent: true | false`: Seems obvious. Uses the `gd._fullLayout._currentFrame` which is the de facto internal reference to the mostly recently animated named frame, if applicable.
- `direction: 'forward' | 'reverse'`: Seems obvious.
Together, these add a bit more capability to play buttons. Not strictly called for, but there's no way this won't get asked for. Wohooo.
> Animation direction and fromcurrent

- src/plot_api/plot_api.js
- test/jasmine/tests/animate_test.js
This change expands on the current bad div message:
> `This element is not a Plotly plot: [object HTMLDivElement].`
with more info:
> `This element is not a Plotly plot: [object HTMLDivElement]. It's likely that you've failed to create a plot before animating it. For more details, see https://plot.ly/javascript/animations/`
Which people who are used to other libraries will probably run into very quickly. See: http://stackoverflow.com/questions/39415791/using-plotly-js-animation-feature/39457872#39457872
> For anyone else's reference it appears that you can't initialize animate on an empty plot and have it animate with the function. It's only intended to change data that already exists
> Add a nice error message when people animate before plotting

- tasks/bundle.js
- tasks/cibundle.js
- tasks/util/browserify_wrapper.js
- tasks/util/patch_minified.js
The ugly `webworkify` + Require.js bug strikes again :ghost: The `1.19.0` dist builds are broken in Require.js. In https://github.com/plotly/plotly.js/pull/914 (more specifically https://github.com/plotly/plotly.js/pull/914#r77898939) I chose to run the plotly.min.js + require.js test only on the main dist bundle because minifying plotly.js takes about 1 minute. That is, it was testing new code only on release builds (like this [one](https://circleci.com/gh/plotly/plotly.js/2887)).
BUT, I should add: _minifying plotly.js take about 1 minute_, that's using node.js v4. Using node.js v6, the minifying time drops to about ~30 seconds. Good enough for me. Let's test this thing on every build!
> Fix minified dist bundles

- package.json
- tasks/stats.js
The most recent minor version bump (`v1.19.0`) featured many dependency bumps. To make sure that I had the correct `node_modules` tree I ran [`npm ls`](https://docs.npmjs.com/cli/ls). That's when I realised that `npm ls` completes with exit code `1` whenever unmet dependencies are present in the local `node_module`. So, why not use this as a preversion check? That way we'll enforce whoever bumps the version to have the correct `node_modules` tree. 
Moreover, I'm thinking that we should log the `node_modules` tree structure in `dist/` whenever for produce new dist bundles. That way troubleshooting possible `master` and `dist` bundle mismatch should be a lot easier. This is especially important with the recent and planned short-term gl2d development where a lot of gl-vis module were …
> Add npm ls check and dist log file

- src/components/annotations/annotation_defaults.js
- src/components/annotations/attributes.js
- src/components/annotations/calc_autorange.js
- src/components/annotations/draw.js
- src/components/images/attributes.js
- src/components/images/defaults.js
- src/components/images/draw.js
- src/components/shapes/attributes.js
- src/components/shapes/calc_autorange.js
- src/components/shapes/draw.js
- src/components/shapes/shape_defaults.js
- src/lib/filter_visible.js
- src/lib/index.js
- src/plot_api/plot_api.js
- src/plots/ternary/ternary.js
- test/image/mocks/annotations-autorange.json
- test/image/mocks/annotations.json
- test/image/mocks/layout_image.json
- test/image/mocks/shapes_below_traces.json
- test/jasmine/tests/annotations_test.js
- test/jasmine/tests/layout_images_test.js
- test/jasmine/tests/shapes_test.js
that is `annotations`, `shapes` and `images` items should get a `visible` attribute just like `updatemenus` and `slider` already have.
This should make setting mobile-friendly annotations-less frames much easier. Related: https://github.com/plotly/plotly.js/pull/1081#issuecomment-258264888 
cc @rreusser  @alexcjohnson
> Add `visible` attribute to layout container items.

- src/transforms/filter.js
- test/jasmine/tests/transform_filter_test.js
fixes https://github.com/plotly/plotly.js/issues/1119
@bpostlethwaite
> Fix filter transform for categorical targets

- src/plots/plots.js
- test/jasmine/tests/transform_filter_test.js
- test/jasmine/tests/transform_multi_test.js
a requirement for https://github.com/plotly/plotly.js/pull/1099
cc @rreusser
> Allow transform to have supply layout defaults handler

- src/plot_api/plot_api.js
- src/plots/plots.js
- test/jasmine/tests/animate_test.js
- test/jasmine/tests/frame_api_test.js
Frame names were successfully cast to strings, but *requested* frames via `Plotly.animate` were not. This PR fixes it and adds some tests. It also adds one small fail-safe against callbacks that execute after a plot has been purged.
See: #1035
> Enforce casting requested frame names to strings

- src/plot_api/plot_api.js
- test/jasmine/tests/plot_api_test.js
@bpostlethwaite @etpinard 
@etpinard 's fix https://github.com/plotly/streambed/pull/8378/commits/6a74d87370ef2205cdd4a86eb8c4ab4a1332ecd0 will handle your exact case, but a more general cover for this issue (until we redo this whole mess of code!) is just to make the tests of `p.parts` not fail on integer parts.
```
Plotly.relayout(gd, {rando: [1, 2, 3]})
Plotly.relayout(gd, {'rando[1]': 45})
gd.layout.rando
[1, 45, 3]
```
> quick fix - allow relayout array elements

- src/plots/plots.js
- test/jasmine/tests/animate_test.js
This PR adds a previously-failing test and corresponding bug-fix for animating bar graphs. Since it was not previously tested, a regression snuck in in the logic that skips non-animatable traces. The updates aren't pretty, but at least now modules that have `module.animatable !== true` will update.
> Fix broken non-animatable transition fallback

- src/traces/scatter/plot.js
- test/jasmine/tests/animate_test.js
This PR adds first a failing test for scatter opacity animation and then a fix. Wasn't so much a bug as just a simple omission.
See #1130
> Animate scatter trace opacity

- package.json
- test/jasmine/tests/gl2d_click_test.js
Testing with fix in `gl-vis`.  Fixes https://github.com/plotly/plotly.js/issues/1145
> Fixing the pickOffset bug in non-fancy gl-scatter2d

- circle.yml
- package.json
- src/lib/topojson_utils.js
- src/plots/geo/geo.js
The `topojson` module got split in a geojson to topojson and topojson to geojson version. The latter is what we do in plotly.js.
This PR replaces the `topojson` dependency with [`topojson-client`](https://github.com/topojson/topojson-client). The API hasn't changed, so the change was easy enough. This should lead to a smaller bundle size.
> Use topojson-client

- src/traces/pie/attributes.js
One of the plotcon speakers called out [this image](https://blog.socialcops.com/wp-content/uploads/2015/11/5.png) where Apple's 20% looks pretty much as big as Blackberry's 40% - lets agree not to go there.
@etpinard
> remove commented out code about 3d pie chart attributes

- src/traces/bar/hover.js
> Fix hover label in stacked bars

- dist/README.md
- tasks/stats.js
typo fixup in `dist/README.md`
> tasks: fixup main bundle URLs

- .eslintrc
- src/plot_api/plot_api.js
- test/jasmine/tests/plot_api_test.js
fixes https://github.com/plotly/plotly.js/issues/1083
and replaces @dfcreative 's https://github.com/plotly/plotly.js/pull/1136
> Flat extend input traces on addTraces

- src/plots/command.js
- test/jasmine/tests/command_test.js
- test/jasmine/tests/updatemenus_test.js
A simple fix for #1169. The fix is more straightforward than the test, which I'm adding now.
> Add check for failed binding comparison

- src/lib/clean_number.js
- test/jasmine/tests/lib_test.js
fixes #1183
An alternate take on #1184
> fix regression in lib/clean_number (alternate)

- src/traces/histogram/calc.js
- src/traces/histogram2d/calc.js
- test/jasmine/tests/histogram2d_test.js
- test/jasmine/tests/histogram_test.js
fixes https://github.com/plotly/streambed/issues/8512 - date histograms with small bins failed. Turns out it was any uniform date bins, ie intervals smaller than 1 month, that were broken.
Note that there are still some issues including and relating to #1151 uncovered in the course of this fix, some TODOs added describing these.
At its root, the issue is that `Lib.findBin` doesn't know anything about the axis it's binning onto, so needs bins specified entirely by numbers, either `{start, end, size}` or `[edge0, edge1, edge2, ... edgeN]`, but in the new date system, `start` and `end` are date strings. For performance it's important that these be turned into numbers only once, so rather than hack date conversion into `findBin` we convert the bins object everywhere it gets called.
In …
> Fix date histograms

- src/plots/cartesian/axes.js
- src/plots/cartesian/set_convert.js
- test/jasmine/tests/axes_test.js
Fixes #738 as well as a bunch of other odd edge cases around tickvals with or without ticktext on all axis types.
@etpinard
> tickvals / ticktext edge cases

- src/components/drawing/index.js
- test/jasmine/tests/drawing_test.js
- test/jasmine/tests/plot_interact_test.js
fixes https://github.com/plotly/plotly.js/issues/558 (hopefully :smile:)
See https://github.com/plotly/plotly.js/issues/558#issuecomment-262853476 for rationale.
> add id to location href w/o hashes when setting clip paths urls

- src/plots/mapbox/mapbox.js
- src/traces/heatmapgl/attributes.js
- test/jasmine/karma.ciconf.js
- test/jasmine/karma.conf.js
- test/jasmine/tests/download_test.js
- test/jasmine/tests/hover_label_test.js
- test/jasmine/tests/mapbox_test.js
- test/jasmine/tests/updatemenus_test.js
resolves https://github.com/plotly/plotly.js/issues/666 (hopefully)
How good does this
feel?
cc @rreusser @n-riesco @alexcjohnson @monfera
> Make citest-jasmine pass locally

- src/components/calendars/calendars.js
- src/components/calendars/index.js
.. so that the resulting main plotly.js bundle weighs in at:
compared to `567 kB` in https://github.com/plotly/plotly.js/pull/1230
> use only the calendars we need from 'world-calendars'

- src/plot_api/plot_api.js
- src/plots/command.js
- src/plots/plots.js
- test/jasmine/tests/animate_test.js
- test/jasmine/tests/command_test.js
- test/jasmine/tests/frame_api_test.js
This PR adds some casting and fixes some checks to ensure that frames with number names are handled correctly. Technically it could break compatibility with current plots, but only in the sense that the current behavior is broken. This seems like an extremely common problem based on what I've observed.
> Fix number named frames

- src/components/sliders/draw.js
- src/plots/plots.js
- test/jasmine/tests/sliders_test.js
cc @bpostlethwaite @etpinard 
This PR fixes two cases:
1. When slider options are added, it needs to *refetch* the slider steps from the d3 data. The mouse events are in a closure, so it was previously using outdated data in callbacks.
1. When slider options are removed, it checks whether the active index is invalid. If it is, it just moves the slider to the first position.
This PR does not fix:
- It does not search for a matching option after the update has occurred. Like if you remove the thid option, it will not fix the active index from 5 -> 4. That can be added, but I did not yet address that case in the interest of stopping blocking @bpostlethwaite ASAP.
This PR also sneaks in `Plot.recomputeFrameHash(gd)` which does what it says. I should add tests for that; it's just a small bonus …
> Add fallbacks for manual manipulation of slider/frames

- package.json
as discussed privately with @alexcjohnson , the auto `git push && git push --tags` postversion hook is probably too magical. Adding one step to our publishing tasks will allow us to inspect `dist/` bundles and `dist/npm-ls.json` before pushing to the origin.
For example,  the failed `v1.19.0` could have been avoided if this hook wasn't present.
TODO:
> don't auto-run `git push && git push --tags` on version

- src/components/calendars/index.js
- src/plot_api/helpers.js
- src/transforms/filter.js
- test/image/mocks/world-cals.json
- test/jasmine/tests/plot_api_test.js
- test/jasmine/tests/plotschema_test.js
- test/jasmine/tests/transform_filter_test.js
Changes filter attribute `calendar` to `valuecalendar` and adds a new one `targetcalendar` to use if an array is provided as `target`. If `target` is a string (ie referring to an attribute in the same trace) it will ignore `targetcalendar` and instead use the calendar for that attribute (so `xcalendar` if target is `'x'`) which is what it was doing previously.
<strike>Note that this is a BREAKING change (`calendar` if supplied is not coerced into `valuecalendar`) but only breaking what's been in master for the last 6 days since merging #1220 </strike>
@VeraZab @cldougl @chriddyp @etpinard
> filters use valuecalendar and targetcalendar instead of calendar

- src/plot_api/plot_api.js
- test/jasmine/tests/frame_api_test.js
cc: @bpostlethwaite 
I've added the capability to ignore null frames in `addFrames`. I *think* it's good, but honestly I find the index-based addFrames a bit fragile and undesirable in the first place, so I hate to push 'fixes' through too quickly. All it does is continue to the next frame if the input is null.
> Add frames accept null

- src/plots/plots.js
- test/jasmine/tests/plots_test.js
@rreusser @alexcjohnson 
`Plots.graphJson` is called in the [`Plots.sendDataToCloud`](https://github.com/plotly/plotly.js/blob/7e9fc1d37cbfaa6c7371121f57a1c330b0bec52f/src/plots/plots.js#L317) to serialize the graph data. 
Now, this routine also serializes `frames`.
> make Plots.graphJson serialize frames too

- src/plot_api/subroutines.js
- src/traces/bar/arrays_to_calcdata.js
- src/traces/bar/calc.js
- src/traces/bar/plot.js
- src/traces/scatter/arrays_to_calcdata.js
- src/traces/scatter/calc.js
- src/traces/scatter/plot.js
- src/traces/scatter3d/calc.js
- src/traces/scatterternary/calc.js
- test/jasmine/tests/transform_filter_test.js
This PR makes calc-transforms behave as desired on relayout (e.g. zoom).
Moreover, it should also be a perf boost as trace array to calcdata is now called only in the calc as opposed to the plot step (which is called more often e.g. on zoom).
Now, this PR moved around some pretty ancient code. I'm a little afraid about possible regressions. I'm not 100% confident in our test suite for the various `restyle` call that depend on `arraysToCalcdata`, I'll dig into our test suites to verify.
> Convert arrayOk attribute to calcdata in calc step

- src/plots/plots.js
- test/jasmine/tests/transform_filter_test.js
To fix the bug, we need to _clear_ the `ax._min` and `_ax._max` arrays (generated in `Axes.expand` done in the `_module.calc` call before the `calcTransform` loop) before the _final_ `module.calc` call.
To do so in the least _intrusive_ way possible, this PR splits `Plots.doCalcdata` operations into separate loops - which hopefully will also help readability.
> Ensure axis autorange is computed after transform operations

- src/lib/coerce.js
- src/traces/contour/attributes.js
- src/traces/contour/calc.js
- src/traces/contour/defaults.js
- src/traces/contour/plot.js
- test/jasmine/tests/contour_test.js
- test/jasmine/tests/lib_test.js
Fixes #591 and a bunch of other edge cases for contour plots related to `autocontour` and / or partial or self-contradictory specification of contour levels.
> Contour bg fix

- src/traces/scattergeo/hover.js
- src/traces/scattermapbox/hover.js
- test/jasmine/tests/geo_test.js
- test/jasmine/tests/scattermapbox_test.js
fixes https://github.com/plotly/plotly.js/issues/1278
I opted for a strategy similar to what's currently done in [`Drawing.textPointStyle`](https://github.com/plotly/plotly.js/blob/1ef50b91e97e3bfc53a856329649c858e7f0d9ec/src/components/drawing/index.js#L319-L321) to handle all valid `text` input combinations.
cc @alexcjohnson @chriddyp
> Fix scattermapbox and scattergeo handling of '' text items

- package.json
... so that users on `v1.21.x` can see 3D hover labels after a fresh `npm i`.
This PR **does not fix** https://github.com/plotly/plotly.js/issues/1268. Making 3D hover labels work with `mouse-change@^1.4.0` will require a patch that I don't want to make on a patch release.
> Lock mouse-change@1.3.0

- src/plots/cartesian/axes.js
- test/jasmine/tests/axes_test.js
so that trying to plot a histogram with categorical sample pts on a linear axis result in blank plot instead of `ax.dtick` exception.
For example,
```js
Plotly.plot('graph', [{
type: 'histogram',
x: ['orange', 'apple']
}], {
xaxis: {
type: 'linear'
}
}
```
currently lead to:
with this patch, the above snippet generates a blank graph.
> add fallback in autobin routine

- src/plot_api/plot_schema.js
- src/plots/frame_attributes.js
- test/jasmine/tests/plotschema_test.js
as described in https://github.com/plotly/plotly.py/pull/656#issuecomment-271754882 by @theengineear
> Frames plotschema for plotly.py v2

- src/plots/geo/geo.js
- src/plots/geo/index.js
- src/plots/mapbox/index.js
- src/plots/plots.js
- src/plots/ternary/index.js
- src/plots/ternary/ternary.js
- src/traces/scatterternary/plot.js
- test/jasmine/tests/plots_test.js
Cartesian, geo and ternary subplots (i.e. all SVG/d3 subplots) draw traces using the trace modules' `plot` method which expects as input the `calcdata` traces corresponding to all traces of a given trace type on a given subplot.
Previously, geo and ternary subplot used similar but not-exactly-equivalent logic to handle add/remove/modify updates. This PR - mainly by making ternary subplot use `gd.calcdata` instead of `gd._fullData` traces - unifies the geo and ternary logic into `Plots.generalUpdatePerTraceModule` (I hope you like the name). Cartesian subplots on the other hand are (still) in a world of their own - unifying all SVG/d3 subplots will have to wait.
By doing so, this PR also fixes a bug where:
```js
Plotly.plot('graph', [{
type: 'scattergeo',   // or 'scatterternary'
visible: …
```
> Combine geo and ternary genaral update pattern

- src/plot_api/plot_api.js
- test/jasmine/tests/updatemenus_test.js
as pointed out by @jackparmer in https://plot.ly/~jackp/17246.embed
When a graph has both updatemenus and sliders, updatemenu buttons drop below sliders.
> Draw updatemenus over sliders

- package.json
- src/plots/gl3d/scene.js
fixes https://github.com/plotly/plotly.js/issues/1268
... and makes 3D hover labels compatible with it.
> bump mouse-change dep to ^1.4.0

- src/components/rangeslider/draw.js
- test/image/export_test.js
Range slider svg / eps / pdf exports are currently failing on plot.ly. 
This PR ensures that
- all range slider `<rect>` elements have set x/y/width/height attributes (no setting those makes the SVG invalid)
- RGBA color are set via `fill` + `fill-opacity` attributes (Batik doesn't like `fill: ${rgba}`)
- all `fill: 'transparent` elements are not drawn on static plots (Batik doesn't like `fill: 'transparent'`)
> Fix range slider svg / eps / pdf exports

- src/lib/notifier.js
- src/lib/svg_text_utils.js
- src/plots/cartesian/graph_interact.js
- test/jasmine/tests/hover_label_test.js
Report:
- make a scatter plot with at least two traces
- edit the name of one of the traces (in the legend) to: <img src=x onerror=console.log('hi')>
- hover over any point in the trace with the bad name, the console.log will execute.
- for bonus points, hide that trace name from the legend, and make that trace look like it's part of (or all of!) another trace - the user will see nothing.
> Fix XSS in trace name on hover

- src/components/rangeslider/defaults.js
- src/plots/cartesian/axis_defaults.js
- src/plots/cartesian/layout_defaults.js
- src/plots/gl3d/layout/axis_attributes.js
- test/jasmine/tests/range_slider_test.js
This should make a bunch of folks on https://community.plot.ly/ happy.
Ever since https://github.com/plotly/plotly.js/pull/1017, there's no reason to hard set `fixedrange: true` for all y-axes anchored to a x-axis that has a range slider: the range plot draw [step](https://github.com/plotly/plotly.js/blob/b823573efb1cd910b6f9406502690f4de0c94f6c/src/components/rangeslider/draw.js#L315-L382) can handle y-axis interactions.
To preserve backward compatibility, we must however make sure that y axes anchored to a x-axis with a range slider default to `fixedrange: true`. With this PR, users can now _set back_ `layout.yaxis.fixedrange: false` if they prefer having interactive y-axes along with their range slider plots.
> Honor `fixedrange: false` in y-axes anchored to xaxis with range slider

- src/traces/scattergl/convert.js
- test/image/mocks/gl2d_scatter-marker-line-colorscales.json
- test/jasmine/tests/gl_plot_interact_test.js
fixes https://github.com/plotly/plotly.js/issues/1298
Previously scattergl traces with `visible: false` or `visible: 'legendonly'` weren't filtered out of the [`convert`](https://github.com/plotly/plotly.js/blob/master/src/traces/scattergl/convert.js) step where several methods assumed non-empty `trace.x` and `trace.y`.
This PR add a third scattergl update path (along side the current fancy and fast paths) for `visible !== true` traces where gl-vis objects are updated with `Float62Array(0)` as data.
> gl2d non-visible traces improvements

- src/plot_api/subroutines.js
- src/plots/gl2d/camera.js
- src/plots/gl2d/scene2d.js
- src/plots/plots.js
- test/jasmine/tests/gl_plot_interact_test.js
to be merged into https://github.com/plotly/plotly.js/pull/1301 
This PR doesn't add any new functionality. It cleans up how fullLayout is updated to the scene2d instances after `Plots.supplyDefaults` create a new fullLayout from `{}`.
Previously, scene2d instances relied on `scene2d.plot` to update their ref to fullLayout. Now, this is done inside `Plots.supplyDefaults` so that
```js
gd._fullLayout === gd._fullLayout._plots[subplotId]._scene2d.fullLayout
// true
```
before and after `Plots.supplyDefaults`.
> Improvement in how gl2d refs to fullLayout are updated

- src/snapshot/cloneplot.js
- test/jasmine/tests/snapshot_test.js
The test case that now (should) be passing was failing before this fix. This impacted Plotly image server thumbnail generation.
> fixes 3d thumbnail clone when no xaxis in scene

- src/components/colorscale/calc.js
- src/plot_api/plot_api.js
- src/traces/contour/calc.js
- test/jasmine/tests/contour_test.js
- test/jasmine/tests/plot_api_test.js
Fixes a bug I found when playing around with contours: If you make a contour plot without specifying anything about contours (so you get the full `autocontour` behavior even though it's not explicitly stated) then you change the `z` range, it would not update the contour range. You can do this in straight plotly.js with `Plotly.restyle`, or in the workspace by making a contour plot and then modifying the data grid. Also ensures the correct level of replotting when you modify any part of an array, ie if `z` triggers a recalc, so does `z[1]`, `z[2][3]`, etc.
Related to #1282 but for now I don't want to go all the way into that, I just want to fix the bug.
cc @etpinard
> Contour auto persist

- src/plot_api/plot_api.js
- test/jasmine/tests/plot_api_test.js
fixes https://github.com/plotly/plotly.js/issues/1341
> Fire plotly_afterplot after Promise.all callback

- src/components/drawing/index.js
- test/jasmine/tests/plot_api_test.js
> Fix #1328 skip translatePoint for empty nodes

- src/traces/candlestick/transform.js
- src/traces/ohlc/helpers.js
- src/traces/ohlc/transform.js
- test/jasmine/tests/finance_test.js
fixes https://github.com/plotly/plotly.js/issues/1343
@VeraZab easy.
> Don't try adding rangeslider to visible: false finance traces

- src/components/legend/draw.js
- test/jasmine/tests/finance_test.js
fixes https://github.com/plotly/plotly.js/issues/1329
In https://github.com/plotly/plotly.js/pull/1020 (more precisely in https://github.com/plotly/plotly.js/pull/1020/commits/fbb299b145d0ed1c16e4802a4a25120938ff4e16) a custom finance trace `editable: true` legend item handler was added to ensure that editing legend text would propagate to the correct finance trace. Unfortunately, the relevant attribute name changed since then, breaking the behavior. Testing this particular `editable: true` isn't trivial hence why I left it out of #1020. 
In this PR, I make sure to :lock: this behavior down.
> Finance trace editable legend fix

- src/components/titles/index.js
- src/constants/interactions.js
- test/jasmine/tests/titles_test.js
fixes https://github.com/plotly/streambed/issues/8961
The issue turned out to be entering a title again after deleting the default, the hover events for the placeholder text weren't cleared.
@chriddyp you had a comment that it involved annotations as well, but I don't see it, so I'm assuming maybe *that* part actually was https://github.com/plotly/streambed/issues/8423
cc @etpinard
> Vanishing titles

- src/plots/cartesian/axis_defaults.js
- src/traces/candlestick/index.js
- test/jasmine/tests/finance_test.js
fixes https://github.com/plotly/plotly.js/issues/1357
> Ensure empty candlestick traces don't lead to autotyped 'category' x-axis

- src/plots/cartesian/dragbox.js
- test/jasmine/tests/click_test.js
fixes https://github.com/plotly/plotly.js/issues/1251
as mentioned in https://github.com/plotly/plotly.js/issues/1251#issuecomment-278976729 the fix was pretty easy, writing a test for it was a little harder though.
> Don't unscale bar layer points on drag

- src/components/modebar/buttons.js
- src/plot_api/plot_api.js
- src/plot_api/subroutines.js
- src/plots/gl3d/index.js
- src/plots/gl3d/scene.js
- test/jasmine/tests/gl_plot_interact_test.js
fixes https://github.com/plotly/plotly.js/issues/934
so that http://codepen.io/monfera/pen/KMmPPV can now use `Plotly.relayout` as
```js
function rotate(id, angle) {
var scene = gd._fullLayout[id];
var camera = scene.camera;
var rtz = xyz2rtz(camera.eye);
rtz.t += angle;
camera.eye = rtz2xyz(rtz);
Plotly.relayout(gd, id + '.camera', camera);
}
```
instead of digging into the `scene` object internals.
----
In addition, 
- by making `relayout` work for `scene.camera` we can now rewrite the 3d camera modebar handlers in a much cleaner way https://github.com/plotly/plotly.js/commit/604f7a0a4b443c15cc6f872122150ad653305083
- to ensure that camera relayout are as fast as they can be, a new relayout path `docamera` is added in https://github.com/plotly/plotly.js/commit/99ad3cbd207e0f85319344a224c …
> Make relayout work for `scene.camera`

- src/traces/bar/set_positions.js
- test/jasmine/tests/bar_test.js
fixes https://github.com/plotly/plotly.js/issues/1310
In bar calc, bars with non-numeric positions are not included in the resulting `gd.calcdata` ([ref](https://github.com/plotly/plotly.js/blob/32ccae5a5e86bcd8c974fea923436223d6fb723d/src/traces/bar/calc.js#L61-L63)). Later in `Plots.doCalcdata`, those skipped bars are given a placeholder calcdata item ([ref](https://github.com/plotly/plotly.js/blob/32ccae5a5e86bcd8c974fea923436223d6fb723d/src/plots/plots.js#L2046-L2048)) to ensure that all calc traces have as many items their corresponding fullData traces (see https://github.com/plotly/plotly.js/pull/1004/commits/dd05c6ee857ff5e5e537ccf946d715e60f9924e2 for more on `placeholder` calcdata items). 
These placeholder calc items contain `x: false, y: false`, which throws off the bar …
> Skip over placeholder calc traces in bar set positions

- bower.json
The minified version of plotly.min.js results in grunt-contrib-uglify
hanging when it hits the minified plotly.min.js
(gruntjs/grunt-contrib-uglify#233)
Best practices captured at bower/bower#393
specify that the main bower file should point to unminified files.
> bower best practice: Updating bower.json to reference non-minified file

- src/traces/scatter/arrays_to_calcdata.js
- src/traces/scatter/attributes.js
- src/traces/scatter/defaults.js
- src/traces/scatter/plot.js
- src/traces/scatter/style.js
- test/jasmine/tests/calcdata_test.js
- test/jasmine/tests/scatter_test.js
This PR adds a `customdata` attribute to scatter traces that is passed through and assigned to the `data` property of the corresponding calcdata entry.
To do: verify the manner in which this is (or is not?) actually passed all the way through to the dom element.
ping @alexcjohnson @etpinard
> Pass customdata through to scatter calcdata

- src/plots/gl3d/camera.js
- src/plots/gl3d/layout/defaults.js
- src/plots/gl3d/layout/layout_attributes.js
- src/plots/gl3d/scene.js
- test/jasmine/tests/gl3dlayout_test.js
- test/jasmine/tests/gl_plot_interact_test.js
resolves https://github.com/plotly/plotly.js/issues/456
for users that want to lock the camera position ... 
and to make our gl3d test more robust in preparation for https://github.com/plotly/plotly.js/issues/751
> Implement `scene.dragmode: false`

- src/plots/gl2d/scene2d.js
Fixes loosing axes/scale in sequence of `toImage`.
Test setup:
```js
let list = [
'gl2d_10',
'gl2d_12'
]
list.forEach(mock => {
let div = document.body.appendChild(document.createElement('div'))
Tabs.getMock(mock, (err, fig) => {
Plotly.plot(div, fig).then((div) => {
return Plotly.toImage(div).then(dataUrl => {
let img = document.body.appendChild(document.createElement('img'))
img.src = dataUrl
})
})
})
})
```
Allows to get rid of delay [here](https://github.com/plotly/plotly.js/blob/master/src/snapshot/helpers.js#L18) to speed up serializing.
Reminiscent of https://github.com/plotly/streambed/issues/6307.
@etpinard please take a look, should go well with https://github.com/gl-vis/gl-scatter2d-fancy/pull/5.
> Force redraw on updateSize

- package.json
- src/lib/geo_location_utils.js
- test/jasmine/tests/geo_test.js
fixes https://github.com/plotly/plotly.js/issues/1381
cc @chriddyp
> Country regex update

- src/plot_api/plot_config.js
- src/plots/cartesian/dragbox.js
- src/plots/cartesian/graph_interact.js
- test/jasmine/tests/config_test.js
For either UI appearance reasons, or because the range entry doesn't work as one might expect (for example, on http://localhost:3000/devtools/test_dashboard/#axes_category_categoryarray , which should maybe be addressed in addition), allow people to disable the entry. Default to on so that introduction of the option is backwards compatible.
> Allow controlling pan/zoom range entry.

- package.json
fixes https://github.com/plotly/plotly.js/issues/280 (as far as I know)
Big ups to @dfcreative for the `gl-plot3d` patch -> https://github.com/gl-vis/gl-plot3d/pull/6 :tada: 
Reviewers that have access to iOS devices are encouraged to check out http://codepen.io/etpinard/full/vxYezj/ to double check that the fix works as desired.
> Fix gl3D on iOS

- src/plots/cartesian/index.js
- test/jasmine/tests/cartesian_test.js
- test/jasmine/tests/gl_plot_interact_test.js
Previously,
```js
var newPlotLayout = {
"xaxis":{ "title":"xAxis Name" },
"yaxis":{ "title":"yAxis Name" }
}
var traces = [ {
"type":"scattergl",  // or any other non-cartesian type
"x":[1,2,3,4,5,6,7],
"y":[0,5,8,9,8,5,0]
}]
Plotly.newPlot('graph', [], newPlotLayout).then(function(){
Plotly.addTraces('graph', traces);
})
```
yielded
After this fix, we get:
as desired.
> Clear cartesian axis titles when deleting subplots

- src/plot_api/validate.js
- test/jasmine/tests/validate_test.js
Something I noticed while reviewing @monfera's `parcoords` PR. Easy late Friday Fixin' :beers:
> Fix `Plotly.validate` for colorscale attributes

- src/traces/heatmap/calc.js
- src/traces/heatmap/hover.js
- test/jasmine/tests/heatmap_test.js
fixes https://github.com/plotly/plotly.js/issues/1391
> Fix for xyz column heatmap trace 'text' on hover

- src/lib/geojson_utils.js
- test/jasmine/tests/scattermapbox_test.js
fixes https://github.com/plotly/plotly.js/issues/1418
easy. cc @rreusser
> Scattermapbox line trailing gaps

- src/plots/gl3d/scene.js
- test/jasmine/tests/gl_plot_interact_test.js
fixes https://github.com/plotly/plotly.js/issues/1407
> 3D hover text fixes for date axes

- src/plots/cartesian/axes.js
- test/jasmine/tests/axes_test.js
Fixup for commit https://github.com/plotly/plotly.js/pull/1355/commits/cebc31c72f20cd0e1426e8d9258f9e09e269817a part of the multiple range slider PR https://github.com/plotly/plotly.js/pull/1355
> Fixup for `Axes.expand` in the early return case

- src/plots/gl2d/scene2d.js
- test/jasmine/karma.conf.js
- test/jasmine/tests/gl2d_click_test.js
Currently, the `curveNumber` field in the gl2d hover data corresponds to the index in `fullData` after `visible: false` are filtered out. That is, `curveNumber` does not match the index in the user data array - as it should and does for all other subplot types. This PR fixes this.
> Show correct curve number in gl2d hover data

- src/components/annotations/draw.js
- test/jasmine/assets/drag.js
- test/jasmine/assets/mouse_event.js
- test/jasmine/tests/annotations_test.js
- test/jasmine/tests/shapes_test.js
Fixes annotation dragging, which was broken back in #1265 - and tests it in all permutations of data/paper reference and arrow/no arrow
@etpinard please review - will need a patch release for this to get 1.24 into the workspace.
> Annotations drag fix

- src/components/dragelement/unhover.js
- test/jasmine/tests/hover_label_test.js
fixes https://github.com/plotly/plotly.js/issues/1446
- so that in the case where a `plotly_unhover` handler calls a Plotly method (restyle, relayout and update which in turn call [`Plots.rehover`](https://github.com/plotly/plotly.js/blob/05c576c87a561da1879b734cf90449c190ccd552/src/plots/plots.js#L2042-L2046) added in https://github.com/plotly/plotly.js/pull/1304) an infinite loop :curly_loop:  isn't triggered (see https://github.com/plotly/plotly.js/issues/1446 for example)
- add test case showing the current infinite loop code path
cc @rreusser @alexcjohnson
> Clear `gd._hoverdata` before emitting `plotly_unhover`

- src/traces/bar/set_positions.js
- test/jasmine/tests/bar_test.js
fixes #1352 - makes autorange work with bar traces on log axes
@etpinard please review
> Log bar autorange fix

- test/jasmine/tests/gl_plot_interact_test.js
... for now. It's been a rough day on CI for those two tests. 
I could not find a way to make these tests more robust. Even translating the technique of [`gl2d_click_test.js`](https://github.com/plotly/plotly.js/blob/master/test/jasmine/tests/gl2d_click_test.js#L61) didn't work. I think we're not mocking the mouse events that trigger hover in the 3d [code](https://github.com/plotly/plotly.js/blob/b1b525ee042fd423a11801c2cca8a83c10e04da4/src/plots/gl3d/scene.js#L67-L124) correctly. At the moment we're simply triggering a [mouseover](https://github.com/plotly/plotly.js/blob/b1b525ee042fd423a11801c2cca8a83c10e04da4/test/jasmine/tests/gl_plot_interact_test.js#L45) event. So, let's skip them for now.
> Skip gl3d hover and click test on CI

- src/components/images/draw.js
- src/components/shapes/draw.js
- test/jasmine/tests/layout_images_test.js
- test/jasmine/tests/shapes_test.js
Soooo many edge cases... This one comes up in the workspace trying to move shapes or images between unlinked subplots, but it can also happen on initial draw - for example you put data on `xy` and `x2y2` but put a shape on `xy2` - not sure why you'd do this but it should be allowed, and certainly shouldn't error as it does now.
Meanwhile on the workspace side I'll just move these components to `layer: 'above'` - which may be less confusing there anyway since much of the time the objects would get hidden behind a plot otherwise.
@etpinard please review.
> Fix shapes and images referencing a missing subplot

- src/plot_api/plot_api.js
- test/jasmine/tests/plot_api_test.js
fixes https://github.com/plotly/plotly.js/issues/1480
I made a blunder in https://github.com/plotly/plotly.js/pull/1257 where conversion of `arrayOk` attributes from `fullData` -> `calcdata` was moved from the `plot` step to the `calc`. I tested `restyle`, it worked (in some situations) but for the wrong reason. Luckily the fixed wasn't too hard.
I wouldn't mind a @alexcjohnson review.
> Make restyling arrayOk attribute redo calcdata

- tasks/ci_test.sh
- test/image/export_test.js
Previously, image export [tests](https://github.com/plotly/plotly.js/blob/master/test/image/export_test.js) were simply firing requests to our image server all at once. 
We currently (only) generate 21 images in this export test, so most machines can handle that fairly easily. But looks like (from all the intermittent failures) CI has a harder time getting through those 21 requests. So the solution is easy, simply batch and throttle the image export requests as we do already in the image comparison tests.
As a bonus, I moved the export test to container 1 after the jasmine tests which should reduce the total test time.
> Batch image export tests

- src/traces/heatmap/convert_column_xyz.js
- test/jasmine/tests/heatmap_test.js
So that
```js
var x = [  0,  0,   0,  5,  null,   5,  10,  10,   10 ];
var y = [  0,  5,  10,  0,  null,  10,   0,   5,   10 ];
var z = [  0, 50, 100, 50,  null, 255, 100, 510, 1010 ];
Plotly.newPlot('graph', [{
type: 'heatmap',
x: x,
y: y,
z: z
}])
```
doesn't lead to index errors.
----
@rreusser unfortunately, commit 93a70be wiil conflict with your carpet PR https://github.com/plotly/plotly.js/pull/1239. I can help merge master into https://github.com/plotly/plotly.js/pull/1239 once this PR is in.
> Fix xyz column convert routine for columns containing nulls

- src/traces/parcoords/base_plot.js
- src/traces/parcoords/parcoords.js
Having tried more verbose approaches such as keeping around both the `<canvas>` element and the `regl` object, or just the `<canvas>` element, the simple and effective route from a memory and object lifecycle point of view was to let the previously created `regl` object be garbage collected. This is achieved by ensuring a fresh `<canvas>` is created and the previous one gets garbage collected (again, after trying some alternatives), including its attached `gl` context and `regl` object.
Also, the snapshot making code should no longer remove the canvas as it's not kept around on rerendering.
> Let the regl object tree be garbage collected on `Plotly.restyle`

- README.md
cc @etpinard 
- Highlight `scientific charts`
- "_over_ 20 " chart types now
- Financial charts too
> Update readme tagline

- src/components/annotations/convert_coords.js
- src/components/images/convert_coords.js
- src/plots/gl3d/scene.js
- test/jasmine/tests/gl_plot_interact_test.js
- test/jasmine/tests/plot_api_test.js
The two commits here each fix one relayout edge case broken since https://github.com/plotly/plotly.js/pull/1431 and https://github.com/plotly/plotly.js/pull/1403 respectively.
> Relayout edge case fixes

- src/traces/parcoords/index.js
- test/jasmine/tests/parcoords_test.js
- so that trace opacity isn't coerced.
cc @bpostlethwaite @monfera
> add 'noOpacity' flag to parcoords trace module

- src/traces/parcoords/calc.js
- src/traces/parcoords/parcoords.js
to be merged into https://github.com/plotly/plotly.js/pull/1508/
cc @monfera
> Edits for no unwarranted colorscale or related data on parcoords trace/fullTrace 

- src/traces/parcoords/calc.js
- src/traces/parcoords/defaults.js
- src/traces/parcoords/parcoords.js
- test/jasmine/tests/parcoords_test.js
Avoid color scale persistence on trace / fullTrace if the user hasn't specified one (as interpreted by [has_colorscale.js](https://github.com/plotly/plotly.js/blob/master/src/components/colorscale/has_colorscale.js#L36-L42))
Before this PR, `colorscale` related details populated `data` and `fullData`, as seen by these test case changes.
> No unwarranted colorscale or related data on parcoords trace/fullTrace

- src/traces/contour/contours_defaults.js
- src/traces/contour/defaults.js
- src/traces/histogram2dcontour/defaults.js
- test/jasmine/tests/histogram2d_test.js
fixes https://github.com/plotly/plotly.js/issues/1517 and DRYs up the `contours` defaults logic for `contour` and `histogram2dcontour` traces :palm_tree: 
Thanks @rreusser for finding this bug :microscope: :beetle:
> Histogram2dcontour relayout fix

- CONTRIBUTING.md
- package.json
- tasks/noci_test.sh
- tasks/test_bundle.js
- test/jasmine/karma.conf.js
This PR :hocho: `citest-jasmine` test script and allows easier and better configuration of our jasmine test runner using the [`minimist`](https://github.com/substack/minimist) argument parser.
From the new `npm run test-jasmine -- --info` output:
```
plotly.js karma runner for jasmine tests CLI info
Examples:
Run `axes_test.js`, `bar_test.js` and `scatter_test.js` suites in `autoWatch` / multiple run mode:
$ npm run test-jasmine -- axes bar_test.js scatter --watch
Run all tests with the `noCI` tag on Firefox in a 1500px wide window:
$ npm run test-jasmine -- --tags=noCI --FF --width=1500
Run the `ie9_test.js` bundle test with the verbose reporter:
$ npm run test-jasmine -- --bundleTest=ie9 --verbose
Arguments:
- All non-flagged arguments corresponds to the test suites in …
```
> Better test-jasmine karma.conf.js with minimist

- src/plot_api/plot_api.js
- test/jasmine/tests/frame_api_test.js
This PR changes the behavior of `deleteFrames(gd)` to delete *all* frames. Previously it threw a slice-null error. Contrast with `deleteTraces(gd)` which throws an error with a meaningful message or `animate(gd)` which animates all frames. In this case I chose to match the behavior of animate.
> make deleteFrames(gd) delete all frames

- src/components/dragelement/index.js
- src/components/dragelement/unhover.js
- src/plots/cartesian/graph_interact.js
- src/plots/geo/geo.js
- src/plots/mapbox/mapbox.js
- src/traces/pie/plot.js
- test/jasmine/assets/click.js
- test/jasmine/assets/get_client_position.js
- test/jasmine/assets/mouse_event.js
- test/jasmine/tests/click_test.js
- test/jasmine/tests/geo_test.js
- test/jasmine/tests/hover_pie_test.js
- test/jasmine/tests/scattermapbox_test.js
- test/jasmine/tests/ternary_test.js
With this PR, listeners to `plotly_click`, `plotly_hover` and `plotly_unhover` receive the original mouse event (that triggered the event) in `data.event`.
Implements #988 for scatter (@etpinard **edit:** cartesian), pie, ternary, geo and mapbox plots.
Fixes #1456 and #902
> Add mouse event to `plotly_click`, `plotly_hover` and `plotly_unhover`

- src/traces/bar/calc.js
- src/traces/bar/set_positions.js
- src/traces/bar/sieve.js
- test/jasmine/assets/custom_matchers.js
- test/jasmine/tests/bar_test.js
Currently
```js
var data = [{
x: [5, NaN, 15, 20, NaN, 21],
y: [20, NaN, 23, 25, NaN, 26],
type: 'bar'
}];
Plotly.newPlot('myDiv', data);
```
generates
[![image](https://cloud.githubusercontent.com/assets/6675409/24366413/108cea4a-12e7-11e7-8e6b-7ba517346590.png)](http://codepen.io/trisphx/pen/gmXQJG?editors=0010)
which is wrong.
With this PR, we get
> Bar with non-numeric (x,y) items bug fix

- src/plot_api/plot_api.js
- test/jasmine/tests/plot_api_test.js
fixes https://github.com/plotly/plotly.js/issues/1526
So that:
```js
Plotly.restyle(gd, {
marker: {
color: ['red', 'blue', 'green']
}
})
```
works in all situations.
> Assume recalc is needed when restyling attribute containers

- src/plots/plots.js
- test/jasmine/tests/config_test.js
A fix for: https://github.com/plotly/plotly.js/issues/1554. Do nothing if showLink is set to be false, to avoid performance overhead caused by measuring and reflows.
> Remove the performance overhead of showLink property

- src/traces/scatter/plot.js
Construct a map rather than an array to improve the performance of index search. Jasmine tests passed.
> Optimize the performance of scatter trace sorting comparator with map

- src/plots/plots.js
- test/jasmine/tests/plots_test.js
fullLayout is sometimes an empty object. This fixes an assumption that layout._transformModules is definitely defined.
> supplyTransformDefaults to fill in missing transformModules

- src/components/errorbars/index.js
- test/jasmine/tests/gl_plot_interact_test.js
Tiny fix for https://github.com/plotly/plotly.js/issues/1139
No idea why it was done for `x` but was not for `y`.
> Cast to empty array

- .github/PULL_REQUEST_TEMPLATE.md
- tasks/util/container_commands.js
- test/image/compare_pixels_test.js
One silver lining to this week's `nw.js` upgrade fiasco :2nd_place_medal:, I spent a lot of time staring at image request logs and found a few ways to make them easier to read. 
I hope this will benefit others when trying to make sense of image tests failures. :beers:
> Better image test logs

- package.json
Temporary fix for https://github.com/gl-vis/gl-scatter2d-sdf/commit/263078a7206d40dbadfb350613bb4701171fbb23#commitcomment-21683726
cc @dfcreative
> lock gl-scatter2d-sdf to 1.3.4

- src/plots/cartesian/set_convert.js
- src/plots/plots.js
- src/traces/scatter/plot.js
- test/jasmine/tests/axes_test.js
I added an auxiliary map for ``ax._categories`` array to avoid using ``Array.prototype.indexOf`` function searching for the existence of a category.
I tested [here](https://jsfiddle.net/smileyhaowen/cvLzxz7L/2/) and observed ~20% performance improvements on big amount of traces.
The unit test failed at some range_slider cases but I cannot figure out how my changes are related to those test cases.
> Optimize performance of setCategoryIndex

- build/plotcss.js
- src/components/annotations/annotation_defaults.js
- src/components/annotations/attributes.js
- src/components/annotations/draw.js
- src/components/color/index.js
- src/css/_cursor.scss
- src/plots/cartesian/graph_interact.js
- test/jasmine/tests/annotations_test.js
Provides hover text for annotations, using the existing hover label framework so you get stuff like automatic left/right flipping built in. Because this is a bit of a custom scenario anyway, and it's not always clear what style these hover labels should get, I included explicit styling. @etpinard and I iterated on this separately to come up with a structure that should work for styling trace hover items as well:
```js
{
annotations: [
{
...,
hovertext: "hello!",
hoverlabel: {
font: {
family: "courier",
size: 20,
color: "#f00"
},
bgcolor: "#0ff",
bordercolor: "#080"
}
}
]
}
```
> annotation hover text

- src/components/legend/draw.js
On a page with several charts, if you happen to have the cursor such that it winds up over a legend with scrollbar as you scroll the page, the scrollbar scrolls, but then captures all further `wheel` events. This change makes it so that the event is passed through to the page if the scrollbar is at the very top or bottom of the box so that the rest of the page can scroll.
> Passthrough the wheel event if the scrollbar is at the very top or bottom

- test/jasmine/tests/annotations_test.js
Pretty sure this fixes the intermittent test failure https://github.com/plotly/plotly.js/pull/1573#issuecomment-293684424
There may be other ways to do it (this adds ~1.5 sec to the test), but the main thing I think is avoiding an accidental doubleclick (and the associated autorange, which moves the annotations) by putting a delay after each click.
Tested 20x locally, which was enough to generally cause failure before...
cc @etpinard @rpaskowitz
> Note test fix

- src/snapshot/cloneplot.js
- test/jasmine/tests/mapbox_test.js
- test/jasmine/tests/scattermapbox_test.js
- test/jasmine/tests/snapshot_test.js
fixes https://github.com/plotly/plotly.js/pull/1598
`toImage` and `downloadImage` are broken currently for graphs with mapbox subplot and access token set via the `config` argument in `Plotly.plot` (e.g. like on plot.ly embed and shareplot).
> Mapbox to image context

- test/jasmine/tests/carpet_test.js
to be merged in @rreusser 's https://github.com/plotly/plotly.js/pull/1595
> A few more carpet plot tests

- src/traces/scatter/plot.js
fixes #1556 
I thought this was going to be very problematic since I struggled with it a lot the first time, but it turned out to be pretty simple. Just required selecting `tspan.line` instead of `tspan` when tweaking properties for animation. It was positioning regular inline spans the same as lines, which I think was the extent of the problem.
cc @n-riesco 
No tests added since it's transient behavior that I don't quite know a good way to test.
An animation of this working simultaneously with tspans representing both `<span>` and `<br>` tags:
> Fix tspan selector

- src/traces/contourcarpet/attributes.js
See https://github.com/plotly/streambed/pull/9387#issuecomment-295776192
> Remove arrayOk: true from contourcarpet `value` attr declaration

- src/traces/pie/style_one.js
- test/jasmine/tests/pie_test.js
quick fix for #1614 - just forgot to use `Color.fill` there.
cc @etpinard
> Split up fill and fill-opacity for pies

- src/traces/scatter/plot.js
- test/jasmine/tests/scatter_test.js
This PR adds a `'textpoint'` class to text points of scatter traces so that they can more easily and consistently be selected. I have no preference on the class name, but `'textpoint'` seemed reasonably descriptive (better than `'text'`, which is a little vague/overgeneral IMO)
> Add textpoint class to scatter text points

- src/plots/gl2d/camera.js
Should fix https://github.com/plotly/phoenix-integration/issues/148#issuecomment-297547082
> Fix aggressive zooming

- src/components/legend/draw.js
- test/jasmine/tests/legend_test.js
@rreusser your https://github.com/plotly/plotly.js/commit/c2994e7c11c8f7b520c2d737dc3d81429d2f2adf commit was missing one little bit of logic to get click and doubleclick legend interactions working :100: 
With this patch:
> Fix carpet legend dblclick toggle

- src/components/drawing/index.js
- src/lib/svg_text_utils.js
- src/plot_api/plot_api.js
Following my attempts in https://github.com/plotly/plotly.js/pull/1544, https://github.com/plotly/plotly.js/pull/1555, and https://github.com/plotly/plotly.js/pull/1557, I did some work to further improve the performance of Plotly. I scan through timeline results I captured on slow charts, which has 200+ traces, and did some caching. I also tried to skip processing on some components (e.g. colorbar) when it is enabled for a graph. 
By doing all these, I observed about 15% improvements on bar chart and marginal improvements on scatter plot.
> Misc performance optimization

- src/plot_api/manage_arrays.js
- test/jasmine/tests/annotations_test.js
Not the first time I've been bitten by the default sort being alphabetical even if the items are numbers... This made a bug where if you tried to add annotations 9 and 10 in a single `relayout`, it would try to add 10 first but it couldn't do that because 9 didn't exist yet (or if it did, 10 would get inserted in the array in the wrong places) and similar problems on deletion.
@etpinard OK?
> numeric sort for component edits

- src/traces/scattercarpet/calc.js
- test/jasmine/tests/carpet_test.js
This addresses @alexcjohnson's comment that scattercarpet was doing something weird and not handling array properties correctly. I mostly copied scattercarpet from scatterternary, but I wasn't quite able to reconstruct the removed line in this PR. I replaced it with `arraysToCalcdata` and it seems like things work fine though.
> Fix scattercarpet calc

- src/components/annotations/draw.js
- test/jasmine/tests/annotations_test.js
@etpinard quick one to add the native mouse event to `plotly_clickannotation`
> Annotationclick event

- src/lib/polygon.js
- src/traces/scatter/calc.js
- src/traces/scatter/select.js
- test/jasmine/tests/calcdata_test.js
- test/jasmine/tests/select_test.js
closes https://github.com/plotly/plotly.js/issues/1648
This PR first replaces `{ x: false, y: false }` scatter calcdata items with `{ x: BADNUM, y: BADNUM }` as put forward in https://github.com/plotly/plotly.js/pull/1564/commits/b5cd57308c60b584ba47ba93b35bb02efdd15418 then makes sure to skip those BADNUM items (as opposed to casting them to numbers - see codepen in https://github.com/plotly/plotly.js/issues/1648) in the scatter select routine.
cc @alexcjohnson it would be nice to include this in `1.27.0` if you get the time to review it :smile:
> Skip BADNUM items in scatter select routine

- src/plot_api/plot_api.js
- src/traces/contour/attributes.js
- src/traces/histogram2dcontour/attributes.js
- test/jasmine/tests/plot_api_test.js
- test/jasmine/tests/plotschema_test.js
fixes https://github.com/plotly/plotly.js/issues/1649
So, turns out that restyling `zmin` and `zmax` for contour traces has been broken since `v1.0.0` and nobody noticed :expressionless:  
This PR fixes this by making `zmin` and `zmax` redo calcdata as the contour [calc](https://github.com/plotly/plotly.js/blob/2105fd48663b616503337518bab28621c1804497/src/traces/contour/calc.js#L26) does use it. Note that this isn't the case for `heatmap` traces where `zmin` and `zmax` are only used in the [plot](https://github.com/plotly/plotly.js/blob/2105fd48663b616503337518bab28621c1804497/src/traces/heatmap/plot.js#L174) step.
> Contour restyle zmin zmax

- src/components/fx/hover.js
- test/jasmine/tests/hover_label_test.js
> Hover bugs #1575 and #1600

- src/components/drawing/index.js
- src/plots/cartesian/dragbox.js
- src/plots/cartesian/transition_axes.js
- src/traces/scatter/plot.js
- test/jasmine/tests/drawing_test.js
Addresses #1608. cc @alexcjohnson @n-riesco 
See: http://rickyreusser.com/demos/plotly-unsupported/text-transition.html
(The hover/click behavior is frustratingly finicky, but that's a separate issue. Also the date axes just return NaN which is why things are weird with dates. That's not addressed here.)
As for this PR, I'm a little worried `.points g` is too general a selector, so may need to add a class on text points to ensure *only* text is selected/modified by this tweak. Finally the transform logic is more than a little weird/ugly, but there's probably no avoiding that.
> Inverse-transform text on layout transition

- src/traces/sankey/plot.js
Issue reported by @alexcjohnson is https://github.com/plotly/plotly.js/issues/1662
> Fixes hover tooltip position with non-origin div position

- src/components/annotations/draw.js
- src/lib/svg_text_utils.js
- test/jasmine/tests/annotations_test.js
- test/jasmine/tests/svg_text_utils_test.js
- test/jasmine/tests/transform_sort_test.js
Fixes #1674
- Make sure links in svg text get `cursor: pointer` like regular html links
- Allow style for `<a>` elements in text, and make our parsing of these fields more robust
- If all you have is a link, in annotation text, turn the whole text box into a clickable link
@etpinard OK?
> Link style

- src/components/drawing/index.js
- src/traces/scatter/plot.js
- test/jasmine/tests/scatter_test.js
fixes https://github.com/plotly/plotly.js/issues/1666
cc @rreusser and @n-riesco 
Continuing on https://github.com/plotly/plotly.js/issues/1666#issuecomment-300627893, I found a case (see 		310e67a ) where `restyle` was failing on blank `x`, `y` arrays without using filter transforms, so the patch had to be made in `scatter/plot.js` (see 49e5da5)
After this patch:
> Scatter <g textpoint> join fixup

- src/components/images/draw.js
Addresses issue https://github.com/plotly/plotly.js/issues/1685
Fixes a bug with IE11 - when images are specified in the layout, the promise is never resolved from the `draw()` function.
```
plotly.newPlot(elem).then(function(){
//never hit
});
```
> Move the promise resolution to address IE11 bug

- src/plots/plots.js
- test/jasmine/tests/transform_sort_test.js
```js
Plotly.newPlot('graph', [{
mode: 'markers',
x: ['A', 'B', 'C'],
y: ['a', 'b', 'c'],
marker: { size: [20, 30, 50] },
transforms: [{
type: 'sort',
target: [2, 1, 0]
}]
}])
```
currently gives:
where the categories are re-arranged after the `sort` transform - which is consistent with how we handle categories in `filter` transforms. See PR https://github.com/plotly/plotly.js/pull/1260 for more details.
But setting `layout.xaxis.categoryarray: ['A', 'B', 'C]` -- which implies that the category positions are fixed -- curently gives the same results as above.
With commit 7a2a2e1
```js
Plotly.newPlot('graph', [{
mode: 'markers',
x: ['A', 'B', 'C'],
y: ['a', 'b', 'c'],
marker: { size: [20, 30, 50] },
transforms: [{
type: 'sort',
target: [2, 1, 0]
}]
}], {
xaxis: {
categoryarray: ['A', 'B', …
```
> Sort + set 'categoryarray'

- src/components/drawing/index.js
- src/components/sliders/draw.js
- src/components/updatemenus/draw.js
- src/lib/svg_text_utils.js
- src/plot_api/plot_api.js
- src/plots/plots.js
- src/traces/carpet/plot.js
- test/jasmine/tests/plots_test.js
fixes https://github.com/plotly/plotly.js/issues/1675 
Take 2 of https://github.com/plotly/plotly.js/commit/29abb5d8ec3dea92cc71f438fffa6785463d1fb1 from  @hy9be's https://github.com/plotly/plotly.js/pull/1585 to be merged in https://github.com/plotly/plotly.js/pull/1683 
@hy9be would you mind checking that this solution here is as fast as yours?
> Drawing perf take2

- src/components/drawing/index.js
- src/components/sliders/draw.js
- src/components/updatemenus/draw.js
- src/lib/svg_text_utils.js
- src/plot_api/plot_api.js
- src/plots/plots.js
- src/traces/carpet/plot.js
- test/jasmine/tests/drawing_test.js
- test/jasmine/tests/plots_test.js
fixes https://github.com/plotly/plotly.js/issues/1678
I decide to play it safe an revert https://github.com/plotly/plotly.js/pull/1585/commits/29abb5d8ec3dea92cc71f438fffa6785463d1fb1 until we :lock: the `Drawing.bBox` behavior better. Reverting https://github.com/plotly/plotly.js/pull/1585/commits/29abb5d8ec3dea92cc71f438fffa6785463d1fb1 also fixes https://github.com/plotly/plotly.js/issues/1675, but maybe we could do better there.
> Drawing bbox fix for window scroll

- src/components/sliders/attributes.js
- src/components/sliders/defaults.js
- src/components/updatemenus/attributes.js
- src/components/updatemenus/defaults.js
- src/plots/command.js
- test/jasmine/tests/command_test.js
- test/jasmine/tests/sliders_test.js
- test/jasmine/tests/updatemenus_test.js
This PR implements half of #1695: the `skip` method by allowing it as a method and otherwise living with it but mostly ignoring it.
/cc @etpinard @alexcjohnson @n-riesco
> Allow the skip api method for sliders and udpatemenus

- src/components/sliders/attributes.js
- src/components/sliders/defaults.js
- src/components/sliders/draw.js
- src/components/updatemenus/attributes.js
- src/components/updatemenus/defaults.js
- src/components/updatemenus/draw.js
- test/image/mocks/sliders.json
- test/jasmine/tests/sliders_test.js
- test/jasmine/tests/updatemenus_test.js
This PR implements the second part of #1695 by adding an `execute` flag to sliders and updatemenus API calls. I had a bit of trouble getting a spy to work, so I omitted the end to end test at the moment. The full extent of the change is to simply sidestep the call to `Plots.executeAPICommand`, so it should have few effects except to skip the API call.
I have *not* yet tested whether everything works identically if the API call is moved into the event handler. Although that's the reason for this PR to exist, it's also a separate usage concern.
/cc @etpinard @alexcjohnson 
#1695
> Add `execute` flag to components

- src/snapshot/tosvg.js
- test/jasmine/tests/snapshot_test.js
fixes https://github.com/plotly/support-assets/issues/87
The `Plotly.toImage` as well as the to-image modebar button are currently broken for graphs with set `marker.gradient` (added in https://github.com/plotly/plotly.js/pull/1620/f). Note that the image tests work fine inside the image test container - I'm thinking this has to do with nw.js 0.12 which uses a much older Chromium version (we gotta upgrade that thing soon).
The fix applies the same logic as in https://github.com/plotly/plotly.js/pull/604. In #604, the `"` surrounding `font-family` property value (e.g. `style="font-family: "Times New Roman""`) were stripped before serializing with `XMLSerializer` and then put back after. In this PR, the `"` surrounding the `fill` property value for gradients (e.g. `style="fill: …
> Fix toImage for marker gradient

- src/components/sliders/attributes.js
- src/components/updatemenus/attributes.js
/cc @etpinard 
Adds missing docs for #1699.
> Add `skip` documentation

- src/components/drawing/index.js
- src/traces/scatter/plot.js
- test/jasmine/tests/scatter_test.js
fixes https://github.com/plotly/plotly.js/issues/1706 (an attempt at least)
> Selection re-ordering for scatter traces with `ids`

- test/jasmine/assets/custom_matchers.js
- test/jasmine/assets/double_click.js
- test/jasmine/assets/modebar_button.js
- test/jasmine/assets/mouse_event.js
So that they can be more easily reused in other projects e.g. in https://github.com/plotly/support-assets/pull/150
@rreusser @alexcjohnson @n-riesco
> Replace @src shortcut paths with `../../../src` in test assets

- src/lib/svg_text_utils.js
Currently relative links (`<a href="/path/to/file">Link!</a>`) that users insert in their plots fail in IE, because it treats the protocol of such a link as `''` - other browsers have these inherit from the page you're in. This fixes that.
@etpinard I can't think of a way to test this (since I can't find any way on Chrome or FF to generate an empty protocol) can you?
@scjody I don't see any way to turn this into an XSS attack, do you?
> add empty protocol to link whitelist for IE relative links

- package.json
to grab https://github.com/gl-vis/gl-error3d/pull/2 and :lock: down the https://github.com/plotly/plotly.js/issues/1562 fix.
> bump gl-error3d to ^1.0.5

- src/plots/plots.js
- test/jasmine/tests/transform_sort_test.js
fixes https://github.com/plotly/plotly.js/issues/1713
As promised, it's not pretty. cc @n-riesco @alexcjohnson
> Transformed array on zoom fix

- test/jasmine/tests/transform_sort_test.js
This test doesn't behave well on CI as noticed by @alexcjohnson and @rreusser 
So to remedy this problem, we'll test sort transform event data using hover events only:
- hover and click when invoked programmatically back-to-back don't behave well.
- this test case makes assertions on the event data (i.e. `gd._hoverdata`) which is the same for hover and click
- use `delete gd._lastHoverTime` to :hocho: that annoying wait promise
> Fixup sort transform event data text using

- src/components/drawing/index.js
- src/traces/scatter/plot.js
- test/jasmine/tests/scatter_test.js
This PR solves #1721 and transitions fillcolor as expected, which currently only updates on an actual redraw.
An example in which it works: http://rickyreusser.com/demos/plotly-unsupported/fillcolor-animation.html
/cc @cpsievert
> Transition fillcolor

- src/lib/svg_text_utils.js
- test/jasmine/tests/svg_text_utils_test.js
Adds two new attributes for more flexibility to determine where links in our pseudo-html text will open:
- `target`, which is preferred over `xlink:show` in modern browsers and has more functionality - but I still include `xlink:show` as a fallback: `'replace'` if target is `'_self'`, `'_parent'`, or `'_top'` and `'new'` for `'_blank'` or a named frame. Some `xlink:show` implementations seem to accept more values to partially bridge the gap with `target` but some don't, and I believe most that do will look at `target` anyway.
- `popup`, which doesn't exist in html but we need a way to insert the "window features" string without accepting arbitrary javascript, so inventing a new attribute seemed like the easiest way. Note that `target` is sent as the second arg (`name`) to `window.open`, …
> support target and popup attributes in pseudo-html text links

- .eslintrc
- test/image/strict-d3.js
As [suggested](https://github.com/plotly/plotly.js/pull/1723#discussion_r118360733) by @etpinard
> Prohibit CSS transform usage on SVG elements due to IE

- src/traces/sankey/render.js
There is still insufficient support for CSS styles on SVG elements in IE: https://github.com/ropensci/plotly/issues/1023#issuecomment-303529546
> Switching to a SVG presentation attribute to assist Microsoft browsers

- src/plots/gl3d/scene.js
- test/jasmine/tests/gl_plot_interact_basic_test.js
Another bug I found when working on gl3d annotations.
On scene drag/pan, we fire a `plotly_relayout` event mocking the equivalent `Plotly.relayout` call that would generate the current view.
Previously, the mocked event data looked:
```js
{ scene: { eye: {/**/}, up: {/**/}, center: {/**/} }
```
(or `scene2: // ...` for multiple-scene graphs) which isn't compatible with our plot schema
Now with this PR, the mocked event data is:
```js
{ 'scene.camera': { eye: {/**/}, up: {/**/}, center: {/**/} }
```
cc @monfera
> Fixup camera interaction relayout event data

- test/image/strict-d3.js
The test should also work in case `val` is not a string.
> Putting CSS transform test outside condition

- src/components/annotations/annotation_defaults.js
- src/components/annotations/click.js
- src/components/annotations3d/convert.js
- src/components/annotations3d/defaults.js
- src/lib/index.js
- src/plots/cartesian/axes.js
- src/plots/cartesian/set_convert.js
- src/plots/plots.js
- src/traces/heatmap/calc.js
- test/jasmine/tests/annotations_test.js
- test/jasmine/tests/heatmap_test.js
- test/jasmine/tests/plot_api_test.js
fixes https://github.com/plotly/plotly.js/issues/1720
This PR is a rebased version of the [`component-category-axes-relayout-attempt`](https://github.com/plotly/plotly.js/compare/component-category-axes-relayout-attempt) branch with better commit messages.
In brief, category (i.e. string) values of annotation/shape/image position attributes (e.g. `x`, `y`, `x0` ...) referencing `type: 'category'` axes are no longer converted to indices (i.e. numbers) during the defaults step. This implies:
- the annotation/shape/image defaults no longer depend on `ax._categories` (which isn't defined during `Plots.supplyDefaults` which led to :bug: #1720 ) and this ugly category-axes-only [block](https://github.com/plotly/plotly.js/blob/7a281ccbb2046888d2d2587461a99fd51ee63d8e/src/plots/plots.js#L2109-L211 …
> Improved category axes conversions

- src/plots/gl2d/scene2d.js
- test/jasmine/tests/gl2d_click_test.js
While working on axis constraints by restricting domain, I found that a bunch of tests were failing locally for me, consistently, on master as well as my branch. Most just needed increased tolerances so I'll just include them in the constraints PR. But this one, "scattergl after visibility restyle", pointed to a real bug in gl2d: if you mouseout of the gl2d plot while hovering on a point, it will not unhover.
@etpinard I guess in principle this should be an independent PR into master (in which case it would also need another commit from my branch that cleaned up the test suite so I could see where the failure was) but I need it in my `constrain-domain` branch to get tests to pass and somehow noone else encountered this error?
It would also be nice eventually if the `mouse-change` package …
> fix bug with unhover in gl2d

- src/snapshot/svgtoimg.js
The `svgToImg()` function tries to normalize the SVG for compatibility
with IE.  However, currently it use a regular expression that is too
greedy when matching the attribute values that need quotes changed from
single to double.  The result is that invalid XML is generated and will
cause IE11 to fail with a `XML 5607` error and `svgToImg()` will never
return.  Edge will not complain but will receive invalid XML, which
causes problems when used.
This change restricts matching to only data surrounded by single quotes.
Seems like a jasmine test should be added for `svgToImg()` along the
lines of
`it('Returns valid XML',...)`
Also addresses: https://community.plot.ly/t/plotly-toimage-xml5607-error-in-ie11/4223
> Fix RE used to correct quotes used in URLs for IE.

- src/components/fx/calc.js
- src/components/fx/hover.js
- src/components/fx/index.js
- src/lib/coerce.js
- src/lib/index.js
- src/plot_api/helpers.js
- src/plot_api/plot_schema.js
- src/plots/attributes.js
- src/plots/gl2d/scene2d.js
- src/plots/gl3d/scene.js
- src/plots/plots.js
- src/traces/choropleth/defaults.js
- src/traces/pie/defaults.js
- src/traces/pie/plot.js
- src/traces/sankey/defaults.js
- src/traces/scattercarpet/attributes.js
- src/traces/scattercarpet/defaults.js
- src/traces/scattergeo/defaults.js
- src/traces/scattermapbox/defaults.js
- src/traces/scatterternary/defaults.js
- test/jasmine/tests/gl2d_click_test.js
- test/jasmine/tests/gl_plot_interact_test.js
- test/jasmine/tests/hover_label_test.js
- test/jasmine/tests/hover_pie_test.js
- test/jasmine/tests/scatterternary_test.js
- test/jasmine/tests/transform_filter_test.js
resolves https://github.com/plotly/plotly.js/issues/1749
TODO:
> Array support for trace `hoverinfo`

- src/lib/coerce.js
- src/plot_api/validate.js
- test/jasmine/tests/lib_test.js
- test/jasmine/tests/validate_test.js
to be merged in @alexcjohnson 's https://github.com/plotly/plotly.js/pull/1767
fixes `Plotly.validate` for axis `anchor`, `overlaying` and `contraintoward`.
> Validate dynamic enumerated

- src/lib/svg_text_utils.js
- src/snapshot/tosvg.js
- test/jasmine/tests/svg_text_utils_test.js
For our rich text displays: instead of converting pseudo-HTML into svg XML and then parsing this into elements, this PR converts the pseudo-HTML directly into `<tspan>` (and `<a>`) elements. Interestingly the speed gain isn't as pronounced as it was in #1776 using `innerHTML` but it helps a bit, and also addresses a couple of deficiencies in the previous version.
> Build svg text

- src/components/annotations/draw.js
- test/jasmine/tests/annotations_test.js
fixes #1771 
@etpinard the bug was actually introduced in https://github.com/plotly/plotly.js/commit/aa58118e3665dd60d3fdda689ae58cf1814f99c2 - nice easy fix, plus a test 🔒
> hide off-plot annotations

- src/components/fx/helpers.js
- src/components/fx/hover.js
- src/components/fx/index.js
- src/plot_api/plot_schema.js
- src/plots/attributes.js
- src/plots/cartesian/select.js
- src/plots/gl2d/scene2d.js
- src/plots/gl3d/scene.js
- src/plots/plots.js
- src/traces/scatter/attributes.js
- src/traces/scatter/defaults.js
- src/traces/scatter/select.js
- src/transforms/filter.js
- src/transforms/sort.js
- test/jasmine/tests/geo_test.js
- test/jasmine/tests/gl2d_click_test.js
- test/jasmine/tests/gl_plot_interact_test.js
- test/jasmine/tests/scattermapbox_test.js
- test/jasmine/tests/select_test.js
- test/jasmine/tests/ternary_test.js
I was about to _just_ add `ids` and `customdata` values in the hover/click/select event data when I realised wouldn't it be nice to include values of all array attributes? We already need to keep track of those attributes for transforms and `restyle`. That is, calls to `PlotSchema.findArrayAttributes` aren't going anywhere. So, might as well cache that list and use it during picking/selecting!
For example,
```js
Plotly.newPlot('graph', [{
y: [1, 2, 1],
ids: ['a', 'b', 'c'],
customdata: [{sup: 'hello'}, 30, 'lol'],
marker: {
size: [20, 10, 30]
}
}])
.then(gd => {
gd.on('plotly_hover', d => console.log(d.points[0]))
})
```
then hovering on `(x=1,y=2)` gives:
```
{
// as before
x: 1,
y: 2,
data: /**/,
fullData: /**/,
xaxis: /**/,
yaxis: /**/,
curverNumber: 0,
pointNumber: 1,
// new
id: 'c', …
```
> Include values of all array attributes in hover/click/select event data

- src/components/fx/click.js
- src/components/fx/hover.js
- src/plots/cartesian/graph_interact.js
- src/plots/ternary/ternary.js
- test/jasmine/tests/hover_label_test.js
Rehover caused a lot of problems with dropped clicks. This PR recomputes the hover data *on click* so that when it's used in the click, it's up to date. It's perhaps a bit of wasted effort, but it should solve the problems with dropped clicks.
> Recompute hover on click to increase click robustness

- src/plot_api/helpers.js
- src/transforms/groupby.js
- test/jasmine/tests/transform_groupby_test.js
- test/jasmine/tests/transform_multi_test.js
This PR supersedes #1465 to rework keyed styles into an array of objects that's more plotly-friendly.
> Rework transform style into array syntax

- src/components/drawing/index.js
- tasks/test_syntax.js
> Take out node.children

- src/components/fx/helpers.js
- test/jasmine/tests/hover_label_test.js
This PR address the issue in #1807 by exiting early if `arrayAttrs` is undefined. This may or may not be an appropriate fix. I could test this by passing it a plain object with no _arrayAttrs, but it seems to be of questionable value since `appendArrayPointValue` isn't tested otherwise. Can add, but I'll wait for a second opinion on the source of the problem.
> Fix hover error in appendArrayPointValue

- src/plot_api/plot_schema.js
- test/jasmine/tests/transform_multi_test.js
`transforms: [{}]` causes plotly to fail with:
See: https://codepen.io/rsreusser/pen/GEyWav
I could have it compress empty transforms out of the picture (`[{}] --> []`, but because of indexing (it should work but I'm too worried it'll cause unexpected failures elsewhere), I've elected to just leave `[{}]` --> `[{}]`. This PR prevents it from throwing an error.
> Accept empty transforms

- src/plots/cartesian/select.js
- src/plots/ternary/index.js
- src/plots/ternary/ternary.js
- test/jasmine/tests/select_test.js
fixes issue-less bug discovered while working on `cliponaxis: false`
In brief, select/lasso drag modes are currently 100% broken on ternary subplots (e.g http://rickyreusser.com/plotly-mock-viewer/#ternary_markers) since https://github.com/plotly/plotly.js/pull/448 (merged more than 1 year ago :upside_down_face: ). Note that `scattertenary` traces supported select/lasso in their first implementation in https://github.com/plotly/plotly.js/pull/390.
> Fix scatterternary lasso/select drag modes

- package.json
- src/components/dragelement/index.js
- src/plot_api/plot_api.js
- src/plots/gl2d/camera.js
- src/plots/gl2d/scene2d.js
- src/traces/scattergl/convert.js
- test/jasmine/assets/touch_event.js
- test/jasmine/karma.conf.js
- test/jasmine/tests/select_test.js
Resolves https://github.com/plotly/plotly.js/issues/1790
We have to avoid creating `dragCover` for touch-only devices, because `touchmove`, unlike `mousemove`, requires the same element where `touchstart` happened.
Is there any particular reason we don't use `document` for catching mouse events? What makes `dragCover` different from `document`?
@etpinard @alexcjohnson 
TODO:
selection in a way similar to [this](https://github.com/dfcreative/mucss/blob/master/selection.js)
> Enable touch interactions for select/lasso/others

- src/traces/contourgl/convert.js
- src/traces/heatmapgl/convert.js
- test/jasmine/tests/gl2d_click_test.js
fixes https://github.com/plotly/plotly.js/issues/1825
Luckily, the problem described in #1825 only concerns `heatmapgl` - as opposed to the solution proposed in https://github.com/plotly/plotly.js/pull/1833. 
The patch is simple. It brings `heatmapgl`'s `pointNumber` event data field on par with other 2D trace types. This PR also adds an _asymmetric_ `heatmapgl` hover test case. 
cc @alexcjohnson @dfcreative
> Fix heatmapgl point number event data

- src/components/modebar/buttons.js
- src/components/modebar/manage.js
- src/plots/mapbox/index.js
- src/plots/mapbox/mapbox.js
- test/jasmine/tests/mapbox_test.js
- test/jasmine/tests/modebar_test.js
... via a new mode bar button and double click.
Moreover, this PR adds the generic `toggleHover` mode bar button to mapbox subplots.
This helps mabpox subplots become _more on-par_ with our other older subplot types (see more in https://github.com/plotly/plotly.js/issues/815). I hope you'll :heart: the changes.
> Mapbox reset view back to initial

- src/plots/cartesian/transition_axes.js
- test/jasmine/tests/annotations_test.js
This PR solves an oversight on my part. At the moment if there's no transitioned axis, then layout objects aren't updated. This PR solves that by calling the layout update if the axes are not otherwise affected.
cc @jackparmer
> Still animate layout objects if there's no transitioned axis

- src/components/fx/helpers.js
- src/plot_api/plot_schema.js
- test/jasmine/tests/cartesian_interact_test.js
- test/jasmine/tests/gl_plot_interact_test.js
fixes https://community.plot.ly/t/tooltips-dont-show-up-in-a-heatmap/4972 first reported by @empet
Another bug introduced by https://github.com/plotly/plotly.js/pull/1770. This time `appendArrayPointValue` tried to dig into a trace's `colorbar.tickvals` and `colorbar.tickvals` with a 2D `pointNumber` leading a slew of exceptions during hover. Note that `colorbar.ticktext` and `colorbar.tickvals` are both declared as `valType: 'data_array'` at the moment.
The proposed fix in 0aa87c9da6914bad762e36c2571886db4c93ad93 isn't great, but feels the safest to my eyes.
Perhaps a better, more evolved fix would make a distinction between `data_array` attributes that are expected to have the same dimension as of the _main_ data coordinates (in 2D traces, that _main_ data coordinate is `z`). and …
> Hover fix for colorbars with custom tickval / ticktext

- src/lib/svg_text_utils.js
- test/jasmine/tests/svg_text_utils_test.js
Fixes an XSS vulnerability in links defined with the special `popup` attribute. See the added test case for three variants that were previously able to exploit it.
The fix here constructs the `onclick` handler in a safer way: it re-extracts `href` and `target` from the element attributes, and it restricts the characters allowed in the `popup` (`strWindowFeatures`) attribute since we know there's [only so much](https://developer.mozilla.org/en-US/docs/Web/API/Window/open) that can be used there.
cc @etpinard @scjody - this bug came in with #1783 which was included in v1.28.0
> safer construction of popup click handler

- src/components/annotations/draw.js
- src/components/colorbar/draw.js
- src/components/legend/draw.js
- src/components/shapes/draw.js
- src/components/titles/index.js
- src/plot_api/plot_api.js
- src/plot_api/plot_config.js
- test/jasmine/tests/config_test.js
Adds a new config option `edits` that's an object of all the separate editable interactions you want to enable or disable. The original `config.editable` should still be a boolean (default `false` as always) that sets the defaults for *all* our supported editable interactions, and `config.edits` can override pieces of it. For example if you *only* want to enable editing legend entries, and axis titles and moving the legend, you could do:
```
Plotly.newPlot(gd, data, layout, {
edits: {legendText: true, axisTitleText: true, legendPosition: true}
})
```
closes #1872
cc @etpinard @geocosmite
I chose to be fairly granular - for example, annotations have three separate flags (`annotationText`, `annotationPosition`, and `annotationTail`, on the idea that for example you might want to allow …
> Granular options for on-chart editing

- package.json
Enable better hover detection
resolves https://github.com/plotly/plotly.js/issues/1889
@etpinard
> Bump has-hover

- src/traces/histogram/calc.js
- test/jasmine/tests/histogram_test.js
Fixes https://github.com/plotly/plotly.js/issues/1682
@alexcjohnson does this look acceptable?
> Compute histogram bin positions beyond length 5000

- src/plots/cartesian/axes.js
- test/jasmine/tests/axes_test.js
fixes #484 
@etpinard what do you think about this solution: Stopping if two consecutive ticks are truly identical (infinite loop) or if we make more ticks than there are pixels on the axis. I included the same 1000 for short axes and as a fallback in case there are callers with dummy axes that don't have a `_length`. But it seems to me that any case where you'd *really* want a large number of ticks, there will still be less than one per pixel.
> smarter tick count limit for cartesian axes

- src/components/fx/attributes.js
- src/components/fx/calc.js
- src/components/fx/hover.js
- src/components/fx/hoverlabel_defaults.js
- src/components/fx/layout_attributes.js
- src/lib/coerce.js
- test/jasmine/tests/fx_test.js
- test/jasmine/tests/hover_label_test.js
resolves https://github.com/plotly/plotly.js/issues/1777
> Hover label namelength

- src/components/errorbars/plot.js
- src/plots/cartesian/dragbox.js
- src/traces/bar/plot.js
- src/traces/box/plot.js
fixes #1879 and a few related effects:
- non-scaling stroke on errorbars, bar outlines, and box plots
- include box plot points in the rescaling we do for scatter points
As far as I can tell that's everything we put on SVG cartesian axes.
Not sure if there's a useful way to test this - I was pondering making a complicated plot and testing that every `<path>` on it either has `vector-effect: non-scaling-stroke` set or matches `.scatterlayer .points .point` or `.boxlayer .points .point` but I kind of feel like that will cause more problems than it solves, and now that we know about these strategies we won't forget to use them when we make new trace types.
cc @etpinard
> better zooming behavior for errorbars, bars, and box plots

- src/traces/histogram/calc.js
- src/traces/histogram2d/calc.js
- test/jasmine/tests/histogram2d_test.js
- test/jasmine/tests/histogram_test.js
on par with colors and axis ranges
fixes #24 
@etpinard are you OK with this?
> copy histogram autobinx/y back to the input trace

- src/lib/svg_text_utils.js
- test/jasmine/tests/svg_text_utils_test.js
See #1923. This PR modifies svg text utils to ignore dangling closing tags when there's nothing on the stack.
> Ignore bare closing tags in html-like input

- lib/aggregate.js
- lib/index.js
- src/plots/cartesian/axes.js
- src/transforms/aggregate.js
- src/transforms/filter.js
- src/transforms/groupby.js
- test/jasmine/tests/transform_aggregate_test.js
- test/jasmine/tests/transform_multi_test.js
Adds an `aggregate` transform type, which is actually a closer analog of sql `groupby` than the `groupby` transform is because it coalesces all values in each group to a single output, and leaves the results all in a single trace. Each array attribute needs an aggregation function; if not provided we fall back on `"first"` ie the first value encountered in the group.
Note that some data types / aggregation function combinations don't make much sense, but we allow them anyway: date sums (we add milliseconds since 1970 and then convert back to a date), category sums (we add category serial numbers), category averages (we average serial numbers then round). The tests include an example to show how this plays out.
I did NOT implement any sort of binning in this PR. That will be a separate PR …
> Aggregate transforms

- src/snapshot/tosvg.js
- test/jasmine/tests/snapshot_test.js
fixes an issue-less bug I discovered while working on `image-exporter`.
See https://github.com/plotly/plotly.js/pull/1694 for more on the subject, this PR here applies the same fix to legend items.
> Fix toSVG for marker gradient legend items

- src/constants/numerical.js
- src/plots/cartesian/axes.js
- test/jasmine/tests/axes_test.js
Fixes #1920 
In addition to no longer rounding the exponent to a factor of 3 when you get past the SI prefixes, I also changed it to `exponentformat: 'power'` there - ie "&times;10<sup>16</sup>" instead of "e+16" as we had before. I suspect using `exponentformat: 'e'` as the fallback was a decision made before we supported pseudo-html in tick labels.
cc @etpinard @AndiMD
> Better exponent treatment beyond SI prefixes

- src/plots/cartesian/axes.js
- test/jasmine/tests/axes_test.js
This PR fixes #755 and #1711. After a bit of digging:
**The problem**: Hover labels are sometimes wrong by arbitrarily gigantic orders of magnitude, which is bad. Hover labels piggyback on `Axes.tickText`, which sometimes hides exponents and just shows 1/2/5 values. That's *always* invalid for hover labels since their exponent is not shown elsewhere as it is for axes.
**The solution**: whenever `'hover'` is passed to `tickText`, this PR prevents it from making any automated decision about whether to hide the exponent, instead just obeying the axis formatting.
> Fix hover label exponents

- src/traces/parcoords/base_plot.js
Purports to fix https://github.com/plotly/plotly.js/issues/1929
> Identify canvases for the specific `gd` being exported

- src/plots/cartesian/axes.js
- test/jasmine/tests/hover_label_test.js
This PR fixes the gl3d hover issue caused and not caught by #1932. It also adds a test to regular log scatter since there's nothing gl-specific about the failure, just that it wasn't tested in regular scatter.
> Fix hover label exponent hiding or gl3d log hover

- src/plots/cartesian/axes.js
- test/jasmine/tests/cartesian_test.js
fixes https://github.com/plotly/plotly.js/issues/1914
This should do the trick :tophat:
> Clear axis title on full axis redraw

- src/plots/cartesian/axes.js
- test/jasmine/tests/hover_spikeline_test.js
fixes https://github.com/plotly/plotly.js/issues/1977 and makes https://github.com/plotly/plotly.js/pull/1604 obsolete.
@alexcjohnson I wouldn't mind a +1 on my approach before I add a test or two.
> Make hover spikes work when no tick labels are present

- tasks/util/strict_d3.js
Otherwise `npm run test-jasmine` fails with karma-browserify as 
```sh
07 09 2017 10:43:12.748:ERROR [framework.browserify]: bundle error
07 09 2017 10:43:12.764:ERROR [framework.browserify]: Error: Cannot find module 'C:projectsplotly.js    estimagestrict-d
3.js' from 'C:\projects\plotly.js\test\jasmine\tests'
```
> Fix karma tests in windows

- src/plot_api/to_image.js
- src/snapshot/svgtoimg.js
- src/snapshot/tosvg.js
- test/jasmine/tests/snapshot_test.js
- test/jasmine/tests/toimage_test.js
This PR adds a `scale` option to `Plotly.toImage` (and `Plotly.downloadImage`) which _scales_ the generated image by a given factor. Note that, _scaling_ an image isn't the same as just relayouting it to some factor times the current layout `width`/`height` values. Scaling scales every feature of a graph - this should help users that want higher resolution image exports.
The new `scale` has an effect on all the supported formats. For `png`, `jpeg` and `webp` this is accomplished using  [`context.drawImage`](https://developer.mozilla.org/en/docs/Web/API/CanvasRenderingContext2D/drawImage)'s width/height options. For `svg`, we tweak the [`viewBox`](https://developer.mozilla.org/en/docs/Web/SVG/Attribute/viewBox) attribute similar to during scroll/pan interactions.
> Scale image in `Plotly.toImage`

- README.md
To account for recent fix found here: https://github.com/browserify/ify-loader/issues/5#issuecomment-330236079
> add minimum ify-loader version to readme

- src/traces/sankey/plot.js
- test/jasmine/tests/sankey_test.js
Fixes https://github.com/plotly/plotly.js/issues/2014
> Sankey default link label

- src/components/legend/draw.js
- src/components/legend/handle_click.js
- test/jasmine/tests/legend_test.js
Legend visibility toggling didn't work at all with `groupby`, which led to mostly a rewrite. By happenstance, it toggled them as a group, which wasn't really the desired behavior. More problematically though, it also threw lots of `Uncaught bad container` errors because it really just wasn't accounted for at all. This PR rewrites legend visibility toggling and tries to preserve existing behavior while fixing `groupby`.
In particular, one tricky case is `legendgroup`, both toggling and isolating:
And the other is `groupby` transforms, both toggling and isolating:
> Rewrite legend visibility toggling

- src/traces/sankey/render.js
- test/jasmine/tests/sankey_test.js
Fixes https://github.com/plotly/plotly.js/issues/2015 (see before/after example there)
Issue found when looking at https://github.com/plotly/plotly.js/issues/2014
Jasmine test produces this DOM tree:
> Sankey: render a thin but visible node even if `value` is very low

- src/traces/sankey/plot.js
Fixes remaining issue of https://github.com/plotly/plotly.js/issues/2014
The fix is that Sankey tooltip positioning be relative to `div.svg-container` rather than `gd`, a difference that's significant if there's a margin specified on (or is effective on) `div.svg-container`.
> Sankey tooltip calc relative to div.svg-container rather than gd

- src/plots/cartesian/axes.js
- src/traces/bar/sieve.js
- src/traces/histogram/calc.js
- test/jasmine/tests/axes_test.js
- test/jasmine/tests/histogram2d_test.js
- test/jasmine/tests/histogram_test.js
Fixes #1978 - some edge cases of single-bin histogram handling
cc @etpinard
> Histogram edge cases

- src/plots/plots.js
- src/transforms/aggregate.js
- test/jasmine/tests/transform_aggregate_test.js
fixes https://github.com/plotly/plotly.js/issues/2024
and adds _index to fullData `aggregation.aggregations` to make back referencing into user data possible.
> Add Aggregation user input _index

- src/traces/bar/calc.js
- src/traces/bar/set_positions.js
- test/jasmine/tests/bar_test.js
fixes #2049 - cleaner handling of base and zero for bar axis autorange.
We don't need to include 0 explicitly in the autorange for bars (unless we're normalizing), nor should we be including the bar base unless that was explicitly specified.
Most of the time these extras were just redundant, but for bars on date axes (which is not really a kosher use of bars but we don't forbid it) the zero (1970) is arbitrary and it's confusing and useless if this gets included in the autorange.
cc @etpinard
> Bar axis autorange fix

- src/components/drawing/index.js
- src/components/fx/hover.js
- src/lib/index.js
- src/traces/bar/hover.js
- src/traces/choropleth/attributes.js
- src/traces/choropleth/hover.js
- src/traces/scatter/fill_hover_text.js
- src/traces/scatter/hover.js
- src/traces/scattercarpet/hover.js
- src/traces/scattergeo/hover.js
- src/traces/scattermapbox/hover.js
- src/traces/scatterternary/hover.js
- test/jasmine/assets/custom_assertions.js
- test/jasmine/tests/carpet_test.js
- test/jasmine/tests/choropleth_test.js
- test/jasmine/tests/drawing_test.js
- test/jasmine/tests/geo_test.js
- test/jasmine/tests/gl2d_click_test.js
- test/jasmine/tests/gl_plot_interact_test.js
- test/jasmine/tests/hover_label_test.js
- test/jasmine/tests/mapbox_test.js
- test/jasmine/tests/pie_test.js
- test/jasmine/tests/scattergeo_test.js
- test/jasmine/tests/scattermapbox_test.js
- test/jasmine/tests/ternary_test.js
fixes https://github.com/plotly/plotly.js/issues/2044 in 0a77239, but really, these few commits here should have been part of https://github.com/plotly/plotly.js/pull/1761. Adding anything hover-related is still a bit of a pain right now. As a lot of logic is scattered around `components/fx`, the base plot and trace modules, things don't _just work_ unfortunately. Manually checking every trace type is in order until we better centralize our hover label logic.
This PR also add a fairly general custom assertion in 4cf489e that checks every part of the hover label DOM nodes. I also caught a few others bug fixed and :lock: in b24759d and 85d7061.
> ArrayOk hoverinfo fixups

- src/traces/table/plot.js
The glitch sometimes occurs when manually stopping a fast mouse wheel scroll in a table with text wrapping that increases cell height - thanks @rreusser for the report!
> Fix for table scroll glitch

- src/traces/parcoords/calc.js
- src/traces/parcoords/parcoords.js
- src/traces/sankey/calc.js
- src/traces/sankey/render.js
More traces to use these simple utils that yield a simple and robust pattern for constructing the scene graph (and wrapping/unwrapping data). I didn't prefix the functions as character count loss wouldn't have improved, so it was a drop-in replacement of preexisting, separate function defs.
> Roll out General Update Pattern utils to `parcoords` and `sankey`

- tasks/util/common.js
Fix formatDate error on `npm start` when system language is Chinese. #1630
> fix Chinese formatDate error on npm start

- src/traces/table/attributes.js
As in https://github.com/plotly/plotly.js/issues/2056
> Reuse font_attributes in `table`

- src/traces/table/data_preparation_helper.js
- src/traces/table/defaults.js
- test/image/mocks/table_latex_multitrace.json
An item in https://github.com/plotly/plotly.js/issues/2056
One mock updated to show its use.
> Allow 1D header in `table`

- src/traces/table/attributes.js
- test/image/mocks/table_latex_multitrace.json
Currently, the JSON spec must have a `line` spec, which is not ideal as it can be supplied with good defaults.
> No default needed for table line

- devtools/test_dashboard/index.html
- src/components/dragelement/index.js
- test/jasmine/tests/dragelement_test.js
`document` keeps getting `mousemove` events even outside the window, until `mouseup`. Who knew?!? Not me anyway... but now that I do, this quick change allows dragging to keep going outside the window. Tested manually in all my local browsers, IE9 - 11 and iOS on Browserstack, and of course the test suites still work (after removing `mouseout` which is no longer part of the interaction).
Two notes:
- I kept `coverSlip` around, because that's an easy way to prevent selecting text as you drag around.
- Some [tips](https://stackoverflow.com/questions/1685326/responding-to-the-onmousemove-event-outside-of-the-browser-window-in-ie) say you need to use `setCapture` / `releaseCapture` in IE, but a) that seems to be older versions than we target, and b) might have been mitigated by `coverSlip` …
> Drag outside window

- src/snapshot/filesaver.js
- src/snapshot/tosvg.js
- test/jasmine/tests/download_test.js
Based off https://github.com/arbscht/plotly.js/pull/1 by @arbscht
Fixes #2063 and possibly #699
@arbscht can you confirm that this produces good output for you - particularly can you verify that a zoomed-in plot is still clipped correctly in the exported SVG?
cc @etpinard @bpostlethwaite
> IE/Edge SVG export fixes

- src/traces/bar/select.js
- src/traces/scatter/select.js
- src/traces/scattergeo/select.js
- src/traces/scattergl/select.js
- src/traces/scattermapbox/select.js
- test/jasmine/tests/select_test.js
Downstream processing expects an array here, even when a trace is not `visible`:
```
var thisSelection = fillSelectionItem(
searchInfo.selectPoints(searchInfo, poly), searchInfo
);
if(selection.length) {
for(var j = 0; j < thisSelection.length; j++) { // <- won't have a length as selectPoints is undefined
selection.push(thisSelection[j]);
}
}
```
(side note: `fillSelectionItem` handles the case of a non-array `selection`, in which case it just passes it on ie. doesn't try to set `curveNumber` etc. properties on `undefined`; the result of which is the same `undefined` as the value of the first arg)
There's a similar `return;` in `scatter`, `scattergeo`, `scattermapbox`.
Is it a good direction @etpinard ?
> Return empty set for invisible bar trace

- src/plots/layout_attributes.js
- src/plots/plots.js
- test/image/mocks/contour_match_edges.json
- test/image/mocks/gl3d_opacity-surface.json
- test/image/mocks/titles-avoid-labels.json
We had a plan a long time ago to support smith charts, but never did.
If/when we decide to do this, it probably won't be implemented with a simple global attribute anyhow.
cc @cldougl
> Remove smith attribute

- src/plots/cartesian/select.js
- src/traces/bar/select.js
- src/traces/choropleth/select.js
- src/traces/scatter/select.js
- src/traces/scattergeo/select.js
- src/traces/scattergl/select.js
- src/traces/scattermapbox/select.js
- test/jasmine/tests/select_test.js
Box select and lasso to work in the presence of an invisible `choropleth` trace. Updated test case signals if the small fix is commented out.
> Selection on `choropleth` to work even if an invisible trace is present

- test/jasmine/tests/select_test.js
Tests are currently failing on [master](https://circleci.com/gh/plotly/plotly.js/5411#tests/containers/1) because PR https://github.com/plotly/plotly.js/pull/2099 got merged on a branch behind https://github.com/plotly/plotly.js/pull/2081 
In detail, the PR #2099 branch didn't have #2081's `addInvisible` utility which messed up the trace indices and lead to a failing test.
@monfera please review.
> Fixup choropleth select test

- src/traces/table/attributes.js
- src/traces/table/data_preparation_helper.js
- src/traces/table/defaults.js
- src/traces/table/index.js
- src/traces/table/plot.js
- test/jasmine/tests/table_test.js
- `restyle` fix was urgent due to https://github.com/plotly/plotly.js/issues/2092
- why not take the opportunity to add jasmine coverage for most of what exists
- tests uncovered misc. special case issues which were fixed
> Improvements to table: `restyle` fix, 0 row/column and misc. fixes; jasmine tests

- src/components/fx/hover.js
- src/traces/contour/attributes.js
- src/traces/contour/defaults.js
- src/traces/heatmap/attributes.js
- src/traces/heatmap/defaults.js
- src/traces/heatmap/hover.js
- test/jasmine/tests/hover_label_test.js
- test/jasmine/tests/select_test.js
Add a `zhoverformat` option to `heatmap` and `contour` traces which specifies the number format to use for displaying `z` values.
> Hoverlabel.zformat

- src/lib/geo_location_utils.js
- test/jasmine/tests/choropleth_test.js
- test/jasmine/tests/scattergeo_test.js
Before, with `locationmode: 'country names'`, non-string locations would throw an error:
```
Uncaught TypeError: Cannot read property 'trim' of null
at countryNameToISO3 (geo_location_utils.js:54)
```
Now they're just ignored silently - as opposed to strings that are unrecognized that generate a console warning. If it's just empty it seems clear you don't even want a warning. I suppose if it's not empty but also not a string it could be nice to still generate a warning, though that's not how most of plotly.js handles invalid data...
cc @etpinard
> harden locationToFeature against non-string country names

- src/transforms/aggregate.js
- src/transforms/filter.js
- src/transforms/helpers.js
- test/jasmine/tests/transform_aggregate_test.js
- test/jasmine/tests/transform_filter_test.js
- test/jasmine/tests/transform_multi_test.js
- generating original points for `transform` results so that, upon interaction such as crossfiltering, the original (constituent) points can be recovered
- cascading these points through a (purportedly) arbitrary sequence of `filter` and `aggregation` steps (`groupby` not yet supported)
- adding test cases for these (also, we didn't have heterogeneous `transforms` testing with both `filter` and `aggregate` in the past)
There's still so much to do (PS: now documented the follow-up issue https://github.com/plotly/plotly.js/issues/2128); eg. more test cases; covering `groupBy` and `sort`. There's plenty of things to iterate on here.
On the pro side, the code change is rather small in terms of lines; also, the logic didn't need to change. So it's an add-on patch rather than anything heavy.
> Transform inverse mapping

- src/traces/contour/defaults.js
- src/traces/contour/style_defaults.js
- src/traces/contourcarpet/defaults.js
- src/traces/heatmap/defaults.js
- src/traces/heatmap/style_defaults.js
- src/traces/histogram2d/attributes.js
- src/traces/histogram2d/defaults.js
- src/traces/histogram2dcontour/attributes.js
- src/traces/histogram2dcontour/defaults.js
- test/jasmine/tests/histogram2d_test.js
- test/jasmine/tests/hover_label_test.js
#2106 interacted with #2113 - still not quite sure why this didn't show up in the tests before but no matter: two more types need `zhoverformat`: `histogram2d` and `histogram2dcontour`. `contourcarpet` would need it as well, but it doesn't support hover at all right now.
Used the opportunity to 🌴  a little bit, moving `zhoverformat` into `contour/style_defaults` and a new `heatmap/style_defaults`
Also short-circuited `supplyDefaults` for `histogram2d(contour)` with no data, as we do for other trace types.
cc @etpinard
> extend zhoverformat to 2d histogram types

- src/components/colorbar/constants.js
- src/components/colorbar/draw.js
- src/traces/choropleth/attributes.js
> Add class to `colorbar`; extract out class names

- package.json
- src/lib/polygon.js
- src/plots/cartesian/dragbox.js
- src/plots/cartesian/select.js
- test/jasmine/tests/select_test.js
> Add multiselect

- src/transforms/groupby.js
- src/transforms/sort.js
- test/jasmine/tests/transform_groupby_test.js
- test/jasmine/tests/transform_sort_test.js
This PR computes @monfera 's brilliant `indexToPoints` map objects (first added in #2126)  for `sort` and `groupby` transforms, in preparation for _transform-compatible_ persistent selections in https://github.com/plotly/plotly.js/pull/2135 - which will use `indexToPoints` heavily :muscle: 
More info of the topic in https://github.com/plotly/plotly.js/issues/2128.
cc @monfera @alexcjohnson
> More indexToPoints 

- build/plotcss.js
- src/css/_notifier.scss
Fixes #2201
Break and hyphenate (in some browsers) long words. Not needed for English, but potentially important for eg German (long compound words?) and maybe asian languages with no spaces between word characters.
Chrome - regular words:
long words:
FF - regular words:
long words:
taken from https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/
but modified: using `word-break`, no matter what I did there would be cases that short words got broken unnecessarily, so I removed it. Also `-moz-hyphens` didn't do anything - which was expected as `hyphens` is supposed to be supported in FF, but I don't ever seem to see hyphens there regardless.
> word breaking in notifier

- src/plots/plots.js
- test/jasmine/tests/plot_promise_test.js
- test/jasmine/tests/plots_test.js
Also `Plots.redrawText` while we're at it - this is the other one in `Plots` that might occasionally need to be called from outside.
cc @etpinard @VeraZab
> allow use of element ID in Plots.resize

- src/components/fx/hover.js
- test/jasmine/tests/box_test.js
- test/jasmine/tests/hover_label_test.js
- test/jasmine/tests/violin_test.js
fixes #527 
@etpinard another quick bugfix for you: Allow hover labels to push out not just to the edges of the subplot but to the edges of the graph div.
There's one downside to this fix: The axis label can get partially covered by point labels in certain extreme cases:
The common label is supposed to say "day 1" and the "1" is mostly covered. If this label were much longer, more of it would be hidden. To my mind this is a good tradeoff, as a) the y labels are usually more important, so it's better to show as many of these as you can, and b) you can always switch to "closest" mode to narrow in on what info is displayed.
> allow hover labels to extend to the edges of the plot

- src/traces/bar/hover.js
- src/traces/bar/set_positions.js
- src/traces/scatter/hover.js
- test/jasmine/tests/hover_label_test.js
Fixes #780 - @etpinard another quick bugfix for you to look at.
Scatter hover was too permissive and too flat in its distance function in compare mode - so it would call the wrong point "closest" sometimes. That was the main culprit in #780, we were matching a scatter point with one x value to a bar with a different x and concluding that they really shouldn't "compare" with each other, so tossing out the bar.
Bar hover was also too restrictive, it would not allow you to be hovered on a bar if the mouse was over the gap between bars. Now in compare mode it allows that, which makes for a more pleasant (and useful) effect as you mouse over, particularly when the bars are very narrow: the hover labels don't flash on/off anymore, there's always one showing.
For both trace types I left …
> scatter & bar hover fixes for #780

- package.json
- tasks/find_locale_strings.js
but we still want to run the rest of the script as it ensures we wrapped all strings
@etpinard as discussed in https://github.com/plotly/plotly.js/pull/2227#discussion_r159028225 so we're not modifying `dist/` when we don't intend to. `build` will still produce a new `translation_keys.txt` file.
> don't write out strings from find_locale_strings during tests

- src/components/annotations/draw.js
- src/components/colorbar/draw.js
- src/components/dragelement/index.js
- src/components/legend/draw.js
- src/components/shapes/draw.js
- src/plots/cartesian/dragbox.js
- src/plots/cartesian/graph_interact.js
- src/plots/cartesian/select.js
- src/plots/geo/geo.js
- src/plots/mapbox/mapbox.js
- src/plots/ternary/ternary.js
- src/traces/pie/plot.js
- test/jasmine/assets/click.js
- test/jasmine/assets/mouse_event.js
- test/jasmine/tests/annotations_test.js
- test/jasmine/tests/click_test.js
- test/jasmine/tests/dragelement_test.js
- test/jasmine/tests/geo_test.js
- test/jasmine/tests/pie_test.js
- test/jasmine/tests/scattermapbox_test.js
- test/jasmine/tests/select_test.js
- test/jasmine/tests/ternary_test.js
fixes #2101 
supersedes #2105 - @AlexVvx I started with your PR, thinking I could just add the right tests to it and be done... unfortunately I found that we had some deeper problems in both the source code and in the tests so it became a much bigger project.
The test problem is that `assets/click` was unrealistic - it generated a sequence of events that's fine for regular clicks, but right clicks and ctrl-clicks (which we were using all over the place to test "modified click behavior", making a bunch of trace types *look* like they supported right-click when they really didn't) take a different pathway, and importantly for some users, it also matters whether the `contextmenu` event is canceled.
The source problem is that we're inconsistent with what we call a click - we have parallel …
> Right click fix

- package.json
- src/plots/gl2d/convert.js
- src/plots/gl2d/scene2d.js
- src/traces/scattergl/select.js
Fixes #2220.
Requires merging https://github.com/gl-vis/gl-plot2d/pull/7 first.
> Gl2d multisubplot fix for 

- src/components/annotations/common_defaults.js
- src/plots/plots.js
@etpinard a quick one, a missing translation I noticed while working on localizing the editor https://github.com/plotly/react-plotly.js-editor/pull/246
> localize "new text"

- lib/locales/es.js
Provided translations for all the keys.
> locales: add Spanish translations

- src/traces/box/calc.js
- src/traces/box/hover.js
- test/jasmine/tests/finance_test.js
fixes https://github.com/plotly/plotly.js/issues/2253
> Candlestick hover label fix

- test/image/strict-d3.js
Fixes #2244 
@monfera you're right, `d3.svg.brush` doesn't work in a way that my idea of disabling the check inside it would work. But here's an alternative: if `d3.event` is truthy then we know we're in a user-initiated event, and so at least within the contexts of our own test systems we know the plot must be visible because the user is interacting with it!
Seem reasonable?
> Allow selection.style getter in event handlers

- src/plots/cartesian/dragbox.js
- test/jasmine/tests/cartesian_interact_test.js
- test/jasmine/tests/click_test.js
- test/jasmine/tests/fx_test.js
fixes #2265 
In #2241 we consolidated click behavior into the drag handler, for cartesian subplots. But this inadvertently disabled click when the drag handler was not attached - ie when there's nothing to drag because you're in zoom or pan mode and all the axes are `fixedrange`!
@dfcreative please take a look!
> Fixedrange click

- src/traces/scatter/link_traces.js
- src/traces/scatter/plot.js
- test/jasmine/tests/scatter_test.js
Fixes #2271 - we were short-circuiting a little too much behavior when no line is generated by a trace.
@dfcreative another quick one to look at, if you would!
> fix ghost fill-tonext when either trace is emptied out

- src/plot_api/plot_api.js
- test/jasmine/tests/gl2d_plot_interact_test.js
Addresses #2282 and https://github.com/ropensci/plotly/pull/1178#issuecomment-359141174.
@alexcjohnson please take a glance.
> Layout resize fix

- package.json
- src/traces/scattergl/index.js
- test/jasmine/tests/gl2d_plot_interact_test.js
This fixes multimarker selection error (@bpostlethwaite discussion) and speeds up entering selection mode (up to ×3 times).
> Speed up selection

- src/plots/plots.js
- test/jasmine/tests/parcoords_test.js
fixes https://github.com/plotly/plotly.js/issues/2228
We already had logic built-in that merge data array container in frame. Previously only one special key was listed ('transforms`), now parcoords `dimensions` is there too.
@monfera would you mind reviewing this thing?
> Add parcoords 'dimension' to list of array containers found in traces

- src/components/colorbar/defaults.js
- src/plots/cartesian/axis_defaults.js
- src/plots/cartesian/tick_label_defaults.js
- src/plots/polar/layout_defaults.js
- src/plots/ternary/layout/axis_defaults.js
- src/traces/carpet/axis_defaults.js
- test/jasmine/tests/axes_test.js
- test/jasmine/tests/polar_test.js
fixes https://github.com/plotly/plotly.js/issues/2317
`visible: false` axes should still support `hoverformat` as demonstrated in the https://github.com/plotly/plotly.js/issues/2317 fiddle. 
To do so, this PR move the `coerce('hoverformat')` out of `handleTickLabelDefaults` -- which does not get called for `visible: false` axes -- to the base axis default handler.
> Coerce hoverformat on visible-false axes

- .circleci/config.yml
- .circleci/test.sh
- test/jasmine/karma.conf.js
- test/jasmine/tests/geo_test.js
- test/jasmine/tests/gl2d_click_test.js
- test/jasmine/tests/gl2d_date_axis_render_test.js
- test/jasmine/tests/gl2d_plot_interact_test.js
- test/jasmine/tests/gl2d_pointcloud_test.js
- test/jasmine/tests/gl2d_scatterplot_contour_test.js
- test/jasmine/tests/gl3d_plot_interact_test.js
- test/jasmine/tests/gl_plot_interact_basic_test.js
- test/jasmine/tests/parcoords_test.js
- test/jasmine/tests/polar_test.js
This PR splits our jasmine test suites (which is getting pretty heavy :hamburger: ) into 2 separate CircleCI jobs: one for our gl3d, gl2d and parcoords tests (tag `@gl`) and another for all the other tests that aren't skipped on CI (that `@noCI` tag).
This does two things:
- speeds up our tests, they now run consistently under 10 minutes
- (hopefully) will help us with our intermittent test failures (gl tests seem to behave better in isolated runs for some reason).
Moreover, the PR removes a few `@noCI` tags from our suites. Upgrading to Chrome 64 in https://github.com/plotly/plotly.js/pull/2323 made some tests work on CI. To note, @monfera almost all your `parcoords` tests are runned on CI now.
cc @alexcjohnson @dfcreative @nicolaskruchten
> Some CI improvements

- src/traces/mesh3d/attributes.js
- src/traces/mesh3d/convert.js
- src/traces/mesh3d/defaults.js
- src/traces/scatter3d/attributes.js
- src/traces/surface/attributes.js
- src/traces/surface/convert.js
- test/jasmine/tests/gl3d_plot_interact_test.js
Call this a bug fix or a new feature, this PR closes https://github.com/plotly/plotly.js/issues/2242
> Add support for (hover) 'text' in mesh3d traces

- src/components/fx/hover.js
- src/components/modebar/buttons.js
- src/components/modebar/manage.js
- src/plots/ternary/ternary.js
- test/image/strict-d3.js
- test/jasmine/tests/gl3d_plot_interact_test.js
- test/jasmine/tests/hover_label_test.js
- test/jasmine/tests/modebar_test.js
- test/jasmine/tests/ternary_test.js
fixes https://github.com/plotly/plotly.js/issues/2338
Not 100% sure how to test this. There's probably a way to add a check in `d3-strict`? But maybe just a jasmine test that doesn't fail would do the trick.
> Negate axis offset and then turn it into a string

- src/components/errorbars/compute_error.js
- src/components/errorbars/defaults.js
- src/components/errorbars/plot.js
- test/image/mocks/basic_error_bar.json
- test/jasmine/tests/errorbars_test.js
- test/jasmine/tests/plot_api_test.js
Noticed this morning during a discussion with @VeraZab - error bars still filled in `[]` during `supplyDefaults`. When fixing that I also noticed that we weren't allowing uneven `array`/`arrayminus`, not a big deal but if you're doing manual data entry it would be nice to see the two halves of the errorbar show up independently. Ideally this would also remove the cap from the missing end of the bar, as I have it here it just sets the missing end to zero length so that the cap shows up on top of the data point; if anyone can think of a use case for this as a final state of the plot (as opposed to an intermediate state while you're typing the rest of the data) I'd be happy to extend it to omit that cap but if not it seemed like unnecessary extra complexity.
> fix errorbars for Plotly.react and for uneven data arrays

- src/components/annotations/draw.js
- test/jasmine/tests/annotations_test.js
fixes https://github.com/plotly/plotly.js/issues/2363
> Fix edits for date-string referenced annotations

- src/lib/relink_private.js
- src/plots/attributes.js
- tasks/util/make_schema.js
- test/jasmine/tests/lib_test.js
@etpinard a quick change to improve update performance with complicated `customdata`
> Relink less stuff

- .circleci/test.sh
- test/jasmine/tests/animate_test.js
- test/jasmine/tests/gl2d_plot_interact_test.js
- test/jasmine/tests/parcoords_test.js
- test/jasmine/tests/select_test.js
Splitting the jasmine tests into two CI jobs did help alleviate some of our intermittent test failures, but these still happen in about 1 run out of 2.
As Circle CI 2.0 doesn't have an _auto-retry_ setting [yet](https://discuss.circleci.com/t/auto-retry-failed-builds/18611), we currently have to painfully navigate the CircleCI UI to restart our failed jobs. This is of course a waste time. So, I propose this in-house solution.
@alexcjohnson @dfcreative what do you think?
> Auto-retry jasmine test on CI

- test/jasmine/tests/parcoords_test.js
@etpinard this seems to make `parcoords_test` pass reliably - and I can even take out the `@flaky` tag I added in #2399. (I did get a gl2d failure in one of these runs though... https://circleci.com/gh/plotly/plotly.js/7227)
I seem to recall trying to add `Plotly.purge` directly to `destroyGraphDiv` once before, and running into problems that looked like I was purging after the next test case had already started... anyway that's why I added the `delay(50)().then(done)`, and if that's really required it doesn't seem like a good idea to add it to *every* `destroyGraphDiv` - though perhaps we can make this into a variant just for use with gl tests? Or maybe we can detect gl contexts and only purge/delay if we find one?
A little more detail on my investigations:
- Even when the tests failed …
> Plotly.purge in parcoords_test

- src/plots/cartesian/axes.js
- src/traces/histogram/calc.js
- test/jasmine/tests/axes_test.js
- test/jasmine/tests/histogram2d_test.js
- test/jasmine/tests/histogram_test.js
Fixes #2393 - this bug was actually introduced with #2028 fixing some other histogram edge cases. But in that fix I accidentally conflated single-value (which should use the special logic added there to readjust bins) and single-bin (which can result from `Axes.autoBin` even with multiple distinct values in the data array). This special logic is only triggered with `barmode: 'overlay'` which is why that's all I tested here; it already worked correctly in any other `barmode`.
cc @etpinard
> Fix yet another histogram edge case

- src/plots/cartesian/axes.js
- src/traces/carpet/calc_gridlines.js
- src/traces/contour/plot.js
- test/jasmine/tests/contour_test.js
Fixes #2398 - the test case I added is the simplest distillation of the plot in the initial report.
Also: I broke up `Axes.calcTicks` -> new `prepTicks` only finishes setting up the axis object (`tick0`, `dtick`, `_tickround`, and `_tickexponent` - all the things `Axes.tickText` will need), but does not actually calculate all the ticks. This is potentially a noticeable improvement for constraint-type contours, where I set an arbitrarily large `nticks` merely to ensure we get a reasonable number of digits of precision. Carpet can take advantage of this as well in one place.
cc @etpinard
> fall back for contour labels when there's only one contour

- src/traces/bar/hover.js
- src/traces/bar/set_positions.js
- test/jasmine/tests/bar_test.js
Fixes #2350 
Adds an extra step to `Bar.setPositions` to record the position extent of each bar group, which includes two loops over the data: one to find the min and max position of the trace group, and a second to calculate the extents. I did it this way because calculating this on the fly in `hoverPoints` is fairly awkward, you either have to loop over traces once for each trace (repetitious) or you could modify the hover data after finishing `hoverPoints`, manipulating all the bar traces in the hover data to match their position axis coordinates (adding type-dependent logic to `Fx.hover` directly)... this way seemed cleaner. There may be ways to move some of these calculations into existing loops in `setPositions` but the way these are set up this seems like it would entail a lot of …
> push hover labels in to the bar group extent in compare mode

- src/plot_api/subroutines.js
- src/plots/cartesian/index.js
- test/jasmine/tests/cartesian_test.js
Fixes #2410 - hide axis lines that have been removed - this one was straightforward, just needed to move the path attr setter out to where it's always called
Fixes #2392 - this one is a bit more complicated, it's hard to figure out a reasonable d3-idiomatic way to do this because it's not obvious where the axis objects that we need to remove had been created in the first place, ie independent or overlaying some other axis. In principle we should refactor the d3 data for drawing axes to reflect this structure, but for now I just added some more explicit cleanup code.
cc @etpinard @nicolaskruchten
> Clean up removed axes and axis lines

- src/plots/cartesian/axes.js
- test/jasmine/tests/hover_label_test.js
Fixes #2420 - #2106 improved formatting here but broke the default behavior for z values that need exponents. Fortunately the fix was a one-liner.
cc @etpinard
> Z exponent fix

- src/components/dragelement/index.js
- src/components/legend/constants.js
- src/components/legend/draw.js
- test/jasmine/tests/legend_scroll_test.js
Fixes #2387 - don't allow dragging from the scroll box of a legend, only from the scroll bar itself, and even then not on right clicks, only left click. I also made the scroll bar handle a little bit wider so it's a bit easier to grab. And another part of the issue is that the scrollbar would jump to be centered on the mouse cursor, rather than simply moving with it from wherever you grabbed it. I fixed that too.
Fixes the legend part of #1859 - makes the scrollbar scale to show the fraction of the legend that's visible.
cc @etpinard
> Legend scroll fix

- src/components/fx/hover.js
- test/jasmine/tests/hover_label_test.js
This fixes #2154: when hover info (aka tooltip) is rendered in the center due to a lack of space left or right, the text overflowed the box and the secondary hove info (trace name) was hidden underneath the primary one.
Final solution:
Hint: part of the discussion took place in https://github.com/rmoestl/plotly.js/pull/1.
> Fix layout of centered hover info #2154

- src/components/fx/hover.js
- test/jasmine/tests/hover_label_test.js
This fixes #865: boxes of multiple centered hover info elements had all the same vertical position, hence hiding each other and not "following" associated text labels in terms of positioning.
Final solution:
> Fix stacking of centered hover info elements #865

- src/plots/polar/polar.js
- src/traces/scatterpolar/calc.js
- test/jasmine/tests/polar_test.js
fixes https://github.com/plotly/plotly.js/issues/2421
- :hocho: useless axex.expand call in scatterpolar/calc, this is an artefact from an earlier angular dates attempt
- set mocked angular axis range using max of set 'period' and total categories length.
- more on period vs category limitations and possible improvements in #2255 
> Fix category angular axis mocked range logic

- package-lock.json
- package.json
- tasks/bundle.js
- tasks/util/browserify_wrapper.js
A nice benefit from removing all circular deps in https://github.com/plotly/plotly.js/pull/2429, [`browser-pack-flat`](https://github.com/goto-bus-stop/browser-pack-flat) now allows us to trim some bundle bits (especially in our minified bundle). 
Here's what `browser-pack-flat` can trim:
that's about 10 gzip+minified `kB` per bundle. Not bad I think.
**That said**, using `browser-pack-flat` comes at a price :moneybag: , `npm run build` is not a bit slower and consumes a lot more memory. So I had to use [`run-series`](https://github.com/feross/run-series) to reduce memory consumption and make `npm run build` succeed consistently. Note also, I thinking of only using `browser-pack-flat` during `npm run build` to not slow `npm run watch` and `npm start`.
------------------
Referencing …
> Bundle with browser-pack-flat plugin

- src/plots/cartesian/axes.js
- test/jasmine/tests/axes_test.js
@etpinard a quick one I noticed while perusing old issues.
> fix #1645 - ensure we don't draw ticks if there are none to draw

- src/plots/cartesian/index.js
- src/traces/scattergl/index.js
- test/jasmine/tests/cartesian_test.js
- test/jasmine/tests/gl2d_plot_interact_test.js
We have special logic for when scatter and scattergl modules are removed from the plot, and it was broken.
cc @etpinard
> fix #2452 - removing and adding scatter(gl) as not the first module

- src/plots/cartesian/axes.js
@etpinard I *think* this will fix #2456 but not quite sure how to test it since everything looks fine in the dashboard... I guess using flat-pack in our tests - jasmine? image?
> Polar + flat-pack

- test/jasmine/assets/mouse_event.js
...when we try to emit a mouse event, which the browser may ignore if it's hidden
@etpinard this would have alerted me a bit quicker yesterday why my tests were failing sporadically 😅 
```
Error: document.visibilityState = "hidden" - Please make the window visible.
```
> throw an error if the test window is hidden

- tasks/cibundle.js
Probably not the greatest way to test those unfortunate `browser-pack-flat` hiccups, but oh well running our image tests with a pack-flat bundle would have been enough to catch https://github.com/plotly/plotly.js/issues/2456. This adds about 1 minute to our total test time on CI unfortunately (`browser-pack-flat` is kinda slow :turtle: ). I think this is an ok compromise for now. Thoughts?
--------
Some info from my investigations:
- I didn't find any issues (other than https://github.com/plotly/plotly.js/issues/2456.) by flipping through the docs page
- With the current master and a `browser-pack-flat` bundle, all image tests are passing
- Running the jasmine tests with `browser-pack-flat` with the current configuration isn't viable. It takes [more than 10 minutes to bundle plotly and …
> Bundle with pack-flat on ci

- src/plot_api/plot_api.js
- src/plots/cartesian/index.js
- test/jasmine/tests/plot_api_test.js
Fixes #2462
The problem was that `_axisConstraintGroups` gets reset in cartesian-only code, so with no cartesian module, the old one just gets added back in by `relinkPrivateKeys`. So I cleaned that up, but also realized that without cartesian we don't even need to do some of the steps in `Plotly.plot` (including the one that errored) 🐎 In fact either one of those would have been enough to fix this bug, but I figured both can't hurt.
@etpinard we should really rethink `relinkPrivateKeys` - can we perhaps figure out which keys we really *need* to relink, and give them some stronger marker than just the generic underscore, which also means private, not an attribute? There are probably other keys that can cause similar problems...
> Clean up constraint groups

- src/lib/svg_text_utils.js
- test/jasmine/tests/svg_text_utils_test.js
Fixes #2239.
Bug description: an already escaped URI of an HTML link was encoded a second time by Plotly which led to a wrong URI.
> Handle HTML links with encoded URIs correctly in svg text labels #2239

- src/plots/cartesian/attributes.js
> fixed typo

- src/plot_api/plot_api.js
- src/plot_api/subroutines.js
- src/plots/cartesian/axes.js
to be more merged in https://github.com/plotly/plotly.js/pull/2474 
In progress for now, as I'll try to speed up a few more things in the coming days.
> More optimization for cartesian subplots

- src/components/colorbar/draw.js
- src/components/drawing/index.js
- src/components/fx/hover.js
- src/components/legend/draw.js
- src/components/legend/style.js
- src/components/rangeselector/draw.js
- src/components/rangeslider/draw.js
- src/components/sliders/draw.js
- src/components/titles/index.js
- src/components/updatemenus/draw.js
- src/lib/index.js
- src/plot_api/plot_api.js
- src/plot_api/subroutines.js
- src/plots/cartesian/axes.js
- src/plots/cartesian/dragbox.js
- src/plots/cartesian/index.js
- src/plots/plots.js
- src/plots/ternary/ternary.js
- src/traces/carpet/plot.js
- src/traces/contour/plot.js
- src/traces/contourcarpet/plot.js
- src/traces/pie/plot.js
- test/jasmine/assets/custom_matchers.js
- test/jasmine/tests/cartesian_test.js
- test/jasmine/tests/click_test.js
- test/jasmine/tests/drawing_test.js
- test/jasmine/tests/plot_api_test.js
- test/jasmine/tests/plot_interact_test.js
Here are two perf commits in `Cartesian.drawFramework` that will help splom subplot generation. :racehorse: 
At 400 subplots (or 20 splom dimensions :smirk: ), these commits are able to speed up `drawFramework` from ~1000ms down under 200ms.
Note that it might be nice to make the new `joinLayer` from 7d881f6 a standard `Lib` function and replace all our `selectAll().data([0])` with it. Waiting on @alexcjohnson before going through with it.
> Perf drawFramwork

- src/traces/scattermapbox/select.js
- test/jasmine/tests/select_test.js
> fixes #2512 - skip over BADNUM lonlat in scattermapbox select

- src/plots/cartesian/index.js
- test/jasmine/tests/cartesian_test.js
Fixes #2509 - and probably various other bugs resulting from the fact that `mainplot` wasn't cleared when a previously overlaid subplot became independent.
cc @etpinard
> fix plotinfo when mainplot is no longer linked

- src/traces/box/plot.js
- test/jasmine/tests/box_test.js
A quick one @etpinard 
Test case straight from @yniknafs report 🎉
> fix #2529 - box plot with one jittered outlier

- CONTRIBUTING.md
Follow-up from the discussion in PR #2506, add documentation to help orient developers in the selection coordinate system.
> Add tips for writing selection tests

- src/components/legend/draw.js
- src/lib/svg_text_utils.js
- src/transforms/groupby.js
- test/jasmine/tests/legend_test.js
Fixes #2576 
- In editable mode, pads all blank or short legend items out to the length of the longest one (or 4 characters at least) - note this is the character length, not the svg text length which will usually be shorter.
- `groupby` and regular traces work the same now - deleting the value completely leaves it blank, rather than reverting to the default like `groupby` had been doing.
cc @etpinard
> Blank editable legend item fixes

- src/components/fx/hover.js
- tasks/test_syntax.js
Fixes #2588 
`evt.offset(X|Y)` isn't implemented consistently in Firefox vs other browsers. Stopped using it and blacklisted it as a property.
The little offset I saw in Chrome https://github.com/plotly/plotly.js/issues/2588#issuecomment-385072182 seems to be a weird interaction of Chrome and my second monitor (non-retina, vs. the laptop's retina monitor which does not show this offset) that shows up even in bare `mouseover` events, so doesn't seem like we can fix that.
cc @etpinard
> fix spikesnap: cursor in FF

- src/components/modebar/modebar.js
- test/jasmine/tests/localize_test.js
Fixes #2484 
@etpinard another quick one I didn't quite finish on bug day :) 
FWIW it fixes not only the encouraged usage (`Plotly.react`) but also the old `Plotly.plot` call with new `config`.
> Update modebar buttons when locale changes

- src/plot_api/plot_api.js
- test/jasmine/tests/plot_api_test.js
Fixes #2602 - not sure how this worked before #2577 but it must have. And I'm kind of amazed that we didn't have an add/remove traces test for `Plotly.react` before... oh well, now we do!
cc @etpinard
> Fix Plotly.react add/remove traces bug

- src/components/modebar/buttons.js
- src/plot_api/plot_config.js
- test/jasmine/tests/modebar_test.js
This PR allows for selective overriding of default behaviour of the `toImage` modebar button. Specifying nothing falls through to the current defaults. Note sure about the implications of renaming the button, wrt to locale files.
> Override toImage modebar button opts via config

- src/components/drawing/index.js
- src/plots/cartesian/dragbox.js
- src/plots/cartesian/index.js
- src/plots/cartesian/transition_axes.js
- src/traces/bar/index.js
- src/traces/box/index.js
- src/traces/scatter/index.js
- src/traces/scattercarpet/index.js
- src/traces/violin/index.js
resolves #2548 (there's still room for improvement, but it's enough to close that ticket for now I think).
In brief this PR:
- makes pan/scroll go through the "inverse scale" per-point loop only when needed. This loop updates the `transform` attr of every point on every mousemove to counteract the scale of trace group during pan/scroll. It turns out that can be extremely costly on graphs with many pts and even more costly for text nodes.
- stashes "hot" svg selections that are used during pan and scrolled to update the view w/o going through a relayout. Note that `plots/cartersian/dragbox.js` is now free of (potentially) slow `selectAll` calls!
- updates optimization flags `hasSVG`, `hasScattergl` and friends only on mousedown instead of on every mousemove.
Taking …
> Faster svg pan

- README.md
Adding this button to the top of the README gives a quick visual indication of the license type.
> Add MIT License button from shields.io

- lib/locales/it.js
Italian translation for plotly. Not complete (yet)
> Italian translation

- src/components/grid/index.js
- test/jasmine/tests/plots_test.js
cc @etpinard a quick one - the key is attaching `gridOut` to `layoutOut` after [this short-circuit return](https://github.com/plotly/plotly.js/blob/2d84a8fba7aa27f36ff3c61e0e07616ab12cfd66/src/components/grid/index.js#L213)
> fix #2633 - make sure we have a grid before attaching it to layoutOut

- src/traces/violin/calc.js
The following code will crash your browser:
<details>
<html>
<head>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>
<body>
<div id="chart"></div>
</body>
<script>
var traces = [
{
'bandwidth':0.33643595519279684,
'box': {
'visible': false,
},
'boxpoints': false,
'meanline': {
'visible': true,
},
'name': 'test',
'points': false,
'showlegend': false,
'type': 'violin',
'y': [
2.4403208885500003e-7,
6.624100740240001e-8,
8.164963286729999e-8,
0.00000550607937631,
3.02033017347e-8,
3.7801716937800004e-7,
5.56297659998e-8,
5.406555702509999e-8,
3.31213740697e-8,
1.0835987313399999e-7,
3.19669534548e-7,
2.8017014902900004e-8,
2.4514782933900002e-8,
5.95554346643e-7,
4.70654584492e-8,
2.3361313822699997e-11,
3.06469187871e-7,
2.07771831308e-8,
5.04663715295e-8, …
> use supplied bandwidth if provided

- src/traces/parcoords/lines.js
Related to recent safari null-buffer fixes. Also may facilitate with #2582
> Add null-data buffer fix for parcoords

- BUILDING.md
- README.md
- tasks/test_syntax.js
For centralized and complete building instructions to eventually cover :sparkles:  all :sparkles: build frameworks.
This PR uses commits from @TomDemulierChevret's https://github.com/plotly/plotly.js/pull/2260/
> Add Building.md

- src/traces/contourcarpet/calc.js
- src/traces/heatmap/calc.js
- src/traces/heatmap/interp2d.js
- test/jasmine/tests/contour_test.js
- test/jasmine/tests/heatmap_test.js
Fixes #2652 - turns out this isn't a react-specific issue, it's just about changing z data for contours with gaps in the data (and heatmaps with `connectgaps: true`). We were caching the interpolation results, even across recalc calls, because this can be a pretty slow (iterative) process. I removed that cache, after first trying to figure out whether we could salvage it, based on comparing the incoming known (non-interpolated) z values to the old ones. It turned out that was difficult (and expensive) to get right, especially for edge cases like removing a previously filled-in value without changing anything else.
We're doing a better job than we used to do (3+ years ago when this cache was added) at avoiding unnecessary recalcs, so I don't think this should be too big a cost, but this is …
> remove cached `trace._interpz` from heatmaps/contour maps with gaps

- src/lib/prepare_regl.js
- test/jasmine/tests/gl2d_plot_interact_test.js
- test/jasmine/tests/parcoords_test.js
As described in https://github.com/plotly/plotly.js/issues/2614, starting in version 1.36.0 all regl based graphs created 3 WebGL contexts (one for each [canvas layer](https://github.com/plotly/plotly.js/blob/dfb56d3a7b99ecf979365ed9b9c2c40747cdd915/src/plot_api/plot_api.js#L212-L224)). But one of these layer (the _pick_ layer) is only used in parcoords traces, so we can create two contexts instead of three on scattergl and splom graphs. 
Why did this happen? I got sloppy in commit https://github.com/plotly/plotly.js/pull/2505/commits/469e4cdb2a045d57ca5e062cd01444a3756f5fd0 where I failed to bring [this `d.pick` check](https://github.com/plotly/plotly.js/commit/469e4cdb2a045d57ca5e062cd01444a3756f5fd0#diff-e03c5a2a46f9392088513c32645ea9d5L341) into `prepareRegl`.
Reducing the number of …
> Create two (not three) WebGL contexts for scattergl/splom graphs

- src/plots/cartesian/dragbox.js
- test/jasmine/tests/select_test.js
Commit https://github.com/plotly/plotly.js/commit/20820cb70c4879c91e8ade621c829f1b5ac4c069 fixes https://github.com/plotly/plotly.js/issues/2667 which has been broken since https://github.com/plotly/plotly.js/pull/2527/commits/bb022818e7fe6c2c808ad440a633558398853325 (from one of the splom perf PRs) where drag handlers are no-longer reintialized when relayout'ing `dragmode`.
> Fix select <-> pan double-click behavior

- src/plots/cartesian/dragbox.js
- test/jasmine/assets/custom_matchers.js
- test/jasmine/tests/select_test.js
Fixes https://github.com/plotly/plotly.js/issues/2669
before:
now:
> Fix shift selection after pan

- src/traces/bar/plot.js
- test/jasmine/tests/bar_test.js
fixes https://github.com/plotly/plotly.js/issues/2688 which was a regression since commit https://github.com/plotly/plotly.js/pull/2574/commits/6d88255bc76ce8b0a7b6c1a90ec00fb5886d6227 where all `Bar` started using a d3-iomatic update pattern.
> Fixup bartext removal in update selections

- src/traces/scatter3d/convert.js
- test/jasmine/tests/gl3d_plot_interact_test.js
Easy fix cc @alexcjohnson 
But: wow, I wish hover from subplot type to another other would be done in a DRYer way :tired_face:
> Fix scatter3d scalar hovertext handling

- src/lib/prepare_regl.js
- src/lib/show_no_webgl_msg.js
- src/plots/gl2d/scene2d.js
- src/plots/gl3d/scene.js
- src/plots/plots.js
- src/traces/parcoords/plot.js
- src/traces/scattergl/index.js
- src/traces/splom/base_plot.js
- test/jasmine/bundle_tests/no_webgl_test.js
- test/jasmine/karma.conf.js
fixes https://github.com/plotly/plotly.js/issues/2665 (the fail _gracefully_ part) and https://github.com/plotly/plotly.js/issues/2666 (the missing message part).
Most importantly, I found a pretty solid way to test no-webgl environments. Adding a `--disable-webgl`  flag to the Chrome CLI in our Karma config did the trick.
@alexcjohnson @nicolaskruchten
> Make all gl traces show "no webgl message" and fail gracefully

- src/traces/scatter/line_points.js
- test/jasmine/tests/scatter_test.js
Fixes #2664 - the problem was the increasing decimation tolerance as points get farther from the viewport - if a *segment* crosses the viewport we need to use the on-screen (minimum) tolerance even though points on both sides are far enough away to get a high tolerance. Adds a little extra calculation into the decimation algorithm unfortunately, but I don't think it's too big a hit (nor do I see any higher-performance alternative).
cc @etpinard
> fix line decimation for segments crossing the viewport

- package-lock.json
- package.json
PR https://github.com/regl-project/regl/pull/479 merged in several browser-dependent fixes to regl (that we used for scattergl, splom and parcoords traces). 
This PR doesn't resolve any open plotly.js issue, but might fix a few unreported browser-dependent issues.
cc @dy
> Bump regl to 1.3.6

- src/traces/histogram/calc.js
- test/jasmine/tests/histogram_test.js
@etpinard a quick one to fix #2722
> fix #2722 - get the right traces in hist calc for cross-trace coupling

- src/plots/mapbox/layers.js
- test/jasmine/tests/mapbox_test.js
- when a new source is given, remove layer, update source and add new layer in that order to avoid mapbox-gl errors.
Some more info about how mapbox layout layers are updated:
These are the available update pathways:
https://github.com/plotly/plotly.js/blob/27c77c11f2eab9cf773543926938743d2eb2b0fc/src/plots/mapbox/layers.js#L35-L51
where `needsNewSource` is fairly dumb (but fast):
https://github.com/plotly/plotly.js/blob/27c77c11f2eab9cf773543926938743d2eb2b0fc/src/plots/mapbox/layers.js#L53-L62
which explains why 
```js
// new source object on each react
function makeFigure() {
return {
// ...
layout: {
mapbox: {
layers: [{source: {/**/}}]
}
}
}
}
Plotly.react(gd, makeFigure())
Plotly.react(gd, makeFigure())
```
can behave differently than
```js
// same source object
var source = {/* */} …
```
> Fix mapbox layout layer updates

- src/plots/plots.js
- test/jasmine/tests/plot_promise_test.js
While working with `plotly` & `react-plotly`, from time to time I could notice minor error in my console:
```
Uncaught TypeError: Cannot read property 'width' of undefined
```
First, I thought the error is somewhere on my side but later it was clear it was inside `plotly` library. I backtracked the error and ended up here:
```js
if(gd.layout.width && gd.layout.height)
```
=> https://github.com/plotly/plotly.js/blob/master/src/plots/plots.js#L75-L113
Reproducing it was possible by changing my routes faster than usual – not waiting for plotly to finish rendering charts – chaos monkey style. Apparently when you delete DOM node from your HTML, `gd` variables still holds the reference to the element which doesn't exist anymore. In that case if you try to call `gd.layout.width/height` it will …
> Plots.resize - additional check for gd.layout

- src/lib/dates.js
- test/jasmine/tests/lib_date_test.js
cc @etpinard - the test is somewhat circular, I don't really see a way around this though.
> Fix #2743 - old date timezone precision in Chrome 67+

- src/plots/plots.js
- test/jasmine/tests/plots_test.js
fixes https://github.com/plotly/plotly.js/issues/2663 (aka the react-plotly.js issue that resulted in negative svg mesures)
There's probably a _better_ fix out there, but our autosize logic is such a mess that I was happy with this here. I hope @alexcjohnson will agree.
> Sanitize margin after 'autosize' relayouts

- src/plot_api/plot_config.js
- src/plots/plots.js
- test/jasmine/tests/config_test.js
Fixes https://github.com/plotly/plotly.js/issues/2759#issuecomment-400776193
I haven't tested this.
> Add `plotlyServerUrl` to `baseUrl`

- src/components/drawing/index.js
- src/plots/mapbox/mapbox.js
- src/traces/scattermapbox/defaults.js
- test/jasmine/tests/mapbox_test.js
- test/jasmine/tests/scattermapbox_test.js
fixes https://github.com/plotly/plotly.js/issues/2742
This PR:
- fixes mocked plotly_relayout event data on mapbox interactions
- make mapbox subplot emit plotly_relayout (w/ mocked evt data) on double click
> Fix mapbox interaction inconsistencies

- src/plots/cartesian/dragbox.js
- test/jasmine/tests/cartesian_interact_test.js
fixes https://github.com/plotly/plotly.js/issues/2748
Now zooming on `12.json` with `Plotly.relayout(gd,'xaxis.fixedrange',true)` gives
> Fix x-only zoom moves when `xaxis.fixedrange: true`

- src/plot_api/plot_api.js
- src/plot_api/subroutines.js
- src/plots/plots.js
- test/jasmine/tests/plot_api_test.js
resolves https://github.com/plotly/plotly.js/issues/2740 and more precisely implements https://github.com/plotly/plotly.js/issues/2740#issuecomment-398198401 where we make `plotly_afterplot` fire after every edit type.
I'm not super proud of commit https://github.com/plotly/plotly.js/commit/cb92d7c31cb6bd27a57e2c88a2404c0d7faa5c31, but please consider this a 'temporary' fix until we improve the automargin pipeline as discussed in #2704
> Emit 'plotly_afterplot' on all edits

- src/traces/violin/calc.js
- test/jasmine/tests/violin_test.js
> Fix bandwidth for single-value violins

- package-lock.json
- package.json
- src/traces/scattergl/index.js
The `orca graph` command in `tasks/noci_test.sh` is broken at the moment on master. Commit https://github.com/a-vis/gl-text/commit/0205af86cec209b92ddda6fd2dc25d6648055f01 fixes the broken. By the way, orca produces very crisp scattergl text baselines :tada:  
I promised 1.39.0 will be out today and because of https://github.com/a-vis/gl-text/issues/1, I need to do this stupid thing. cc @dy
> Use @etpinard/gl-text

- src/traces/box/plot.js
- src/traces/violin/plot.js
- src/traces/violin/style.js
- test/jasmine/tests/box_test.js
- test/jasmine/tests/violin_test.js
fixes https://github.com/plotly/plotly.js/issues/2777 and a bunch of other restyle/react bugs introduced in https://github.com/plotly/plotly.js/pull/2579, where the box and violin meanlines and points d3-data-binds assume a clean parent `<g>` and didn't care about clearing parts that should no longer be visible.
cc @alexcjohnson @dmt0
> Fix box & violin inner parts removal

- tasks/bundle.js
- tasks/cibundle.js
- tasks/util/constants.js
a very unfortunate fix to https://github.com/plotly/plotly.js/issues/2787, we have a bunch of additional bytes, but at-least mapbox-gl is working.
cc @alexcjohnson 
Does anyone know a way to skip uglify-js (-es, terser or other uglify-js folks) the `compress` step on only selected files? cc @dy
> Set minify option 'compress' to false to fix mapbox-gl minification

- src/traces/scattergl/index.js
- test/jasmine/tests/gl2d_click_test.js
fixes #2731 
Such that after relayout edits that do not trigger a recalc, selection can properly clear the canvas.
cc @alexcjohnson @dy
> Use updated fullLayout._size in scene.clear

- src/plots/plots.js
- test/jasmine/tests/transform_filter_test.js
- test/jasmine/tests/transform_multi_test.js
fixes https://github.com/plotly/plotly.js/issues/2786
cc @alexcjohnson @dmt0
> Transform removal from react fix

- src/plot_api/plot_api.js
- test/jasmine/tests/gl2d_plot_interact_test.js
Fixes https://github.com/plotly/plotly.js/issues/2791
Some edits may call `makePlotFramework` in plot_api.js, we can't clear the ref to glcanvas there as we need to properly clear the canvases.
cc @alexcjohnson @dy
> Do not clear _glcanvas ref during layout replot edits

- src/css/_base.scss
plotly breaks when inserted in a documented with RTL direction
as can be seen here :
> fix: tooltip misplaced in RTL documents

- src/plots/geo/zoom.js
- test/jasmine/tests/geo_test.js
fixes https://github.com/plotly/plotly.js/issues/2809
@alexcjohnson some d3.geo projections return `undefined` when trying to map outside-subplot x/y px values to lon/lat.
> Guard against undefined projection.invert results 

- src/traces/scatter/line_points.js
- test/jasmine/tests/scatter_test.js
resolves https://github.com/plotly/plotly.js/issues/2794 by allowing smooth transitions of lines with the same number of coordinates:
> Do not collapse duplicate end points when `line.simplify: false`

- src/plot_api/subroutines.js
- src/plots/cartesian/axes.js
- src/plots/cartesian/graph_interact.js
- src/plots/cartesian/index.js
- src/plots/plots.js
- test/jasmine/tests/cartesian_test.js
- test/jasmine/tests/splom_test.js
fixes https://github.com/plotly/plotly.js/issues/2828 and moves a few "clean up old layer" blocks out of `Plots.supplyDefaults` and into `Cartesian.drawFramework` (cc https://github.com/plotly/plotly.js/issues/2549).
cc @alexcjohnson @nicolaskruchten
> Fix overlaying subplot configuration relayouts

- src/components/legend/draw.js
- test/jasmine/tests/legend_test.js
fixes https://github.com/plotly/plotly.js/issues/2819, an edge case that made 
https://github.com/plotly/plotly.js/blob/0426b61b9a6034b73adca10970923d8ced6cc71b/src/components/legend/draw.js#L343-L354
not grab the correct legend item bounding boxes when `edits.legendPosition` was turned on. 
> Position-editable horizontal legend toggle fixups

- src/plots/cartesian/set_convert.js
- test/jasmine/tests/axes_test.js
@etpinard a quick one while looking over old bug reports
> fix #1363 - honor tenths of milliseconds in old numeric date data

- src/components/annotations/attributes.js
- src/components/annotations/calc_autorange.js
- src/components/annotations/draw.js
- src/components/rangeslider/defaults.js
- src/components/shapes/attributes.js
- src/plot_api/edit_types.js
- src/plot_api/plot_api.js
- src/plots/cartesian/autorange.js
- src/plots/cartesian/axis_defaults.js
- src/plots/cartesian/layout_attributes.js
- src/traces/box/attributes.js
- src/traces/ohlc/attributes.js
- src/traces/scatter/attributes.js
- src/traces/scatter/calc.js
- test/jasmine/tests/annotations_test.js
- test/jasmine/tests/axes_test.js
- test/jasmine/tests/box_test.js
- test/jasmine/tests/finance_test.js
- test/jasmine/tests/gl2d_click_test.js
- test/jasmine/tests/gl2d_pointcloud_test.js
- test/jasmine/tests/plot_api_test.js
- test/jasmine/tests/scatter_test.js
- test/jasmine/tests/shapes_test.js
resolves https://github.com/plotly/plotly.js/issues/2546 and brings cartesian axis autorange relayout calls (e.g. on-plot-area double-click or the "autoscale" mode bar button) to perform to a level comparable to axis range relayout calls (e.g zoom in/out).
In brief, cartesian `axis.autorange` is now declared as `editType: 'axrange'` and edit type 'calcIfAutorange' is gone.
As mentioned in https://github.com/plotly/plotly.js/issues/2546#issuecomment-405388288, adapting the update pathway ended up being a little trickier than I'd imagine (especially for annotations, see https://github.com/plotly/plotly.js/commit/a8fb653ddca6dd00407b4362131ba2ceb3e6d511). But I'm pretty please with the results: a lot of old delicate "find-autoranged-axes" logic in restyle, relayout and react is gone (see …
> Faster axis autorange + remove calcIfAutorange edit type

- src/plot_api/plot_api.js
- src/plots/plots.js
- src/traces/pie/calc.js
- src/traces/pie/index.js
- src/traces/pie/layout_attributes.js
- src/traces/pie/layout_defaults.js
- test/jasmine/tests/annotations_test.js
- test/jasmine/tests/bar_test.js
- test/jasmine/tests/pie_test.js
Reboot of #2867
Original commit https://github.com/plotly/plotly.js/commit/d50334e8a16b033f4613cc310a17559e03865afd:
- Fix inheritance of explicit colors by later traces (see https://github.com/plotly/plotly.js/issues/2834#issuecomment-408965483)
- Allow inheritance (of explicit colors) by earlier traces too by adding a `calcInteractions` step immediately after `calc`.
- Add `layout.piecolorway` and `layout.extendpiecolors` for more control over pie colors (cc @nicolaskruchten @VeraZab)
- Does not address #2858
Update after #2868, commit https://github.com/plotly/plotly.js/commit/ded6e945250b910261101ccd92acd20c662abe30:
- Get rid of `calcInteractions` and uses `crossTraceCalc` for pies
- Update `crossTraceCalc` to work with pie (and other subplot-less traces)
- Simplify some things by …
> Pie colors fix & enhancements

- src/components/colorscale/defaults.js
- src/traces/scatter/line_defaults.js
- src/traces/scatter3d/attributes.js
A few `scatter3d` attributes are not listed properly as mentioned in https://github.com/plotly/plotly.js/issues/2872 and https://github.com/plotly/plotly.js/issues/2862.
This PR corrects them while we wait until https://github.com/plotly/plotly.js/issues/2872 and https://github.com/plotly/plotly.js/issues/2862 get implemented as features.
> Scatter3d attributes fixups

- src/traces/scattergl/index.js
- test/jasmine/tests/gl2d_click_test.js
fixes https://github.com/plotly/plotly.js/issues/2767 
Can't stop won't stop fixing bugs this week.
I'm not 100% this is the best to fix this bug (@dy would you mind reviewing this?), but the new test case should be a good starting point if ever there's a better solution out there.
> Fix scattergl select -> dblclick -> pan bug

- package-lock.json
- package.json
- tasks/util/browserify_wrapper.js
Rewrite require calls in the generated bundles so that Browserify is able
to consume the bundles when bundling new bundles. Solves issue #2902.
I can successfully use the bundle this builds in Browserify as well as Webpack (CRA). That being said I am not a Webpack Pro, so if someone else could double check this it'd be much appreciated.
> Apply derequire to generated bundles

- src/plots/cartesian/axes.js
- test/jasmine/tests/axes_test.js
At least until we do something more substantial in #2893, be more consistent about the 100 microsecond limit.
cc @etpinard
> fix #2892 - don't allow auto date ticks < our 100 microseconds limit

- src/components/drawing/index.js
- src/snapshot/tosvg.js
- tasks/noci_test.sh
- test/jasmine/tests/snapshot_test.js
This PR fixes `toSVG` (and hence `toImage` and `downloadImage`) for graphs with filled colorbars (from https://github.com/plotly/plotly.js/pull/2910) and contour legend items (added in https://github.com/plotly/plotly.js/pull/2891) in "newer" browsers.
These bugs are related to double-nested `"` inside svg node `style` - which browsers have a hard time serializing (cc https://github.com/plotly/plotly.js/issues/1697). Why were they unnoticed in their respective PRs: our old nw.js image-server doesn't care about those double-nested `"`. 
What saved us from releasing these bugs in 1.40.0 is `./tasks/noci_test.sh` which test mapbox and cone mocks using orca (which relies on a much newer version of Chromium) where the mocks with colorbars failed to export.
Now, this PR offers two solutions:
- …
> Fix `toSVG` for graphs that call `Drawing.gradient`

- .circleci/test.sh
- package-lock.json
- package.json
- tasks/shard_jasmine_tests.js
- tasks/test_syntax.js
- tasks/util/common.js
- test/jasmine/karma.conf.js
- test/jasmine/tests/cone_test.js
- test/jasmine/tests/gl2d_click_test.js
- test/jasmine/tests/gl2d_date_axis_render_test.js
- test/jasmine/tests/gl2d_plot_interact_test.js
- test/jasmine/tests/gl2d_pointcloud_test.js
- test/jasmine/tests/gl2d_scatterplot_contour_test.js
- test/jasmine/tests/gl3d_plot_interact_test.js
- test/jasmine/tests/gl_plot_interact_basic_test.js
- test/jasmine/tests/parcoords_test.js
- test/jasmine/tests/polar_test.js
- test/jasmine/tests/select_test.js
- test/jasmine/tests/shapes_test.js
- test/jasmine/tests/splom_test.js
- test/jasmine/tests/streamtube_test.js
resolves https://github.com/plotly/plotly.js/issues/2922 (hopefully)
This PR adds a _sharding_ script that splits our jasmine test suites into groups of a given number of `it` blocks. We use it here to shard jasmine tests with tag `@gl`, but the same logic could eventually be used in other jasmine tests.
To make the sharding logic simple and predictable, we enforce the following jasmine test tag _rules_:
- `@gl`, `@noCI`, `@noCIdep` and `@flaky` are the only allowed tags
- `@gl` and `@flaky` can't be set in `describe` blocks, only in `it` blocks
- a given `it` block can't have both a`@gl` and a `@flaky` tag (i.e. all `@gl` are _flaky_ and are in runned in retry loop on ci, setting both tags is redundant)
Along the way, commit 77125072d0f568f4f0726f87680b9de84e5e88ed made …
> Shard gl jasmine tests

- src/snapshot/download.js
- test/jasmine/tests/download_test.js
> Fix Plotly.download using graph id as 1st argument

- src/plot_api/plot_api.js
- test/jasmine/tests/splom_test.js
... as this can unfortunately happen when relayouting to large width/height on some browsers e.g. Chrome 68 and Chrome 64 (that we use on CI).
Note that this doesn't just affect sploms, but all regl-based trace type and presumably all WebGL-trace types.
> Replot when webgl buffer dims don't match canvas dims

- src/traces/sankey/plot.js
- test/jasmine/tests/sankey_test.js
Fixes #2782 
Simple fix: hover handler functions now simply return if hovermode is false.
cc @etpinard
> disable hover for sankey traces when hovermode is false

- src/plot_api/plot_api.js
- src/plots/plots.js
- test/jasmine/tests/transform_multi_test.js
@nicolaskruchten try this with https://github.com/plotly/react-chart-editor and the fit transform.
> ensure makesData transforms work with Plotly.react

- package-lock.json
- package.json
- src/traces/scattergl/index.js
cc @alexcjohnson 
The first commits applies https://github.com/a-vis/regl-splom/pull/9 and the other essentially reverts https://github.com/plotly/plotly.js/pull/2783
Note that `gl-text@1.1.6` includes an additional commit (-> https://github.com/a-vis/gl-text/commit/95036634910f6801b0eb583a58ab286c98b0c500) that wasn't bundled before. @dy do you remember what https://github.com/a-vis/gl-text/commit/95036634910f6801b0eb583a58ab286c98b0c500 was for?
> Bump regl trace deps

- src/lib/prepare_regl.js
- src/plots/gl3d/scene.js
- test/jasmine/tests/gl2d_plot_interact_test.js
- test/jasmine/tests/gl3d_plot_interact_test.js
- test/jasmine/tests/parcoords_test.js
cc @alexcjohnson 
I'm not sure if there's a way to actually test this.
This PR makes regl-based graphs emit an event on WebGL context lost from one of our canvases.
Note that gl3 already sort of does this:
https://github.com/plotly/plotly.js/blob/ff3c324bc09029766b9e4b7ab517b83166a7e363/src/plots/gl3d/scene.js#L231-L234
but logs something instead of emitting an event. Personally, I think emitting an event is better, but maybe consistency with gl3d is best (this is, before the v2 push).
> Emit 'plotly_webglcontextlost' event on WebGL context lost

- src/plots/plots.js
- test/jasmine/tests/plots_test.js
- as `JSON.stringify(new Float32Array([1,2,3]))` gives: `"{"0":1,"1":2,"2":3}"`
- use `Lib.simpleMap` as opposed to `Array.prototype.slice.call(d)` to avoid potential 'exceed stack size' errors
> Convert typed array to 'regular' arrays before sendToCloud

- test/jasmine/tests/plot_api_test.js
I forgot to run the `@noCI` tests after adding the last commit of https://github.com/plotly/plotly.js/pull/2977
> There are now 4 `<g.drag>` nodes in polar subplots

- src/plot_api/plot_api.js
- test/jasmine/tests/plot_api_test.js
fixes https://github.com/plotly/plotly.js/issues/2898, a better fix would be to make `dtick` and `tick0` for all axes _just work_ with `Plotly.react` with no added logic (that's one of the items in https://github.com/plotly/plotly.js/issues/2353), but that will be for another day.
cc @alexcjohnson @antoinerg
> Don't skip over dtick and tick0 in geo subplot in diffLayout

- src/components/dragelement/index.js
- test/jasmine/tests/hover_label_test.js
Fixes #1967 
Fx.hover() uses evt.clientX and evt.clientY to calculate an offset for the hover. In a TouchEvent, these properties are undefined, which results in the hover being rejected.
https://github.com/plotly/plotly.js/blob/master/src/components/fx/hover.js#L285
> DragElement: initialize clientX and clientY for touch events

- src/plots/cartesian/dragbox.js
- test/jasmine/tests/cartesian_interact_test.js
... so that 'old' keys from two-sided zoomboxes don't trickle into single-side zoombox updates.
Fixes https://github.com/plotly/plotly.js/issues/3026, which was made apparent staring from `v1.40.0` (and PR https://github.com/plotly/plotly.js/pull/2823), as we no longer run a `calc` edit when autoranging cartesian axes (e.g on double-click).
This one is fairly bad bug, so I'll make a release as soon as this thing is merged.
cc @alexcjohnson @antoinerg
> Reset updates object on every zoomDone

- src/plot_api/validate.js
- src/plots/polar/legacy/area_attributes.js
- src/plots/polar/legacy/axis_attributes.js
- src/traces/barpolar/layout_defaults.js
- src/traces/scatter/attributes.js
- test/jasmine/tests/barpolar_test.js
- test/jasmine/tests/validate_test.js
@alexcjohnson @antoinerg this solution isn't as strict as it could be (see comment in test), but at least it fixes the false-negative case of #3022.
> Fix #3022 - validate + polar.bargap

- src/traces/barpolar/hover.js
- src/traces/scatterpolar/hover.js
- src/traces/scatterpolargl/index.js
- test/jasmine/tests/barpolar_test.js
- test/jasmine/tests/scatterpolar_test.js
- test/jasmine/tests/scatterpolargl_test.js
Thanks for the report @alexcjohnson !
> Polar 'text' in hover labels fixes

- src/components/legend/get_legend_data.js
- test/jasmine/tests/pie_test.js
> Fix pie's support for individual stroke width values [2989]

- src/plots/plots.js
- test/jasmine/tests/config_test.js
> fallback to max-width and max-height if necessary

- src/components/fx/hover.js
- test/jasmine/tests/hover_label_test.js
fixes https://github.com/plotly/plotly.js/issues/2981, by doing two things:
- contrast common hover label font color w/ bgcolor
- do not use `hoverlabel.bgcolor` to determine for "name" part of hover label
cc @alexcjohnson @antoinerg 
More to come in https://github.com/plotly/plotly.js/issues/2342, but this is probably the best we can do until then.
> Fix hover label coloring on white bgcolor

- src/components/fx/hover.js
- test/jasmine/assets/custom_assertions.js
- test/jasmine/tests/hover_label_test.js
- test/jasmine/tests/violin_test.js
fixes https://github.com/plotly/plotly.js/issues/2194 and might offer a solid enough workaround for https://github.com/plotly/plotly.js/issues/2970 to close it.
cc @alexcjohnson @antoinerg
> Rotate hover labels in a few more scenarios

- src/plot_api/plot_api.js
- test/jasmine/tests/shapes_test.js
fixes an issue brought up in https://community.plot.ly/t/posible-issue-in-plotly-relayout-and-passing-in-an-update-object-with-a-shapes-array/13975 - which didn't lead to any bugs (as the correct `editType` was still resolved), but lead to a false `Lib.warn` message in the console.
This PR is essentially a small fixup of commit https://github.com/plotly/plotly.js/commit/138a84f613c7c6185c6c1d1d3978fda4754f76e5#diff-2941ab69a12080c0633ff4ac8ea3aa83 from PR https://github.com/plotly/plotly.js/pull/2823 (fast axis autorange).
@alexcjohnson @antoinerg @archmoj
> Do not to look for 'add' or 'remove' when replacing array containers

- src/plots/cartesian/axis_autotype.js
- test/jasmine/tests/axes_test.js
Fixes #3039 - treat `boolean` as category data in autotype
Fixes #2473, fixes #1413, by counting only distinct values while determining date and category autotype, as discussed in https://github.com/plotly/plotly.js/issues/2473#issuecomment-372825967. This way we don't need to include any explicit "missing" values; data with up to 2 non-numeric values for every numeric value will still be interpreted as numbers, but even a single non-numeric string (including the previous special values `'None'` and `''`) will be interpreted as a valid category if there are no numbers present.
Note that as part of ^^ I also converted the date determination to counting distinct values. Nobody had complained about this part, but if I didn't do that there could be some strange cases where you have only date …
> Axis autotype update

- src/plots/cartesian/layout_attributes.js
> Clarify documentation for "overlaying"

- package-lock.json
- package.json
by bumping gl-plot3d to 1.5.6 which includes @dy's https://github.com/gl-vis/gl-plot3d/pull/11 that closed https://github.com/plotly/plotly.js/issues/280
cc @nicolaskruchten @plotly/plotly_js
> Fix gl3d subplots on tablets

- build/plotcss.js
- src/css/_modebar.scss
This PR makes vertical modebars behave like horizontal ones.
Previously, a vertical modebar could overflow the figure's container:
With this PR, it doesn't and wrap the items:
This patch relies on `display:flex` which is used on plotly's official webpage and is now [very well supported](https://caniuse.com/#search=flex).
> prevent vertical modebar from overflowing

- src/plot_api/template_api.js
- test/jasmine/tests/template_test.js
As a first-time user of templates, I expected the following to just work:
```
var.gd = document.getElementById('graph');
Plotly.plot(gd,{...});2,3], y:[4,9,3], line: {color: 'red'}}
...
var layout = Plotly.makeTemplate(gd);
```
This PR enables calling `makeTemplate` with a DOM element.
> support dom element as argument to Plotly.makeTemplate

- src/plot_api/helpers.js
- test/jasmine/tests/plot_api_test.js
> ignore invalid trace indices in restyle and update

- test/jasmine/tests/template_test.js
Title is pretty self-explanatory 🙂!
> test that validateTemplate accepts DOM element as input

- devtools/test_dashboard/server.js
This allows talking to the devtools http server from any webpage. This enables my prototype image viewer (hosted on another domain) to retrieve mocks and images from localhost!
> add cors support for devtools http server

- src/plot_api/plot_api.js
- test/jasmine/tests/config_test.js
- test/jasmine/tests/plot_api_test.js
So you can turn autosize back on again, using `relayout` or `update`, after it's been turned off and replaced by explicit `height` & `width`.
@antoinerg please review. Shouldn't have any adverse impact on the autosize work you did recently as this only affects edit behavior (and only the older modes, not `react`)
> implied edits connecting height/width/autosize

- src/plot_api/plot_api.js
- test/jasmine/assets/mock_lists.js
Fixes #3121 
See issue for details!
> ignore private attributes in diffConfig

- src/traces/parcoords/parcoords.js
- test/jasmine/tests/parcoords_test.js
This PR could fix the issue #3099 i.e. before the implementation of hovermode for parcoords.
@alexcjohnson
> Display parcoords deselected lines

- src/lib/search.js
- test/jasmine/tests/lib_test.js
Fix `Lib.sort`'s tests which are failing in Chrome v70+.
Background:
Chrome v70+ introduces a new implementation of ` Array.prototype.sort` which optimizes sorting pre-sorted arrays. Our own `Lib.sort` doesn't win the shootout anymore so the tests have to be relaxed to reflect that. Beating the browser was only gravy anyway.
Thanks to @Marc-Andre-Rivet for pointing this out to me :)
> update Lib.sort comment and relax its tests

- src/lib/loggers.js
- test/jasmine/tests/lib_test.js
cc @antoinerg - a sort of followup to #3114
> prevent our loggers from throwing their own errors in a few more cases

- .circleci/config.yml
Testing the artifacts features of circleCI. 
The idea is to store the `plotly.js` that gets built for each commit/branch. This way, it would be extremely easy to test a particular branch without having to checkout, build and serve over HTTP locally. Moreover, if the artifacts are served by circleCI over HTTPS, it will be easy to test them out in Codepen and quickly swap between versions to check whether it correctly fixes a given issue.
> add build artifact to CI build

- src/plots/plots.js
- test/jasmine/tests/splom_test.js
Transforms mean `supplyDefaults` gets run twice. This is mostly fine, but there are some unwanted effects from running it on a trace object that has already had its defaults filled in. The one I'm concerned with here is that if a trace is explicitly `visible: false` we don't even run the module defaults, but occasionally there are things that automatically trigger `visible: false` in the module defaults, after we've already set some properties in `fullTrace`. Because the `visible: false` only makes sense based on those properties, we still want them to be part of the final trace (for example, to make RCE and toolpanel happy). So in this PR I detect this situation and clear `expandedTrace.visible` so that the original logic will run again the second time through `supplyDefaults`.
@etpinard …
> fix for transforms operating on auto-invisible traces

- src/plot_api/edit_types.js
- src/traces/sankey/attributes.js
- src/traces/sankey/defaults.js
- src/traces/sankey/plot.js
- test/jasmine/tests/sankey_test.js
> implement hoverinfo 'none' and 'skip' in sankey

- .circleci/config.yml
I'm a <strike>big</strike> huge fan of @antoinerg 's https://github.com/plotly/plotly.js/pull/3136, so I couldn't resist improving it slightly.
This PR:
- makes the build artifacts get "published" even when the tests fail (which can be useful in some situations)
- echoes the artifact URLs in the publish step using Circle's [built-in environment variables](https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables), which can serve as an easier click-to alternative to @antoinerg's [fancy shell footwork](https://github.com/plotly/plotly.js/pull/3136#issuecomment-432059992).
> Improvements for CI build artifacts

- src/plot_api/plot_api.js
- src/traces/scattergl/index.js
- test/jasmine/tests/gl2d_plot_interact_test.js
This PR resolves the issue #2999 by providing additional checks before calling destroy functions of scattergl. Without these checks in scenarios namely switching back and forth between different modes e.g. `markers` to `lines` and  then back to `markers` the program (depending on the device/browser) may complain and/or stop.
@alexcjohnson
> Fix to enable switching modes using plotly react method on scattergl traces

- src/traces/sankey/attributes.js
- src/traces/sankey/defaults.js
- test/jasmine/tests/sankey_test.js
Addressing comments of @etpinard on PR https://github.com/plotly/plotly.js/pull/3096.
I also DRYed up some tests!
> sankey hover improvements

- src/components/drawing/index.js
- src/traces/scatter/link_traces.js
- test/jasmine/tests/scatter_test.js
This PR fixes an unreleased regression originating from https://github.com/plotly/plotly.js/pull/3087. I'd like to get this in before the 1.42.0 release.
Scatter fills on master currently do not restyle correctly and lead to these logs:
but **no** failed tests. That's because those logs come from:
https://github.com/plotly/plotly.js/blob/0a310c99455bf7389f4bb891392c806b59d93d47/src/components/drawing/index.js#L201-L207
which do **not** make `failTest` throw, leading to false-positive tests.
----------
The first commit fixes and :lock:s the bug, and the second commit :hocho:s that try-catch (which is at least 4 years old) which is probably a bit more dangerous, but I'm willing to take that chance. I hope @plotly/plotly_js agrees.
> Fix scatter fill regression

- src/traces/splom/attributes.js
- src/traces/splom/index.js
- test/jasmine/tests/splom_test.js
This PR is a fixes a few regressions introduced in https://github.com/plotly/plotly.js/pull/3057.
This PR should be merged before the 1.42.0 release.
> Splom marker edits regression fixups

- src/traces/bar/cross_trace_calc.js
- test/jasmine/tests/bar_test.js
fixes https://github.com/plotly/plotly.js/issues/3142 and a similar unlisted bug for bar `offset`.
> fix support for typed arrays in bar 'width' and 'offset'

- package-lock.json
fixup for commit https://github.com/plotly/plotly.js/pull/3171/commits/513461a7c0d8e5215fe9fc7ec9a4a3c220dbd76c - where @archmoj wasn't using the correct npm version.
> Update package-lock for pr #3171

- package-lock.json
This PR adds optional packages info which may help improve the build times.
@etpinard
> optional packages

- src/lib/index.js
- test/jasmine/assets/unpolyfill.js
- test/jasmine/karma.conf.js
This PR is a fixup of https://github.com/plotly/plotly.js/pull/3068 for IE11, which hopefully will be enough to close https://github.com/plotly/plotly.js/issues/3186. It would be nice to add a test before merging this in.
> Fix modebar <style> update in IE11

- src/plot_api/plot_schema.js
- src/plots/plots.js
- src/traces/carpet/attributes.js
- src/traces/cone/attributes.js
- src/traces/contourcarpet/attributes.js
- src/traces/heatmap/attributes.js
- src/traces/mesh3d/attributes.js
- src/traces/parcoords/attributes.js
- src/traces/pointcloud/attributes.js
- src/traces/sankey/attributes.js
- src/traces/streamtube/attributes.js
- src/traces/surface/attributes.js
- src/traces/table/attributes.js
- test/jasmine/bundle_tests/plotschema_test.js
- test/jasmine/tests/parcoords_test.js
Fixes #3058 
Prune unsupported global-level trace attributes from
> prune global-level trace attributes that are already defined in a trace

- src/traces/scattergl/index.js
- test/jasmine/tests/config_test.js
- test/jasmine/tests/gl2d_plot_interact_test.js
fixes https://github.com/plotly/plotly.js/issues/3197
> Guard against infinite loops during scattergl line/fill positions cleanup

- test/jasmine/tests/parcoords_test.js
Fixes #3178.
The `getAvgPixelByChannel` function is revised and now accepts an id to select which gl layer (e.g. focus/pick/context) to be used by different tests. 
The new jasmine test, checks for the parcoords context layer to remain visible after a restyle call.
@etpinard 
@alexcjohnson
> Second jasmine test to lock issue 3101

- src/traces/bar/attributes.js
- src/traces/pie/attributes.js
- test/jasmine/tests/bar_test.js
- test/jasmine/tests/pie_test.js
fixes https://github.com/plotly/plotly.js/issues/3190
> pie/bar textfont-color restyles

- src/traces/scattergl/index.js
- src/traces/scatterpolargl/index.js
- test/jasmine/tests/gl2d_plot_interact_test.js
- test/jasmine/tests/scatterpolargl_test.js
fixes https://github.com/plotly/plotly.js/issues/3226 and partly fixes https://github.com/plotly/plotly.js/issues/2999#issuecomment-436005771
This PR is essentially a fixup of my (dumb) https://github.com/plotly/plotly.js/commit/f79c64c359a52a4342fc31ee796535e3806218f6 commit.
> Fixup scattergl / scatterpolargl with mode: lines & >1e5 pts

- package-lock.json
Implementing https://github.com/plotly/plotly.js/pull/3184#issuecomment-435958178 so that 
```
git checkout master
git pull
npm install
```
won't result in a `package-lock` diff.
> Remove non-reproducible "optional" fields in package-lock

- tasks/sync_packages.js
resolves https://github.com/plotly/plotly.js/issues/3083, a continuation from https://github.com/plotly/plotly.js/pull/2670 (the partial-bundle-pkgs PR)
As locale files are fairly small, I decided to publish only one `plotly.js-locales` package (as opposed to one per locale) and ask users (in the `plotly.js-locales` README) to grab to relevant locale as:
```js
// ES6 module
import Plotly from 'plotly.js';
import locale from 'plotly.js-locales/fr';
// CommonJS
var Plotly = require('plotly.js');
var locale = require('plotly.js-locales/fr');
// then
Plotly.register(locale);
```
that is, users would npm-download all the locales, but only bundle the locale(s) they need.
Reviewers can look at:
https://github.com/plotly/plotly.js/compare/publish-locales...publish-locales-build
to see to …
> Publish `plotly.js-locales` to npm

- src/components/fx/hovertemplate_attributes.js
> update hovertemplate description

- package-lock.json
fixup after https://github.com/plotly/plotly.js/pull/3286 - might be worth adding a `tasks/` script that does that at some point.
> http -> https in package-lock.json

- appveyor.yml
- package-lock.json
- package.json
- test/jasmine/karma.conf.js
- test/jasmine/tests/lib_test.js
resolves https://github.com/plotly/plotly.js/issues/431
Looks like AppVeyor has gotten a lot better in the last three years, adding IE11 tests was relatively easy.
Note that this iteration only tests the `lib_test.js` suite. We should add more IE11 tests eventually, perhaps by adding a specialty suite in `test/jasmine/bundle_tests/ie11_test.js` or by adding a `@ie11` jasmine tag.
But as discussed in https://github.com/plotly/plotly.js/issues/431#issuecomment-435079403, adapting all our jasmine tests (especially our pixel-based tests) might be too much of a pain for little benefit.
> Add (some) IE11 testing on AppVeyor

- src/components/annotations/draw.js
- src/components/drawing/index.js
- src/components/errorbars/plot.js
- src/components/images/draw.js
- src/components/legend/draw.js
- src/components/rangeslider/draw.js
- src/components/shapes/draw.js
- src/components/updatemenus/scrollbox.js
- src/plot_api/plot_api.js
- src/plot_api/subroutines.js
- src/plot_api/to_image.js
- src/plots/cartesian/index.js
- src/plots/geo/geo.js
- src/plots/polar/polar.js
- src/plots/ternary/ternary.js
- src/traces/bar/plot.js
- src/traces/barpolar/plot.js
- src/traces/contour/plot.js
- src/traces/contourcarpet/plot.js
- src/traces/scatter/plot.js
- src/traces/scattercarpet/plot.js
- src/traces/table/plot.js
- test/jasmine/tests/drawing_test.js
- test/jasmine/tests/plot_interact_test.js
- test/jasmine/tests/snapshot_test.js
- test/jasmine/tests/toimage_test.js
fixes https://github.com/plotly/plotly.js/issues/3260
@plotly/plotly_js to do this "properly" i.e. w/o doing something hacky in `Snapshot.toSVG` like
```js
d3.selectAll('[clipPath'].each(function() {
var s = d3.select(this);
var cp = s.attr('clipPath');
s.attr('clipPath'. cp.replace(URL_REGEX, '');
})
```
I made `Drawing.setClipUrl` expect `gd` as third argument. This means we can stash the `<base>` href on `gd._context` (instead of on `Drawing`) and use it in `setClipUrl`.
> Do not add <base> href to SVG clip paths during toImage

- src/components/drawing/index.js
- test/jasmine/tests/scatter_test.js
fixes https://github.com/plotly/plotly.js/issues/3277 - introduced by https://github.com/plotly/plotly.js/commit/1f3c10c735927d57b78151be8c4d43bdf35e53d7
> Fix fills on segment-less marker-less traces

- src/components/modebar/manage.js
- src/plot_api/plot_config.js
- test/jasmine/tests/modebar_test.js
Closes #316 - removes the "Edit in Chart Studio" button by default, and adds a new config arg `showSendToCloud` to re-enable it.
cc @etpinard @nicolaskruchten @chriddyp any comments in particular on the name of this new arg?
> remove "Edit in Chart Studio" button by default

- src/components/fx/hovertemplate_attributes.js
- src/traces/sankey/attributes.js
- src/traces/sankey/defaults.js
- src/traces/sankey/plot.js
- test/jasmine/tests/sankey_test.js
> hovertemplate support for sankey

- src/traces/table/data_preparation_helper.js
- src/traces/table/plot.js
- test/jasmine/assets/mouse_event.js
- test/jasmine/tests/table_test.js
> Table scroll

- package-lock.json
- package.json
Bumped `regl-scatter2d` to be at 3.1.2
@etpinard
> Apply regl-scatter2d vertex shader simplifications

- src/traces/histogram/calc.js
- test/jasmine/tests/histogram_test.js
... in `Histogram.calc` loop looking for `isFirstVisible` traces.
cc @plotly/plotly_js - a follow-up of https://github.com/plotly/plotly.js/pull/3044
cc @nicolaskruchten
> fixes #3336 - don't try to makeCalcdata on visible:false traces

- src/plots/cartesian/dragbox.js
- test/jasmine/tests/click_test.js
... on graphs w/ `fixedrange:true` axes and w/o set `_rangeInitial`
fixes https://github.com/plotly/plotly.js/issues/3347 cc @plotly/plotly_js
> Fix axis autorange on doubleClick

- src/plots/cartesian/axes.js
- test/jasmine/tests/cartesian_test.js
A follow-up on https://github.com/plotly/plotly.js/pull/3326/commits/c88c16722a9e7c7fc5016c56190642e37b934c85 merged in #3326 - fixing a bug reported in-person by @nicolaskruchten set to be released in `v1.43.1`.
> Clear y-axis multicategory secondary ticks and dividers

- package-lock.json
- package.json
> Bumping the dev deps 2018-12-21 edition

- package-lock.json
- package.json
More info: 
- https://npm.community/t/some-packages-have-dist-tarball-as-http-and-not-https/285/44
- https://www.npmjs.com/package/replace (using this as a cross-platform `sed`)
so that 
```
git checkout master
npm i
```
doesn't lead to
ever again!
> Add postshrinkwrap step to replace http:// -> https://

- package-lock.json
- package.json
This PR is the follow up to #3372. 
In order to reduce the chance of undesirable changes to the code by using a general purpose `replace` program, regex and its dependencies, a new module is developed https://www.npmjs.com/package/chttps that could be maintained by the Plotly team and may possibly be handy in fixing similar `http > https` fixes in other places namely in `gl-vis` module upgrades.
> Compact http to https with zero dependency
