plotly/plotly.js

src/traces/heatmap/index.js

@etpinard - just a missing period.

heatmap documentation tyop

---

src/plot_api/plot_api.js
test/jasmine/tests/plot_api_test.js
test/jasmine/tests/plot_promise_test.js

Added promise returns for exposed methods in `plot_api.js`, and they will all be sent along with the gd.
https://github.com/plotly/plotly.js/issues/76
Tests on `npm run test-image` are not passing on my machine, but let's see if they pass on circle!

Added promise returns to Plotly.___

---

devtools/test_dashboard/server.js
devtools/test_dashboard/test_cartesian.js

@mdtusz @alexcjohnson 
`npm run start-test_dashboard -- cartesian` for cartesian dashboard buttons.

Cartesian test dashboard buttons

---

.gitignore
circle.yml
package.json
tasks/test_bundle.js
tasks/util/constants.js
test/jasmine/bundle_tests/bar_test.js
test/jasmine/bundle_tests/choropleth_test.js
test/jasmine/bundle_tests/contour_test.js
test/jasmine/bundle_tests/core_test.js
test/jasmine/bundle_tests/histogram2dcontour_test.js
test/jasmine/karma.conf.js
test/syntax_test.js

@mdtusz 
Far from covering all the possible bundle cases, but it's a start.
The jasmine test file are very repetitive, if you find a better to test custom bundles, please let me know.

Add testing framework to test custom bundles

---

src/traces/scattergeo/plot.js

Woopsie daisies. 
:neutral_face:

Fix incorrect path for graph interactions

---

circle.yml

@mdtusz @cldougl @alexcjohnson 
Any objections?

add eslint test to circle.yml

---

README.md

Browserify complains right away :)

Small correction: remove semicolon from the register array

---

package.json

@mdtusz quick PR to make the devDependencies badge go green.

bump karma-browserify

---

src/plots/gl2d/scene2d.js

@mdtusz which has broken since https://github.com/plotly/plotly.js/pull/300

fix gl2d toImage from modebar button

---

test/syntax_test.js

@mdtusz dev tools week continues ...
This PR adds a test asserting that all file names are in lower case. 
Inspired what happened in https://github.com/plotly/plotly.js/pull/390#discussion-diff-58316524 .
Maybe we could also enforce that file names use `_` and not `-` ?

Add file name syntax test

---

src/components/annotations/attributes.js
src/plots/cartesian/constants.js
src/plots/cartesian/index.js
src/plots/cartesian/layout_attributes.js
test/jasmine/karma.conf.js

@mdtusz @monfera @timelyportfolio @n-riesco 
A few of you noticed that running
```bash
npm run test-jasmine -- tests/<name-of-test-suite>.js
```
resulted in import errors for some test suites.
This PR (in an albeit hacky way) fixes this issue.

Single suite karma/jasmine tests

---

package.json

@mdtusz .. keeping our badges [green](https://david-dm.org/plotly/plotly.js#info=devDependencies).

bump fs-extra dev dep

---

README.md

@mdtusz doc Tuesday continues.

add usage info in README quick start

---

test/jasmine/tests/gl_plot_interact_test.js

This PR reduces the number of jasmine test failures (when run locally) from 78 to 3.

test: fix bug in gl_plot_interact_test.js

---

src/plots/cartesian/layout_attributes.js
src/traces/contour/attributes.js

Update `nticks` and `ncontours` descriptions

---

devtools/test_dashboard/server.js

Devtools: Fix mock-file filter function

---

src/plots/mapbox/layout_attributes.js

 fix typo in layout.mapbox.layers.line description

---

src/plots/mapbox/mapbox.js
test/jasmine/tests/mapbox_test.js

@chriddyp 
Now,
```js
gd.on('plotly_relayout', function(updateData) {
updateData  // => { mapbox: { /* */ }
});
```

emit plotly_relayout on mapbox map move

---

circle.yml
src/lib/svg_text_utils.js
test/jasmine/tests/svg_text_utils_test.js

Cherry-pick #736 into a v1.1.1 -> v1.1.2 maintenance release

---

test/jasmine/tests/heatmap_test.js

test material locking down the patch in https://github.com/plotly/plotly.js/pull/783

Add test case for PR 783

---

.gitignore
devtools/test_dashboard/server.js

@etpinard @bpostlethwaite
Please take a look, this just fixes dashboard in windows.

Fix dashboard for windows

---

package.json

Applies the fix for the font change detection bug FI-19.
It needs that these are merged and `npm publish`ed first:
1. https://github.com/gl-vis/gl-axes3d/pull/8
2. https://github.com/gl-vis/gl-plot3d/pull/5

FI-19 bumped gl-plot3d to benefit from fix in gl-axes3d

---

src/traces/bar/hover.js
test/jasmine/tests/bar_test.js

fixes https://github.com/plotly/plotly.js/issues/1105
Two-character fix of commit 451ee82890bb1ce10857406280cd0a958a94f6bc merged in PR https://github.com/plotly/plotly.js/pull/1075
I'll add a few test cases and release `1.19.2` tomorrow morning.
cc @n-riesco

Fix hover bar delta

---

test/jasmine/tests/transform_filter_test.js

resolves https://github.com/plotly/plotly.js/issues/1135
@bpostlethwaite https://github.com/plotly/plotly.js/issues/1135 turned out to be a non-bug, but might as well commit the test cases I used to confirmed this non-bug.

Add test cases for category + array target + interval op

---

src/components/modebar/buttons.js
test/jasmine/tests/modebar_test.js

fixes https://github.com/plotly/plotly.js/issues/1160
cc @alexcjohnson @adamborowski

Modebar date zoom fix

---

src/plot_api/plot_schema.js
test/jasmine/tests/plotschema_test.js

Fix defs.metaKeys field

---

devtools/test_dashboard/devtools.js

load frames in test dashboard

---

composer.json

This file is required to add plotly.js is packagist and solves issue #1242.

create composer.json file to add plotly in packagist

---

test/jasmine/tests/gl2d_click_test.js

- remove `noCI` tag -> now runs on CI :tada: 
- add abstractions to test hover/click/unhover for every
gl2d trace type
- merge redundant specs

Revamp gl2d click test suite

---

test/jasmine/tests/gl_plot_interact_test.js

to :hocho: CI intermittent failures (hopefully).

Bump gl plot interact delay

---

src/components/annotations/click.js
test/jasmine/tests/annotations_test.js

a quick one @etpinard @charleyferrari

Support all axis types for clicktoshow annotations

---

package.json

fixes https://github.com/plotly/plotly.js/issues/1510
using @dfcreative's https://github.com/gl-vis/gl-scatter2d-sdf/pull/1

Fix scattergl marker size restyle bug

---

README.md

It's about time we do this.
cc @rreusser @monfera @n-riesco 
@n-riesco do you have a twitter account you want us to show in our README?

Add Ricky, Robert and Nico to Creators section

---

package.json

That fixes losing points in scatter2d zooming in/out https://github.com/gl-vis/gl-scatter2d/pull/6
@etpinard @bpostlethwaite

Bumg gl-scatter2d

---

src/traces/scattergl/convert.js

fixes #1806
https://github.com/plotly/plotly.js/issues/1806#issuecomment-310501742

Reset selection by doubleclick

---

src/plots/gl2d/scene2d.js
src/plots/gl3d/camera.js
src/plots/gl3d/scene.js

Covers https://github.com/plotly/plotly.js/issues/1813

Fix scatter camera memory leak

---

.github/SUPPORT.md

... might as well: https://github.com/blog/2400-support-file-support
Any objections @chriddyp @jackparmer @alexcjohnson ?

add SUPPORT.md file

---

package.json

https://github.com/plotly/plotly.js/issues/1900#issuecomment-317782675

Bump color-rgba

---

src/components/shapes/draw.js
test/jasmine/tests/shapes_test.js

fixes #1974 
Interesting that we had a test of shapes with an overlaid axis but... we didn't actually put any shapes on this axis! now we do 😅 
cc @etpinard

fix and test shapes on overlaid axes

---

src/lib/index.js
src/traces/sankey/render.js

[minor] factor out raiseToTop

---

src/traces/parcoords/constants.js
src/traces/parcoords/parcoords.js
src/traces/sankey/constants.js
src/traces/sankey/plot.js
src/traces/sankey/render.js
src/traces/table/constants.js
src/traces/table/plot.js
test/jasmine/tests/parcoords_test.js
test/jasmine/tests/sankey_test.js

An item in https://github.com/plotly/plotly.js/issues/2056
@etpinard is it how you meant it, or should the test cases also pull the class names from the constants?

Lisp-casing class, id names and factoring them out in `table`, `parcoords`, `sankey`

---

lib/locales/de.js

type: translation Add "decimal" and "thousands" to de.js locale

---

README.md

As referenced here: https://github.com/plotly/plotly-webpack#bundling-with-webpack
Got approval to create pull request in #2294

Update README.md to reflect webpack configuration

---

package-lock.json
package.json
src/plots/mapbox/constants.js

https://github.com/mapbox/mapbox-gl-js/blob/master/CHANGELOG.md#0441

Bump and ping mapbox-gl to 0.44.1

---

lib/locales/cs.js

Contains Czech localization.
(Unfotunatelly, I don't know other czech users of Plotly.js, so hopefully some find this and approve/make corrections.)

Czech localization

---

README.md

Add dy to list of creators

---

src/components/drawing/index.js
src/components/fx/hover.js
test/jasmine/tests/hover_label_test.js

* treat number 0 as valid in hover fixes #2660

Fix for number 0 treated as invalid in hover (#1)

---

README.md

```
>>> len(plotly_schema['schema']['traces'].keys())
33
```

over 30 chart types

---

src/transforms/aggregate.js
test/jasmine/tests/transform_aggregate_test.js

This PR adds aggregate functions `range` (max - min) and `change` (last - first). Resolves #2763.

Aggregate functions

---

package.json

fixup following https://github.com/plotly/plotly.js/pull/2670

Fix typo in postpublish script

---

.github/ISSUE_TEMPLATE.md

cc @cldougl @alexcjohnson what do you think?
referencing https://github.com/plotly/plotly.js/issues/2818

Mention documentation repo in issue template

---

package-lock.json
package.json

which should solve
by making 
turn into

Bump dev deps that require sshpk

---

lib/locales/cy.js

supersedes #2877 
cc @HywelMJ - I tweaked formatting to make the syntax test happy, and swapped `tres` to `olin` - look good?
@etpinard I also put in unix-style `\n` line endings, so the optional `\r\n` test isn't necessary now - we could add it later but that can be a separate discussion.

Welsh translation

---

src/transforms/aggregate.js
test/jasmine/tests/transform_aggregate_test.js

This PR fixes the last item off https://github.com/plotly/plotly.js/issues/2908, corresponding to https://codepen.io/dmt0/pen/xJoWoY

Fix aggregate transforms with bad group values

---

src/traces/bar/attributes.js
src/traces/bar/plot.js
test/jasmine/tests/bar_test.js

Adresses #3116 (see also https://codepen.io/haskellelephant/pen/JmpJMZ). When base is set, which bar is outmost is difficult to calculate. Instead, outside is chosen for all bars in that case.

Don't override outside when base is set

---

.circleci/config.yml
tasks/bundle_plot_schema.js

circleci update plot-schema.json during publish job

---

src/components/legend/style.js
test/jasmine/tests/scatter_test.js

fixes https://github.com/plotly/plotly.js/issues/3179 

Fix legend for traces with typed array marker.size

---

package-lock.json

In this PR few more packages are highlighted by npm as `optional` which may help improve the build times.
@etpinard

Few more optional packages in lock

---

package-lock.json
package.json

to resolve https://github.com/plotly/plotly.js/network/alert/package-lock.json/cached-path-relative/open
where now

Bump browserify

---

package-lock.json
package.json

Bump svg-path-sdf

---

package-lock.json
package.json

Fixes #2802 @etpinard.
Should be merged with https://github.com/regl-project/regl/pull/518

Mute regl error

---

src/components/fx/hover.js
test/jasmine/tests/hover_label_test.js

fixes https://github.com/plotly/plotly.js/issues/3330 cc @plotly/plotly_js

fix #3330 - fix hoverChanged for traces with pointNumbers

---

src/components/rangeslider/attributes.js

description of borderwidth should be "Sets the border width" instead of "Sets the border color..."

Description of borderwidth

---

lib/locales/pl.js

Add missing polish character

---

test/jasmine/tests/plot_api_react_test.js

Remaining change from PR #3465.
Fix https://github.com/plotly/plotly.js/pull/3465#issuecomment-457238107 but using z value other than zero.
@etpinard

change camera up vector in plot api react test

---

src/components/fx/hovertemplate_attributes.js

update description of `hovertemplate`

---

tasks/noci_test.sh

a follow-up of https://github.com/plotly/plotly.js/pull/3591
cc @archmoj

No need to test `cone` traces during pre-release checklist

---

package-lock.json
package.json

Bump dev deps 2019-03-22

---

package-lock.json
package.json

Fixes #3671.
[Codepen Before](https://codepen.io/MojtabaSamimi/pen/YggKpB).
[Codepen After](https://codepen.io/MojtabaSamimi/pen/ywwBMM).

Bug fix surface plot issue with large floats using iOS

---

src/components/colorscale/scales.js

update comment on RdBu

---

src/traces/surface/convert.js

Lint fix after merging PR #3469.
cc: @etpinard

apply new eslint rule in surface convert file

---

lib/locales/sv.js

Added dictionary translations for Swedish.
@emillundstrm

Swedish translation

---

package-lock.json
package.json

@plotly/plotly_js this should be enough to clear our security [alerts](https://github.com/plotly/plotly.js/network/alerts).

Bump dev deps 11-06-2019 edition

---

src/components/errorbars/attributes.js

I think in the description this "array" should be "data" to match the options listed in values above

edit error type description

---

src/components/fx/hovertemplate_attributes.js
src/constants/docs.js
src/plots/cartesian/layout_attributes.js
src/traces/carpet/axis_attributes.js
src/traces/contour/attributes.js
src/traces/heatmap/attributes.js
src/traces/indicator/attributes.js
src/traces/sankey/attributes.js
src/traces/table/attributes.js

See https://github.com/plotly/plotly.js/issues/3052#issuecomment-424731196

Fix tickformat attribute description links

---

package-lock.json
package.json

i.e to remove an unused variable from the shader
https://github.com/gl-vis/gl-scatter3d/commit/a07e1fe5624c9376227b795cfed9b51ce165f107
@etpinard @antoinerg

Bump scatter3d to 1.2.2 

---

test/image/mocks/indicator_datacard3.json

Removing duplicate domain definition from an indicator mock

---

src/traces/indicator/attributes.js

Closes https://github.com/plotly/plotly.js/issues/4114

indicator: rename steps' items to `step`

---

src/traces/sankey/plot.js
test/image/mocks/sankey_subplots.json

Closes #4119 
Before: https://jsfiddle.net/9fmyo20c/
After: https://jsfiddle.net/qakmy2x6/

fix for invisible Sankey traces

---

src/traces/scattergl/convert.js
test/jasmine/tests/scattergl_test.js

Fix for PR #4071
See https://github.com/plotly/plotly.js/pull/4125#discussion_r313621904 for details

scattergl: do not mutate text array

---

src/traces/streamtube/index.js

I hope this is the right place for this PR. I had a hard time understanding how streamtube works, especially the divergence encoding the radius was only documented in a community post I think.

additions to streamtube doc

---

tasks/noci_test.sh

quick fixup of https://github.com/plotly/plotly.js/pull/3656 - cc @archmoj

Remove obsolete comment about noCI test for cone traces

---

lib/locales/zh-cn.js

follow-up from https://github.com/plotly/plotly.js/pull/4276#issuecomment-546976695
cc @archmoj for `v1.51.0`

zh-CN translation - fix trailing spaces

---

src/traces/parcoords/parcoords.js

remove a duplicate function call in parcoords

---

src/components/legend/attributes.js

Mention legend.bgcolor default in documentation

---

test/image/make_baseline.js

for @archmoj - making `npm run baseline` on-par with `npm run test-image`

Handle multiple positional args in make_baseline.js script

---

test/jasmine/assets/click.js
test/jasmine/assets/custom_matchers.js
test/jasmine/assets/modebar_button.js
test/jasmine/assets/mouse_event.js
test/jasmine/assets/touch_event.js
test/jasmine/tests/bar_test.js
test/jasmine/tests/funnel_test.js
test/jasmine/tests/funnelarea_test.js
test/jasmine/tests/pie_test.js
test/jasmine/tests/waterfall_test.js

apply src tag in jasmine requires

---

package-lock.json
package.json

bump minify-stream v2

---

package-lock.json
package.json

bump topojson-client v3

---

README.md

- Make a PR directly to the main repository
Developers are strongly encouraged to first make a PR to their own plotly.js fork and ask one of the maintainers to review the modifications there. Once the pull …

Added code block

---

package-lock.json

Follow up of #4802, this PR simply addresses @alexcjohnson's   https://github.com/plotly/plotly.js/pull/4802#issuecomment-622652654. 
As I also get this diff today, I'll move forward an merge this.

update package-lock May 2nd

---

package-lock.json
package.json

Bump eslint v7

---

devtools/test_dashboard/devtools.js
package-lock.json
package.json

Bump fuse.js v6

---

src/plot_api/validate.js
test/jasmine/tests/mock_test.js

handle undefined args in Plotly.validate

---

package-lock.json
package.json

bump through2, fuse.js and eslint versions

---

package-lock.json
package.json

bump is-mobile v2.2.2

---

package-lock.json
package.json

Bump dev-dependencies - June 30

---

src/plots/ternary/ternary.js

Fix numeric sort in ternary drag

---

package-lock.json
package.json

bump karma 5.1.1

---

package-lock.json
package.json

bump fuse.js 6.4.1

---

package-lock.json
package.json

Addressing https://github.com/plotly/plotly.js/network/alert/package-lock.json/elliptic/open

dev-install elliptic 6.5.3

---

src/components/rangeslider/draw.js

PR for the range slider touch support requested here:
https://github.com/plotly/plotly.js/issues/1098
Thanks @cristiantx @JasDev42 for the code.
#1098

Add Touch Support to RangeSlider #1098

---

package-lock.json
package.json

bump browserify 16.5.2

---

package-lock.json
package.json

bump eslint 7.6.0

---

package-lock.json
package.json

bump prepend-file v2

---

package-lock.json
package.json

https://github.com/sindresorhus/into-stream/releases/tag/v6.0.0

Bump into-stream v6

---

package-lock.json
package.json

bump lodash v4.17.20

---

package-lock.json
package.json

Bump dev-dependencies Aug 30

---

package-lock.json
package.json

bump eslint v7.9.0

---

package-lock.json
package.json

bump karma v5.2.2

---

package-lock.json
package.json

bump madge v3.10.0

---

package-lock.json
package.json

Bump some dev dependencies - Sep 29

---

README.md

Fixes #5247.
- Fix a broken link in README.md

Correct link in README.md

---

test/image/compare_pixels_test.js
test/image/mocks/legend_horizontal_testwrap.json
test/jasmine/tests/mock_test.js

fixup tests to pass on CI and more mock validation

---

package-lock.json
package.json

Addressing https://github.com/plotly/plotly.js/issues/5289#issuecomment-730518332
cc: @rreusser

Bump events to v3 in glslify-deps

---

CHANGELOG.md

It's me:)
https://github.com/plotly/plotly.js/pull/5212

Fix contributer's name in CHANGELOG

---

package-lock.json

Addressing 
https://github.com/plotly/plotly.js/network/alert/package-lock.json/ini/open
See 
https://github.com/advisories/GHSA-qqgx-2p2h-9c37

Reinstall watchify and madge to bump version of the ini module

---

devtools/image_viewer/index.html

Fixup image_viewer

---

src/traces/indicator/plot.js

Closes #5428 
[Codepen](https://codepen.io/antoinerg/pen/XWjQygz?editors=1000)

Fixes indicator traces with a threshold equal to 0

---

package-lock.json
package.json

Use latest package with fixed inline comments
https://github.com/gl-vis/gl-heatmap2d/pull/8/files

bump gl-heatmap2d

---

.circleci/config.yml

Side effect of changes made in #5486.

Correct arguments passed to circleci tests

---

test/jasmine/assets/ie9_mock.js

remove unused IE9 file

---

tasks/test_requirejs.js

fixup throwing error in requirejs test

---

package.json

Script to help generating mathjax and mapbox baselines

---

package-lock.json
package.json

Fixes https://github.com/plotly/plotly.js/security/dependabot/package-lock.json/elliptic/open

Bump elliptic to v6.5.4 and uninstall it from root

---

package-lock.json
package.json

Addressing https://github.com/plotly/plotly.js/security/dependabot/package-lock.json/madge/open
See https://github.com/advisories/GHSA-753c-phhg-cj29

Bump madge v4

---

package-lock.json
package.json

Addressing https://github.com/plotly/plotly.js/security/dependabot/package-lock.json/xmlhttprequest-ssl/open
See https://github.com/advisories/GHSA-h4j5-c7cj-74xg

Bump karma from v5 to v6

---

package-lock.json
package.json

Bump karma dev-dependencies

---

package-lock.json
package.json

Addressing https://github.com/plotly/plotly.js/security/dependabot/package-lock.json/hosted-git-info/open
See https://github.com/advisories/GHSA-43f8-2h32-f4cj

bump node-sass v6

---

package-lock.json
package.json

Closes https://github.com/plotly/plotly.js/security/dependabot/package-lock.json/ws/open
See https://github.com/advisories/GHSA-6fc8-4gx4-v693.

Reinstall karma and bump jsdom to get ws 7.4.6 patch

---

README.md

Revise readme headers and more edits

---

package-lock.json

Addressing https://www.npmjs.com/advisories/1751

Audit fix glob-parent

---

package-lock.json
package.json

https://github.com/Automattic/node-canvas/compare/v2.7.0...v2.8.0

bump node-canvas 2.8.0 dev-dependency

---

package-lock.json
package.json

bump karma-firefox-launcher v2.1.1

---

package-lock.json
package.json

bump karma v6.3.4

---

test/image/compare_pixels_test.js

Addressing https://github.com/plotly/plotly.js/pull/5733#issuecomment-864154838

update flaky list for image test

---

README.md

Side effect of edits in https://github.com/plotly/plotly.js/commit/a670f78a530f24b62807cbe80293a0407910b907

correct readme links

---

package-lock.json
package.json

Bump turf bbox dependency to v6.4.0

---

package-lock.json
package.json

Bump turf area dependency to v6.4.0

---

.circleci/config.yml
.circleci/test.sh

rename flaky container

---

.circleci/config.yml

Make it easier to read commands.

Modify CircleCI config - remove extra dot pointing to current directory

---

test/image/compare_pixels_test.js

A bit of adjustment for one mock so that the image test can succeed.

increase compare tolerance for mapbox_geojson-attributes

---

.circleci/env_image.sh

Disable progress bar of pip install to avoid undesirable log files

---

draftlogs/5836_fix.md
src/components/fx/hover.js
src/traces/scatter/calc.js
src/traces/scatter/hover.js
src/traces/scattergl/hover.js
test/jasmine/tests/gl2d_click_test.js
test/jasmine/tests/hover_label_test.js

Revert " Fix scatter and scattergl hover on axes with period and adjust the unified hover position in respect to mean"

---

test/jasmine/tests/lib_number_format_test.js

Add tests for padding and alignment without formatting numbers

---

test/jasmine/tests/hover_label_test.js

change trace names in hover label test when all have end alignments

---

.circleci/config.yml

move up bundle-jasmine in config below other jasmine tests

---

test/image/compare_pixels_test.js

increase tolerance for flaky mocks

---

.circleci/env_image.sh

bump plotly.py to v5.2.1

---

package-lock.json
package.json

https://github.com/jsdom/jsdom/releases/tag/17.0.0

bump jsdom v17

---

.circleci/config.yml

i.e. to help check the size of new bundles

preview stats diff on ci

---

devtools/test_dashboard/devtools.js
devtools/test_dashboard/index-strict.html
devtools/test_dashboard/index.html

Add css transform input to devtool

---

package-lock.json
package.json

switch back to `3d-view` base repository now that https://github.com/mikolalysenko/3d-view/pull/1 is merge.

use 3d-view v2.0.1

---

package-lock.json
package.json

Helps tackle #897 | https://github.com/gl-vis/regl-scatter2d/pull/33

bump regl-scatter2d v3.2.8

---

package-lock.json
package.json

Help deterministic regl compiles while working on #897 | https://github.com/gl-vis/gl-text/pull/10

bump gl-text to v1.3.1

---

package-lock.json
package.json

Bump dev-dependencies Nov 22

---

package-lock.json

Closes https://github.com/plotly/plotly.js/security/dependabot/package-lock.json/nanoid/open
See https://github.com/advisories/GHSA-qrpm-p2h7-hrv2

`nanoid` package audit fix

---

package-lock.json

Address https://github.com/advisories/GHSA-wpg7-2c88-r8xv

bump simple-get to v3.1.1

---

package-lock.json
package.json

Bump some of the dev dependencies on Feb 4, 2022

---

package-lock.json

Closes https://github.com/plotly/plotly.js/security/dependabot/package-lock.json/ansi-regex/open
Details: https://github.com/advisories/GHSA-93q8-gq69-wqmw

Address `ansi-regex` audit warnings

---

package-lock.json
package.json

Closes https://github.com/plotly/plotly.js/security/dependabot/10

bump karma to v6.3.16

---

CONTRIBUTING.md

1. make sure they are not on the `master` branch of their fork as using `master` for a pull request would make it difficult to fetch `upstream` changes.
2. fetch …

Fixed Typo

---

package.json
tasks/bundle.js
tasks/extra_bundles.js

Revise extra bundles creation

---

package-lock.json

Closes https://github.com/plotly/plotly.js/security/dependabot

bump minimist 1.2.6

---

stackgl_modules/package-lock.json

Closes https://github.com/plotly/plotly.js/security/dependabot/13

bump minimist in stackgl_modules

---

src/traces/carpet/axis_defaults.js

It looks like a bug to me.
@alexcjohnson

fix clearing carpet.gridwidth

---

package-lock.json
package.json

Bump dev-dependencies May 6, 2022

---

package-lock.json
package.json

bump sass v1.52.1

---

package-lock.json
package.json

Bump dev dependencies - July 5, 2022

---

package-lock.json

Closes https://github.com/plotly/plotly.js/security/dependabot/15.

bump terser 4.8.1

---

package-lock.json
package.json

Bump certain dev-dependencies | Oct 21, 2022

---

src/traces/bar/defaults.js
src/traces/bar/grouping_defaults.js
src/traces/box/defaults.js
src/traces/funnel/defaults.js
src/traces/histogram/cross_trace_defaults.js
src/traces/waterfall/defaults.js

To simplify the use by other traces

separate file for grouping defaults

---

.circleci/config.yml
draftlogs/6334_add.md
package-lock.json
src/traces/icicle/attributes.js
src/traces/icicle/defaults.js
test/plot-schema.json

Fixes before the 2.17.0 release

Pre v2.17.0 fixes

---

package-lock.json

Closes 
https://github.com/plotly/plotly.js/security/dependabot/26 &
https://github.com/plotly/plotly.js/security/dependabot/27

bump json5 - audit fix

---

.circleci/config.yml
webpack.config.js

Fix es5 dist on master

---

package-lock.json

Closes https://github.com/plotly/plotly.js/security/dependabot/29.

bump `ua-parser-js` in `karma`

---

package-lock.json
package.json

Bump some dev dependencies

---

lib/locales/no.js

- Translation added
- Number format updated
Norwegian Reviewers: 
@stiberger
@mariuslarsson

Update locale no with new dictionary and number formats

---

package-lock.json

Addressing `npm audit` warning.

bump socket.io-parser

---

src/components/legend/draw.js

Fixes #6638, regression of #6535.

Fix legend groups toggle

---

src/plots/attributes.js
test/plot-schema.json

Fix typo in legendrank description.
See: https://github.com/plotly/plotly.py/pull/3824
1. make sure they are not on the `master` branch of their fork as using `master` for a pull request would make it …

Update legendrank description

---

draftlogs/6684_fix.md
src/components/legend/handle_click.js
test/jasmine/tests/legend_test.js

Fix isolated state detection in multi legend case

---

lib/locales/fi.js

Key "Download plot as a png" was missing " a"
and therefore was not translated in Finnish locale.
@archmoj
1. make sure they are not on the `master` branch of …

Fix key in Finnish locale

---

src/traces/box/plot.js
test/jasmine/tests/finance_test.js

Fixes #4729.
@Coding-with-Adam 

Clear empty boxes and candlestick using react

---

package-lock.json

bump follow-redirects

---

stackgl_modules/package-lock.json

Closes https://github.com/plotly/plotly.js/security/dependabot/40

Update `stackgl` dev dependency

---

src/components/modebar/manage.js
test/jasmine/tests/modebar_test.js

Adjust failing modebar test after merging PR #5879

---

package-lock.json
package.json

Adds support for node 20, min. supported version is node 18.
[Changelog](https://github.com/pahen/madge/blob/master/CHANGELOG.md)

Bump madge 6 -> 8

---

.circleci/config.yml

Closes #7126.
Continuation of @birkskyum's #7128

Pin down Chrome version to 127

---

.circleci/config.yml

test webgl jasmine on latest stable chrome i.e. v128 now

---

src/components/images/draw.js
src/plot_api/subroutines.js

This should fix the failing baseline tests

Fix hiding of axis lines and of images

---

draftlogs/7231_remove.md
src/plot_api/plot_api.js
src/plot_api/plot_config.js
test/plot-schema.json

Drop deprecated `plot3dPixelRatio` from config

---

.gitignore
tasks/util/bundle_wrapper.mjs

Do not keep empty CSS files generated by `esbuild` on the repository

---

CITATION.cff

Add the Citation file to Plotly.JS. Here is the [original issue](https://github.com/plotly/plotly.js/issues/7223#issuecomment-2429269291).

Add Citation file to Plotly.js

---

package-lock.json

Closes https://github.com/advisories/GHSA-8cj5-5rvv-wf4v

chore: Bump tar-fs 
